### ISSUE TITLE
Issue when getting Transactions from block

### ISSUE THREAD

**Issue by herecy** [ethereum/web3.js#4523] opened 2021-11-04 10:53 UTC
### 

- [X] This is not a Bug Report, Feature Request, or related to Documentation

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

Basically I am running these commands:

```
var blocknumber = await web3.eth.getBlockNumber();
var transaction = await web3.eth.getTransactionFromBlock(blocknumber, 0)
console.log(transaction)
```

But transaction never gets any output, regardless of the iterator. Block number is fetched properly, I can also get the block via web3.eth.getBlock(blocknumber), but the transactions cannot be fetched for some reason.

How can I debug this?

**Comment by nazarhussain** [comment] 2021-11-04 12:14
Hi @herecy  Thanks for reaching out to us. I tried the function `getTransactionFromBlock` and it works for me as expected. Here is my sample script I tried out. 

```ts
const Web3 = require("web3");

const web3 = new Web3(
  Web3.givenProvider ||
    "wss://mainnet.infura.io/ws/v3/xxxxxxxxxxxxxxx"
);

(async () => {
  console.log("%%%%% WEB3: ", web3.version);

  const blocknumber = await web3.eth.getBlockNumber();
  const transaction = await web3.eth.getTransactionFromBlock(blocknumber, 0);

  console.log({ blocknumber, transaction });
})().catch((e) => {
  console.log(e);
});

```
and I got the following output. 

```
%%% WEB3:  1.5.2
{
  blocknumber: 13550106,
  transaction: {
    accessList: [ [Object], [Object], [Object], [Object] ],
    blockHash: '0xe980f00398e3963480e40eea4de92bdcf2a56ab273c61a28c9e6a05a4be741af',
    blockNumber: 13550106,
    chainId: '0x1',
    from: '0x4970197593EF5aed9D2C33409b953F5f9bb22563',
    gas: 2000000,
    gasPrice: '129828579292',
    hash: '0x54b2a2d98849de7a66a924a0bfe1d8143c09f24112f523785c17dc48ac2a5f56',
    input: '0x0300cec21a85b5a7dc1630f9465d8409e2ac53313b70a71b9c0141d12a3600000000000000000000000000000000000000000000025aafa3d6fc922a59d90002656c00e1bcd96f256f224ad9112ff426ef0537330bb8',
    maxFeePerGas: '146057151703',
    maxPriorityFeePerGas: '0',
    nonce: 8997,
    r: '0x151c19e69b941076c8d27f927374a34507da0a41121e95397ae0e5b511e35c24',
    s: '0x112f6b10c3876676dcdf3191a05adbbfa91dae7e4d3a9a9688e2631f7ee385ae',
    to: '0x00000000008C4FB1c916E0C88fd4cc402D935e7D',
    transactionIndex: 0,
    type: 2,
    v: '0x0',
    value: '0'
  }
}
```

Please make sure your `web3` object is properly initiated and you are using a correct provider. 

If you still face the issue, please share more details as Node/Browser versions, web3 versions. Also share some reproducible code that helps us to quickly see the issue so we can look into its details.

**Comment by herecy** [comment] 2021-11-04 13:11
@nazarhussain Thank you very much for your helpful reply, I appreciate it greatly.

After some more debugging it seems the error narrows down to this:

Error: Invalid JSON RPC response: "<html>\n<head><title>403 Forbidden</title>

So it seems like the provider does not allow this method if I understand correctly.

**Comment by nazarhussain** [comment] 2021-11-04 14:07
Yes that's correct. Either it's not supported by the provider or it has some kind of rate limiting or firewall, but defiantly its the issue with the provider. 

I am closing this issue, feel free to reach to us if you came across anything else.

**Closed as completed by nazarhussain** 2021-11-04 14:07 UTC
Labels: Needs Clarification
