### ISSUE TITLE
Contract deploy promise never returns in beta.52

### ISSUE THREAD

**Issue by spalladino** [ethereum/web3.js#2681] opened 2019-04-14 20:33 UTC
### Description 

Awaiting on a transaction to `deploy` a `web3` contract in beta.52 never returns, even though the transaction does go through and the contract is deployed. Tested in ganache with both instant seal and 1s block time. The same snippet worked fine in beta.37.

#### Expected behavior

Awaiting on `Contract.deploy().send()` should return after the transaction is mined.

#### Actual behavior

Awaiting on `Contract.deploy().send()` never returns.

#### Steps to reproduce the behavior

1. Create a new web3 contract instance
2. Await on `Contract.deploy().send()`

#### Error Logs 

None, but ganache reports the transaction as successful:
```
  Transaction: 0xd74bac6e76aa75e9c9a8998cc0e1835acf38ddf92cd07d47e694709b12b7f58c
  Contract created: 0x5b1869d9a4c187f2eaa108f3062412ecf0526b24
  Gas usage: 412242
  Block Number: 44
  Block Time: Sun Apr 14 2019 17:27:16 GMT-0300 (Argentina Standard Time)
```

#### Gists

```js
const Web3 = require('web3');

async function main() {
  const web3 = new Web3('http://localhost:8545');
  const [from] = await web3.eth.getAccounts();
  const artifact = require('./Greeter.json');
  const data = artifact.compilerOutput.evm.bytecode.object;
  const abi = artifact.compilerOutput.abi;
  const Greeter = new web3.eth.Contract(abi, null, { data, gas: 1e6 });
  const greeter = await Greeter.deploy({ arguments: ["Hello"] }).send({ from });
  console.log(`Deployed at ${greeter.options.address}`);
}

main();
```

### Versions 
* web3.js: 1.0.0-beta.52
* nodejs: v10.13.0
* ethereum node: Ganache CLI v6.4.0 (ganache-core: 2.5.1)

**Comment by nivida** [comment] 2019-04-14 20:52
Thanks for opening this issue! 
Did you configure the ``transactionConfirmationBlocks`` as described [here](https://web3js.readthedocs.io/en/1.0/web3.html#options)?

**Comment by spalladino** [comment] 2019-04-14 21:00
Adding that configuration fixed the issue, thanks! That said, I would expect the option to have a reasonable default value if it is not set.

**Comment by ejwessel** [comment] 2019-04-14 21:23
I too was able to fix this with `transactionConfirmationBlocks`, but if I'm developing locally with ganache and deploying I need to manually mine a block in order to get a response.

Is there a reasonable way to get around having to do this manual step?

**Comment by szerintedmi** [comment] 2019-04-14 21:38
i think I have the same issue, see #2661

**Comment by nivida** [comment] 2019-04-14 21:39
@ejwessel We have an issue with the transaction confirmation workflow over an HTTP connection as mentioned from @szerintedmi. Because of this will I close this issue.

**Closed as completed by nivida** 2019-04-14 21:39 UTC

**Comment by levino** [comment] 2019-04-16 06:26
As long as the issue is not fixed, it should be left open.

**Comment by nivida** [comment] 2019-04-16 06:55
It's a duplication of #2661 @Levino
