### ISSUE TITLE
Docs don't mention that constant/view/pure functions may return an error if smart contract reverts

### ISSUE THREAD

**Issue by richard-ramos** [ethereum/web3.js#1668] opened 2018-05-29 18:32 UTC
In web3.js/docs/web3-eth-contract.rst  , in the documentation for *methods.myMethod.call*, it doesn't mention that the promise will fail when the smart contract method invoked triggers a require/revert/assert/throw . 

Example: 
```
pragma solidity ^0.4.24;
contract Test  {
  function ABC() public view returns(uint256){
    require(true == false);
    return 1;
  }
}
```
This will return an error: "couldn't decode uint256 from ABI: 0x" that needs to be caught with a try/catch block. Since instead of returning default values for the output parameters, it throws an exception (which seems like the right thing to do), it would be useful to mention this in the documentation.

**Comment by nivida** [comment] 2018-08-10 07:08
Duplicate of: https://github.com/ethereum/web3.js/issues/1639

**Closed by nivida** 2018-08-10 07:08 UTC
