### ISSUE TITLE
Subscription for logs, unexpected error

### ISSUE THREAD

**Issue by borispovod** [ethereum/web3.js#1930] opened 2018-09-10 15:32 UTC
When i'm trying to subscribe for logs, and using parameters fromBlock/toBlock i'm getting error after catching latest log in the latest block.

**Web3**: 1.0.0-beta.36
**Geth**: wss://mainnet.infura.io/ws

To reproduce:
```js
web3.eth.subscribe('logs', {
    fromBlock: from,
    toBlock: to
}, (err, res) => {
    console.log(err, res)   
})
```

Error output:
```
Error: Returned error: invalid from and to block combination: from > to
    at Object.ErrorResponse (/Users/boris/Documents/indexing-node/node_modules/web3-core-helpers/src/errors.js:29:16)
    at Object.<anonymous> (/Users/boris/Documents/indexing-node/node_modules/web3-core-requestmanager/src/index.js:140:36)
    at /Users/boris/Documents/indexing-node/node_modules/web3-providers-ws/src/index.js:121:44
    at Array.forEach (<anonymous>)
    at W3CWebSocket.WebsocketProvider.connection.onmessage (/Users/boris/Documents/indexing-node/node_modules/web3-providers-ws/src/index.js:98:36)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/boris/Documents/indexing-node/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/Users/boris/Documents/indexing-node/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/Users/boris/Documents/indexing-node/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at emitOne (events.js:116:13)
    at WebSocketConnection.emit (events.js:211:7)
    at WebSocketConnection.processFrame (/Users/boris/Documents/indexing-node/node_modules/websocket/lib/WebSocketConnection.js:552:26)
    at /Users/boris/Documents/indexing-node/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by kyriediculous** [comment] 2018-09-14 13:45
What's the value of from and to?

**Comment by nivida** [comment] 2018-10-31 14:14
I'll close this issue because the creator does not respond.

**Closed as completed by nivida** 2018-10-31 14:14 UTC

**Comment by wbt** [comment] 2020-05-29 22:49
Might be fair to assume this was a predating duplicate of [#3207](https://github.com/ethereum/web3.js/issues/3207).
