### ISSUE TITLE
new web3-eth-abi decodeLog throw error when the event's input are all indexed

### ISSUE THREAD

**Issue by libotony** [ethereum/web3.js#2065] opened 2018-11-23 02:54 UTC
When the input of an event are all indexed, go-ethereum's JSON-RPC will response with data '0x', it will throw an error cause by the following code

``` javascript
ABICoder.prototype.decodeParameters = function (outputs, bytes) {
    if (!bytes || bytes === '0x' || bytes === '0X') {
        throw new Error('Returned values aren\'t valid, did it run Out of Gas?');
    }
    //...
}
```

I found the following test code, I assume `Line 82` should be `0x` not empty string

https://github.com/ethereum/web3.js/blob/0d54d94e637832abf97834e4fc444fbff87f874b/test/eth.abi.decodeLog.js#L70-L91

**Comment by sawyna** [comment] 2018-11-26 14:42
I'd like to work on it.

**Comment by dileepfrog** [comment] 2018-11-27 21:14
Confirmed same with 1.0.0-beta.36, appears to be a regression from unaffected 1.0.0-beta.35

**Comment by krzkaczor** [comment] 2018-12-03 15:06
Just in case you're wondering, `ganache` in this case returns: `0x00` which works.

**Comment by krzkaczor** [comment] 2018-12-03 15:32
btw. i think this one is related: https://github.com/ethereum/web3.js/issues/1916

**Comment by conscott** [comment] 2018-12-05 08:44
Any simple workaround for this? My contract event filters are now broken.

**Comment by krzkaczor** [comment] 2018-12-05 08:47
@conscott I didn't manage to prepare a PR fixing it since current develop branch is much different so I used [patch-package](https://www.npmjs.com/package/patch-package) to fix it locally and create git patch applied on every `yarn install`. A dirty solution, but it works 🤷‍♂️ 

Here's patch:
```
patch-package
# FIX FOR: https://github.com/ethereum/web3.js/issues/2065
--- a/node_modules/web3-eth-abi/src/index.js
+++ b/node_modules/web3-eth-abi/src/index.js
@@ -222,7 +222,7 @@ ABICoder.prototype.decodeParameter = function (type, bytes) {
  * @return {Array} array of plain params
  */
 ABICoder.prototype.decodeParameters = function (outputs, bytes) {
-    if (!bytes || bytes === '0x' || bytes === '0X') {
+    if (!bytes) {
         throw new Error('Returned values aren\'t valid, did it run Out of Gas?');
     }
```

**Comment by conscott** [comment] 2018-12-05 10:10
thanks @krzkaczor !

**Comment by rmujica** [comment] 2018-12-12 23:42
the behavior still occurs on 1.0.0-beta.37 even though is reported on the changelog to be fixed. how can I be of more help?

**Comment by travisdmathis** [comment] 2018-12-20 15:08
This is still not resolved in beta 37. I've monkey patched it for now, but it would be nice to get an official fix. Anything I can do to help, please let me know! @krzkaczor

**Comment by rmujica** [comment] 2018-12-26 21:07
@travisdmathis what is your patch?

**Comment by libotony** [comment] 2018-12-27 03:55
I just did a test in beta 37, the test codes are:

``` javascript
const ethABI = require('web3-eth-abi')

const ABI = [{
    type: 'string',
    name: 'MyString',
    indexed: true
}, {
    type: 'bool',
    name: 'IsTrue',
    indexed: true
}, {
    type: 'uint8',
    name: 'myNumberWork',
    indexed: true
}]

const data = '0x'
const topics = ['0xffdd000000000000000000000000000000000000000000000000000000000003', '0x0000000000000000000000000000000000000000000000000000000000000000', '0x000000000000000000000000000000000000000000000000000000000000fd44']

console.log(ethABI.decodeLog(ABI, data, topics))
```

Seems the problem is solved, @travisdmathis @rmujica can you provide some cases that will produce the error? Otherwise, I will close this issue

**Closed as completed** 2019-01-07 01:58 UTC
Labels: Bug
