### ISSUE TITLE
Truffle-migtration-4.x/Contract call falls to wrong overload

### ISSUE THREAD

**Issue by nikoulai** [ethereum/web3.js#6091] opened 2023-05-15 11:48 UTC
In some truffle tests they have overloaded functions, and when I was doing the migration I was getting errors about the arguments I was passing, because they were tested against the other overloaded signature. 

It's strange behavior, because, this should be fixed in https://github.com/web3/web3.js/pull/5570

```
// Here multicall is a function with two overloads ("function multicall(bytes[] calldata datas)" &  "multicall(uint deadline, bytes[] calldata datas)")
    //value "0x589a53140000000000000000000000003b071016a3f491ef4067e847f6c2410a2ef8ec73000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000008,0x35287014,0xa2fc12280000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000005900000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000003e000000000000000000000000000000000000000000000000000000000000000568656c6c6f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e696e646563697068657261626c65000000000000000000000000000000000000"
    //at "/0" must pass "uint256" validation
```

See the test:
https://github.com/trufflesuite/truffle/blob/38edf2ee94dc5a21d6fa3546042ea7256f509565/packages/decoder/test/current/test/wire-test.js#L1267

**Comment by jdevcs** [comment] 2023-05-30 11:36
@spacesailor24 related https://github.com/web3/web3.js/issues/6091 ?

**Comment by jdevcs** [comment] 2023-05-30 11:37
@spacesailor24 https://github.com/web3/web3.js/issues/6128 related ?

**Comment by Spacesai1or** [comment] 2023-06-01 02:20
I've created [a test file](https://github.com/web3/web3.js/blob/c748c692f72cc5c4be8a8a6046b5277431840000/packages/web3-eth-contract/test/integration/contract_simple_overloaded.test.ts) that tests various overloaded function `call`s and `send`s and don't get the same validation error. I've even copied over the `multicall` tests that are failing in Truffle repo and those also pass inside of web3.js

For reference, this is contract I'm using to test, you can call every method on this contract without error:

```solidity
pragma solidity 0.8.19;

contract SimpleOverload {
	uint256 public secret;
	string public someString;

	constructor() {
		secret = 42;
	}

	function getSecret() public view returns (uint256) {
		return secret;
	}

	function getSecret(uint256 numToAdd) public view returns (uint256) {
		return secret + numToAdd;
	}

	function getSecret(
		uint256 numToAdd,
		string calldata _someString
	) public view returns (uint256, string memory) {
		return (secret + numToAdd, string.concat(someString, _someString));
	}

	function setSecret() public {
		secret = 42;
	}

	function setSecret(uint256 numToAdd) public {
		secret += numToAdd;
	}

	function setSecret(uint256 numToAdd, string calldata _someString) public {
		secret += numToAdd;
		someString = _someString;
	}

	function multicall(bytes[] calldata datas) external {
		for (uint i = 0; i < datas.length; i++) {
			address(this).call(datas[i]);
		}
	}

	function multicall(uint deadline, bytes[] calldata datas) external {
		require(block.timestamp <= deadline);
		for (uint i = 0; i < datas.length; i++) {
			address(this).call(datas[i]);
		}
	}
}
```

**Comment by Spacesai1or** [comment] 2023-06-02 07:05
When `multicall` is called [here](https://github.com/trufflesuite/truffle/blob/38edf2ee94dc5a21d6fa3546042ea7256f509565/packages/decoder/test/current/test/wire-test.js#L1297), for some reason I've yet to identify, the value of the argument, `encodedTxs`, is being duplicated when it's passed to the web3.js generated function that's returned by our [_createContractMethod](https://github.com/web3/web3.js/blob/88ac791bff7641823ea8281d9b63bdb085b5d076/packages/web3-eth-contract/src/contract.ts#L860). When the created contract method is being executed (because of `deployedContract.multicall(encodedTxs)` in Truffle's tests) the value of `params` is:

```typescript
[
  [
    "0x589a53140000000000000000000000003b071016a3f491ef4067e847f6c2410a2ef8ec73000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000008",
    "0x35287014",
    "0xa2fc12280000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000005900000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000003e000000000000000000000000000000000000000000000000000000000000000568656c6c6f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e696e646563697068657261626c65000000000000000000000000000000000000",
  ],
  [
    "0x589a53140000000000000000000000003b071016a3f491ef4067e847f6c2410a2ef8ec73000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000008",
    "0x35287014",
    "0xa2fc12280000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000005900000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000003e000000000000000000000000000000000000000000000000000000000000000568656c6c6f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e696e646563697068657261626c65000000000000000000000000000000000000",
  ],
];
```

When it should just be:

```typescript
[
  [
    "0x589a53140000000000000000000000003b071016a3f491ef4067e847f6c2410a2ef8ec73000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000008",
    "0x35287014",
    "0xa2fc12280000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000005900000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000003e000000000000000000000000000000000000000000000000000000000000000568656c6c6f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e696e646563697068657261626c65000000000000000000000000000000000000",
  ],
];
```

Because the length of `params` is `2` instead of the expected `1`, the `arrayOfAbis` returned from [this logic](https://github.com/web3/web3.js/blob/88ac791bff7641823ea8281d9b63bdb085b5d076/packages/web3-eth-contract/src/contract.ts#L871-L873):

```typescript
const arrayOfAbis: AbiFunctionFragment[] = abis.filter(
  (_abi) => (_abi.inputs ?? []).length === params.length
);
```

is:

```typescript
[
  {
    inputs: [
      { internalType: 'uint256', name: 'deadline', type: 'uint256' },
      { internalType: 'bytes[]', name: 'datas', type: 'bytes[]' }
    ],
    name: 'multicall',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x5ae401dc',
    constant: false,
    payable: false
  }
]
```

which is incorrectly the abi of the `multicall` function we don't want. This is what's causing `encodedTxs` to be compared to the incorrect validation rules

---

Interestingly, the Truffle test the executes the other `multicall` function (the one with multiple arguments: `uint256` and `bytes[]`) is also failing because of a similar scenario, however it seems that only the `bytes` value of `encodedTxs` is duplicated. This is the value of `params` when the web3.js generated function from `_createContractMethod` is called:

```typescript
[
  4503599627370495,
  [
    "0x589a53140000000000000000000000003b071016a3f491ef4067e847f6c2410a2ef8ec73000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000008",
    "0x35287014",
    "0xa2fc12280000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000005900000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000003e000000000000000000000000000000000000000000000000000000000000000568656c6c6f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e696e646563697068657261626c65000000000000000000000000000000000000",
  ],
  [
    "0x589a53140000000000000000000000003b071016a3f491ef4067e847f6c2410a2ef8ec73000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000008",
    "0x35287014",
    "0xa2fc12280000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000005900000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000003e000000000000000000000000000000000000000000000000000000000000000568656c6c6f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e696e646563697068657261626c65000000000000000000000000000000000000",
  ],
];
```

The expected value of `params` is:

```typescript
[
  4503599627370495,
  [
    "0x589a53140000000000000000000000003b071016a3f491ef4067e847f6c2410a2ef8ec73000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000008",
    "0x35287014",
    "0xa2fc12280000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000005900000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000003e000000000000000000000000000000000000000000000000000000000000000568656c6c6f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e696e646563697068657261626c65000000000000000000000000000000000000",
  ]
];
```

This causes

```typescript
const arrayOfAbis: AbiFunctionFragment[] = abis.filter(
  (_abi) => (_abi.inputs ?? []).length === params.length
);
```

to return `0`, triggering the execution of:

```typescript
if (abis.length === 1 || arrayOfAbis.length === 0) {
  abiParams = this._getAbiParams(methodAbi, params);
  validator.validate(abi.inputs ?? [], abiParams);
}
```

which ultimately causes the function call where `encodedTxs` is of type `(uint256, bytes[])` to be validated against `(bytes[])`

---

So, something, outside of web3.js I believe, is causing the `bytes` value of `encodedTxs` to be duplicated causing the incorrect validation rules to be applied when `multicall` is called in the tests. As mentioned previously, none of this seems to be an issue when executing the tests added in #6140, which is why I believe the cause of this bug lies within the updates made to Truffle

**Comment by mpetrunic** [comment] 2023-06-02 08:44
@spacesailor24 Bug is in call to `args = utils.convertToEthersBN(args);` in prepareCall: https://github.com/trufflesuite/truffle/blob/38edf2ee94dc5a21d6fa3546042ea7256f509565/packages/contract/lib/execute.js#L87

Here is the fix: https://github.com/nazarhussain/truffle/pull/1/files

**Comment by mpetrunic** [comment] 2023-06-07 15:34
Fixed with https://github.com/nazarhussain/truffle/pull/1/files

**Closed as completed by mpetrunic** 2023-06-07 15:34 UTC
Labels: Bug, Investigate, 4.x
