### ISSUE TITLE
BigNum comparison wrong result

### ISSUE THREAD

**Issue by leckylao** [ethereum/web3.js#4914] opened 2022-04-02 12:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="133" alt="image" src="https://user-images.githubusercontent.com/148800/161383780-c45cd63c-1f00-45a5-b05d-e5f0985d718f.png">
<img width="748" alt="image" src="https://user-images.githubusercontent.com/148800/161383776-e4d6bab9-52fc-485b-8d57-8cf2b2ccad0b.png">

5 Ether compare with 32 Ether return true. 

### Expected Behavior

Expected 5 Ether compare with 32 Ether return false 

### Steps to Reproduce

```
Web3 = require('web3')
Web3.utils.toWei('5', 'ether') >= Web3.utils.toWei('32', 'ether')
```

### Web3.js Version

1.7.1

### Environment

- Operating System: MacOS
- Browser: N/A
- Node.js Version: 16.3
- NPM Version: 7.18.1

**Comment by leckylao** [comment] 2022-04-02 13:35
<img width="485" alt="image" src="https://user-images.githubusercontent.com/148800/161385702-7e1073bb-a3a2-46fe-852e-9f025ce575f2.png">

Looks like it actually return as String and that caused the issue. I would suggest it should return BN/BigNumber and that's what ethersJS do, which would be a better practice.

**Comment by nazarhussain** [comment] 2022-04-06 10:43
Hi @leckylao for reaching out to us. It's actually not a bug but the desired behavior. As you want to first convert string output to big number and then use it's comparison functions in [bn.js](https://github.com/indutny/bn.js/).

```javascript
const Web3 = require("web3");

const val1 = Web3.utils.toBN(Web3.utils.toWei("5", "ether"));
const val2 = Web3.utils.toBN(Web3.utils.toWei("32", "ether"));

console.log(val1.gte(val2));
```

For your other comment, we had refactored the whole library to support native BigInt support. That will be released as 4.x alpha.

**Closed as completed by nazarhussain** 2022-04-06 10:43 UTC
Labels: Bug
