### ISSUE TITLE
Uncaught "TypeError: (intermediate value).data is undefined" calling a contract function with insufficient funds on Polygon

### ISSUE THREAD

**Issue by nicos99** [ethereum/web3.js#6611] opened 2023-11-20 22:10 UTC
#### Expected behavior

Given `handleRevert = true` and a dApp frontend using MetaMask as provider connected to Polygon PoS, I can catch an "_err: insufficient funds for gas * price + value: ..._" error through `myContract.methods.MyUsefullMethode(param).call(options).catch.(err => { // manage error })` when there is insufficient funds for the transaction.

#### Actual behavior

`.call().catch()` is never called and an error is only logged in the web browser consol : "_TypeError: (intermediate value).data is undefined_".

#### Steps to reproduce the behavior

I think it's quite easy to reproduce by calling an existing contract on Polygon (I can provide my site address if asked). The actuel RPC server is https://polygon-mainnet.infura.io.

#### Logs

``` js
21:43:58,929 MetaMask - RPC Error: Internal JSON-RPC error. 
Object { code: -32603, message: "Internal JSON-RPC error.", data: {…}, stack: "Error@moz-extension://8de06240-0fd5-4f6d-8dca-318e48de4a2c/runtime-lavamoat.js:7554:17\ni@moz-extension://8de06240-0fd5-4f6d-8dca-318e48de4a2c/common-3.js:16:10940\ns@moz-extension://8de06240-0fd5-4f6d-8dca-318e48de4a2c/common-3.js:16:13880\ninternal@moz-extension://8de06240-0fd5-4f6d-8dca-318e48de4a2c/common-3.js:16:14491\nu@moz-extension://8de06240-0fd5-4f6d-8dca-318e48de4a2c/background-0.js:7:49968\nr.createFetchMiddleware/<@moz-extension://8de06240-0fd5-4f6d-8dca-318e48de4a2c/background-0.js:7:50971\n" }
​
code: -32603
​
data: Object { code: -32000, message: "err: insufficient funds for gas * price + value: address 0x8e1ef29660EF4569181a7bCCd678427bcE1223b4 have 78119475604576697598 want 80000000000000000000 (supplied gas 600000000)" }
```

![image](https://github.com/web3/web3.js/assets/32513365/60df195e-aae3-415f-b572-e7d00bca89d9)

#### Environment

- web3.js : 1.10.3
- Browser : with FireFox 119.0.1 (64 bits) + MetaMask 11.4.1

**Comment by nicos99** [comment] 2023-11-20 23:53
[this fix](https://github.com/nicos99/web3.js/commit/7c5f0bc2db7165d281ba5e203d43375e5ba01b77) seems to work

**Comment by Muhammad-Altabba** [comment] 2023-11-21 16:09
Thanks @nicos99 for opening the issue and sharing your findings.
Could you open an MR for this fix?

Also I encourage you to check with web3.js version 4. As version 1 will be deprecated later.
So, could you, please, check with version 4 and share your findings?

**Comment by nicos99** [comment] 2023-11-23 13:13
ok, I'll check with version 4 and open a PR (probably this weekend)

**Comment by nicos99** [comment] 2023-11-26 23:01
Then @Muhammad-Altabba it turns out that with version 4.2.2 (from 'https://cdn.jsdelivr.net') there is no problem!
The error object caught is generic (`.message`: _"Internal JSON-RPC error."_) but we have access to the `data` sub objet that gives details I was looking for (`.data.message`: _"err: insufficient funds for gas * price + value: address 0x<HHH...> have <AAA...> want <BBB...> (supplied gas <GGG...>)"_, the exact message differs slightly between the networks/provider but the structure is identical).

**Comment by Muhammad-Altabba** [comment] 2023-11-26 23:15
Congratulations @nicos99 that version 4 worked with your case.
It is hard to fulfill the different specifications of every network (in your case Polygon). But we try our best :smile: .

Since the issue is not present in web3 v4. I will suggest to close this issue. And for those who use web3 v1, we encourage them to upgrade. Does this work for your case?

**Comment by nicos99** [comment] 2023-11-27 13:26
Thank you @Muhammad-Altabba. I've partialy switched to web3 v4 for my dApp and it will require more validation so for now I'm still on 1.x with [my fix](https://github.com/nicos99/web3.js/commit/7c5f0bc2db7165d281ba5e203d43375e5ba01b77). I think this protects against other bugs of the same kind (because we are in a scope not protetced by a try/catch so we have to check carefully each fields access) so I'm going to open a PR soon. I suggest you can tag this bug "1.x" and close it if the PR is not merged quikly.

**Comment by Muhammad-Altabba** [comment] 2024-01-05 07:49
Thanks @nicos99 for your understanding, and many thanks for reporting this and trying to fix it on 1.x.

And for those who encounter this issue they can upgrade to version 4.x.

**Closed as completed by Muhammad-Altabba** 2024-01-05 07:49 UTC
Labels: 1.x
