### ISSUE TITLE
getTransaction is not being validated correctly

### ISSUE THREAD

**Issue by meyer9** [ethereum/web3.js#918] opened 2017-07-05 19:16 UTC
Version: 1.0.0-beta

Steps to reproduce:
1. Setup Web3 to talk to Geth
2. Run `web3.eth.getTransaction('some valid tx hash looking like 0x0e963a8a39e3772d46cdbb1cf4577ccab0cad1420b31cab06954692c2a1111cf')`

```
Error: Provided address "0x0e963a8a39e3772d46cdbb1cf4577ccab0cad1420b31cab06954692c2a1111cf" is invalid, the capitalization checksum test failed, or its an indrect IBAN address which can't be converted.
```

Looks like it's running address validation rather than transaction hash validation.

**Comment by meyer9** [comment] 2017-07-05 19:21
Either this needs to be updated, or a new method needs to be added: https://github.com/ethereum/web3.js/blob/1.0/packages/web3-utils/src/utils.js#L77

**Comment by meyer9** [comment] 2017-07-05 19:25
We also aren't testing that each method has the correct formatter.

**Comment by dev1644** [comment] 2019-01-07 12:37
I am unable to reproduce this behavior in the current version, I think it got fixed in the recent version.

@nivida I think we can close this issue.

**Closed** 2019-01-17 02:59 UTC
Labels: clarification needed
