### ISSUE TITLE
decode dynamic array in a struct results in error

### ISSUE THREAD

**Issue by chaitanyapotti** [ethereum/web3.js#3294] opened 2020-01-02 14:07 UTC
#### Expected behavior

```js
const web3 = require("web3-eth-abi");
console.log(
  web3.decodeParameter(
    {
      Epoch: {
        id: "uint256",
        n: "uint256",
        k: "uint256",
        t: "uint256",
        nodeList: "address[]",
        prevEpoch: "uint256",
        nextEpoch: "uint256"
      }
    },
    "0x000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002000000000000000000000000bf0fa6c2ef61da5206adb11fb74e3d821342bac00000000000000000000000001cf7defe552c9f030c79f1d812dcc745667c97c9"
  )
);
```

The above code shouldn't throw an error and decode parameters correctly.

#### Actual behavior
Throws an error
```
Error: insufficient data for dynamic array length (arg="nodeList", coderType="array", value="0x")
    at Object.throwError (/home/chai/source/repos/torus/torus-public/solidity/node_modules/ethers/utils/errors.js:68:17)
    at CoderArray.decode (/home/chai/source/repos/torus/torus-public/solidity/node_modules/ethers/utils/abi-coder.js:716:24)
```

#### Steps to reproduce the behavior
run the above script

#### Versions
npm: 6.13.4
node: 10.16.3
web3: 1.2.4
os: all
device: all
[NPM, Node, Web3.js, OS, device...]

**Comment by nivida** [comment] 2020-01-06 09:05
@chaitanyapotti Thanks for opening this issue! We will test and if required fix it asap.

**Comment by holgerd77** [comment] 2020-02-14 17:52
Some context: tested this locally and can confirm the error message.

Error is thrown in the `ethers` (installed dependency version `v4.0.0-beta.3`) ABI decoder [here](https://github.com/ethers-io/ethers.js/blob/master/src.ts/utils/abi-coder.ts#L871).

Tried to install a newer `ethers` version (`v4.0.44`), error persists.

**Comment by holgerd77** [comment] 2020-02-14 18:13
@chaitanyapotti Just tested this with leaving the `nodeList` param in your JSON definition, which - read from the error message - is the cause of the problem.

This succeeds with the following output:

```
[
  '1',              '5',
  '3',              '1',
  '224',            '0',
  id: '1',          n: '5',
  k: '3',           t: '1',
  prevEpoch: '224', nextEpoch: '0'
]
```

Are you sure the encoded hex string you provide include the data for the `nodeList` parameter?

**Comment by cgewecke** [comment] 2020-06-09 21:08
Closing because comment above seems to resolve. Please ping if that's not the case.

**Closed as completed by cgewecke** 2020-06-09 21:08 UTC
Labels: Needs Clarification, 1.x
