### ISSUE TITLE
encodeParameters is broken on tuples

### ISSUE THREAD

**Issue by cd1m0** [ethereum/web3.js#6307] opened 2023-07-25 02:23 UTC
#### Expected behavior

Running this code should succeed:

```
const ethABI = require("web3-eth-abi");
ethABI.encodeParameters(["tuple(uint256,uint256)"], [[1,2]]);
```
#### Actual behavior

Running this code results in the below exception:

```
Uncaught AbiError: Parameter encoding error
    at Object.encodeParameters (/home/dimo/work/consensys/sol2maruir/node_modules/web3-eth-abi/lib/commonjs/api/parameters_api.js:67:15) {
  innerError: TypeError: Cannot read properties of undefined (reading 'length')
      at formatParam (/home/dimo/work/consensys/sol2maruir/node_modules/web3-eth-abi/lib/commonjs/utils.js:149:30)
      at /home/dimo/work/consensys/sol2maruir/node_modules/web3-eth-abi/lib/commonjs/utils.js:197:48
      at Array.forEach (<anonymous>)
      at modifyParams (/home/dimo/work/consensys/sol2maruir/node_modules/web3-eth-abi/lib/commonjs/utils.js:188:18)
      at Object.encodeParameters (/home/dimo/work/consensys/sol2maruir/node_modules/web3-eth-abi/lib/commonjs/api/parameters_api.js:60:45)
      at REPL20:1:8
      at Script.runInThisContext (node:vm:122:12)
      at REPLServer.defaultEval (node:repl:570:29)
      at bound (node:domain:433:15)
      at REPLServer.runBound [as eval] (node:domain:444:12),
  code: 205
```
#### Steps to reproduce the behavior

1. Install web3-eth-abi version 4.0.3
2. Run above code in node

#### Environment

Node 20

**Comment by avkos** [comment] 2023-07-26 01:51
This is a bug and should be investigated and fixed. Thank you for helping to find it.

**Comment by blitz-1306** [comment] 2023-07-26 06:59
Additionally, for those who else would hit this issue: there is a workaround if you remove `tuple` and pass types in parens. An example:
```javascript
const ethABI = require("web3-eth-abi");

console.log(ethABI.encodeParameters(["(uint256,uint256)"], [[1,2]]));
```
Results
```
0x00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002
```

**Comment by krzysu** [comment] 2024-10-07 12:34
@jdevcs @avkos looks like this issue was solved by replacing abi coder in PR #6385  - a few months after the issue was reported. I am not able to reproduce it now. There is a unit test for `encodeParameters` with tuple as an input here (link to the fixture used in the test) https://github.com/web3/web3.js/blob/4.x/packages/web3-eth-abi/test/fixtures/data.ts#L744

**Comment by krzysu** [comment] 2024-10-07 12:53
The only improvement I see regarding this issue is in the fixture used in the integration test for `web3.abi`. The second object in the `validEncodeParametersData` fixture array isn’t used anywhere, and its expected output is obviously incorrect. You can find the fixture here: https://github.com/web3/web3.js/blob/4.x/packages/web3/test/shared_fixtures/data.ts#L35

**Comment by krzysu** [comment] 2024-10-09 07:40
I’m closing this issue since it has been resolved.

**Closed as completed by krzysu** 2024-10-09 07:40 UTC
Labels: Bug, Investigate, 4.x
