### ISSUE TITLE
Error Reason

### ISSUE THREAD

**Issue by verma-shu6ham** [ethereum/web3.js#5677] opened 2022-12-02 12:44 UTC
### What's up?

Hi,  in the function given below I am reverting with the message "Insufficient Balance."  in React error object I am not getting error reason but on other hand in the ganache console error reason is showing, how will I get reason in react.
   

### Examples/References

       function registerJob(
           string memory _jobName,
           string memory _jobDescription,
          uint256 _jobBudget
       ) external payable {
            require(extraFund() + msg.value >= _jobBudget, "Insufficient Balance.");
                 uint32 timeNow = uint32(block.timestamp);
                 _jobIds++;
                 Job storage _job = _jobs[_jobIds];
                 _job.jobId = _jobIds;
                 _job.jobName = _jobName;
                 _job.jobDescription = _jobDescription;
                 _job.jobOwner = payable(msg.sender);
                 _job.jobWorker = payable(0x0);
                 _job.isCompleted = false;
                 _job.isJobValid = true;
                 _job.jobRegisteredDate = timeNow;
                 _job.jobStartedDate = 0;
                 _job.jobCompletedDate = 0;
                 _job.jobBudget = _jobBudget;
                 _job.jobSettledAmount = 0;
                 _liveJobs.add(_jobIds);
                 _fundByJobOwner[msg.sender] += msg.value;
                 _jobOwnerFundLocked[msg.sender] += _jobBudget;
                 emit JobRegistered(msg.sender, _jobBudget, _jobName, _jobIds);
    }
}

![image](https://user-images.githubusercontent.com/106945859/205293916-80f97631-38c6-43e4-b44e-f44cd660fbc5.png)
![image](https://user-images.githubusercontent.com/106945859/205293982-c3c666f6-2c94-42fb-a39d-7ae5aa1a2f8a.png)

**Comment by Spacesai1or** [comment] 2022-12-06 21:52
Hi there, thank you for bringing this to our attention! Can you provide a code snippet that reproduces what's happening in your screenshots?

**Comment by Muhammad-Altabba** [comment] 2022-12-07 08:48
Hello @shubham-verma-neo ,
To catch the error you simply put the send transaction function inside a try-catch and then you can check the error object and the error message:
```
try{
    // your send transaction code...
} catch(error){
    console.log("error message:", error.message):
    console.log("complete error object:", error.message);
}
```

**Comment by sachin-kiwi** [comment] 2022-12-08 18:16
Hi, I am performing blockchain transactions using web3js + nodejs. 
While submitting the mint transaction if I got error then I store transaction id and later ping it to check its status using getTransactionReceipt. It is help generally if handling Error - Transaction still not mined after 750s error but apart from it if i get  insufficient funds gas*gasPrice+value error during submission, my system can not differentiate it. Is there any approach for error filtering if its concerns delay in blockchain level or account issue ?

**Comment by sachin-kiwi** [comment] 2022-12-08 18:22
In Simple terms, after calling sendSignedTransaction if i get error is it possible to filter out error based on error message like it is due transaction logic issue or delay at blockchain end like timeout after 750s

**Comment by verma-shu6ham** [comment] 2022-12-12 11:43
try {
            _receipt = await contract.methods
                .registerJob(jobType, jobDes, web3.utils.toWei(jobBudget, "ether"))
                .send({
                    value: web3.utils.toWei(depositETH, "ether"),
                    from: accounts[0],
                });
            if (_receipt.status) {
                setReceipt(_receipt)
                setTx(true);
            }
        } catch (error) {
            console.log("error: ", error);
            console.log("error.message: ", error.message);
        }
![image](https://user-images.githubusercontent.com/106945859/207036762-3c936a3e-891d-4b47-95fc-1d655229778c.png)
![image](https://user-images.githubusercontent.com/106945859/207036412-cd57d567-8e62-4a8e-a080-e3e40ffaa9ee.png)
![image](https://user-images.githubusercontent.com/106945859/207036478-592c5ff4-5388-437d-a3bb-23fb0dd8feec.png)
![image](https://user-images.githubusercontent.com/106945859/207036342-5ad2ad9d-ed6f-4a95-a1fc-4e092d867c89.png)



>

**Comment by mconnelly8** [comment] 2023-02-07 21:33
Discussed in meeting today.  Need to investigate further.

**Comment by folego** [comment] 2023-02-08 19:19
I found that using `{ handleRevert: true }` as an option could give the revert reason, but it's not going through. There is an error inside the creation of the error message trying the get the reason message.

![image](https://user-images.githubusercontent.com/20648959/217629821-94cfc2f8-e863-4c19-96c2-08f1d520c889.png)

I also found this discussion: https://forum.openzeppelin.com/t/how-to-use-handlerevert-in-web3-for-fetching-transaction-reverting-reason/14670/3, and it seems the fix implemented here solved the issue. I can't test yet because ViteJs doesn't care about the changes in node_modules folder.

**Comment by Muhammad-Altabba** [comment] 2023-03-16 11:33
Hello @shubham-verma-neo and @folego
I am trying to replicate the same issue by using an account that does not have enough balance to do the transaction. But, I got the error:
> Error: Returned error: insufficient funds for gas * price + value
    at Object.ErrorResponse (/home/maltabba/repos/web3v1.x/packages/web3-core-helpers/lib/errors.js:21:10356)
    at /home/maltabba/repos/web3v1.x/packages/web3-core-requestmanager/lib/index.js:113:46
    at /home/maltabba/repos/web3v1.x/packages/web3-providers-http/lib/index.js:43:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  data: null
}

So, could you please share the exact configuration, that you are using for the account balance?

Thanks,

**Comment by verma-shu6ham** [comment] 2023-03-16 11:59
Hi @Muhammad-Altabba,

You got this error due to insufficient balance in your account but in my case, I want to throw an error in case the msg.sender not passing enough ETH to contract.

assume this line with the error given below: 
 require(extraFund() + msg.value >= _jobBudget, "Your total balance including msg.value is still not sufficient to post this job.  Total Balance should be more than "_jobBudget".");
 
 try to replace the line and see if will you get this new error.

**Comment by Muhammad-Altabba** [comment] 2023-03-16 14:22
Thanks @shubham-verma-neo ,
I think I got you now.
However, when I tried this. I got the `reason` as expected.

Here is the code snippet for JavaScript:
```js

  contractInstance
      .methods
      .reverts()
      .send({ from: accounts[0], gas: 100000 })
      .on('error', err => {
          console.error(err)
          done();
      });
``` 

And here is the SmartContract:
```solidity

contract Basic {
    function reverts() public {
        revert('REVERTED WITH REVERT');
    }
}
```

And here is the error object:

```json
Error: Transaction has been reverted by the EVM:
{
  "transactionHash": "0x17caeb08165be41d51a0a5accc1df5a55ac5665f21979ce6fe12ddad396df8b7",
  "transactionIndex": 0,
  "blockNumber": 28,
  "blockHash": "0x0af05a12f38c469e07552da0fb6107e386ba5c77a80814ac38caef103b8c9fa5",
  "from": "0x6e599da0bff7a6598ac1224e4985430bf16458a4",
  "to": "0xe994438545f35b8cfe3ad4bb23e87ee01980f643",
  "cumulativeGasUsed": 21367,
  "gasUsed": 21367,
  "contractAddress": null,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "effectiveGasPrice": 1000000000,
  "type": "0x0",
  "events": {}
}
    at Object.TransactionRevertInstructionError (/home/maltabba/repos/web3v1.x/packages/web3-core-helpers/lib/errors.js:21:13368)
    at /home/maltabba/repos/web3v1.x/packages/web3-core-method/lib/index.js:91:3 {
  reason: 'REVERTED WITH REVERT',
  signature: 'Error(String)',
  receipt: {
    transactionHash: '0x17caeb08165be41d51a0a5accc1df5a55ac5665f21979ce6fe12ddad396df8b7',
    transactionIndex: 0,
    blockNumber: 28,
    blockHash: '0x0af05a12f38c469e07552da0fb6107e386ba5c77a80814ac38caef103b8c9fa5',
    from: '0x6e599da0bff7a6598ac1224e4985430bf16458a4',
    to: '0xe994438545f35b8cfe3ad4bb23e87ee01980f643',
    cumulativeGasUsed: 21367,
    gasUsed: 21367,
    contractAddress: null,
    logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    status: false,
    effectiveGasPrice: 1000000000,
    type: '0x0',
    events: {}
  }
}
```

So, could you please confirm that you are using the latest stable version of web3 (version `1.8.2`)? And if you still face the issue with the latest version, could you please share the full but also the very minimal code that we can use to reproduce the issue you are facing? It will be great if you could share your code on some cloud IDE like https://codesandbox.io/ and have the solidity code deployed on a test net.

Thanks in advance,

**Comment by verma-shu6ham** [comment] 2023-03-17 05:05
Hi @Muhammad-Altabba, sorry but I am unable to get the reason after doing the same as you suggested. I am using Ganache CLI.

for reference, I am attaching a video link that, how I am doing maybe I am doing wrong something please let me know if I am doing wrong.

https://drive.google.com/file/d/1vDA-3EWnjGxLPDYS2oDI_cgWbsN0b2m4/view?usp=drivesdk

As you suggested to deploy the smart contract to testnet and code to IDE once I will do that I will let you know with details.

**Comment by Muhammad-Altabba** [comment] 2023-03-17 06:03
Many thanks @shubham-verma-neo ,
Could you also confirm that you are using `{ handleRevert: true } ` inside the contract options? and that you are using web3.js version `1.8.2`?
And will be great to see this once you do it on a test net with an online could IDE.
Thanks,

**Comment by verma-shu6ham** [comment] 2023-03-17 06:14
@Muhammad-Altabba 
{ handleRevert: true } & I am using web3.js version 1.8.2

I tried with the below code still no revert reason
```js
try {
            setBackdrop(true);
            _receipt = await contract.methods
                .registerJob(jobType, jobDes, web3.utils.toWei(jobBudget, "ether"))
                .send({
                    value: web3.utils.toWei(depositETH, "ether"),
                    from: accounts[0],
                    gas: 100000,
                    handleRevert: true
                })
                .on('error', err => {
                    console.log("inside-1 .on")
                    console.error(err)
                    console.log("inside-2 .on")
                });
            if (_receipt.status) {
                setReceipt(_receipt)
                setTx(true);
            }
        } catch (error) {
            console.log("error: ", error);
            console.log("_receipt: ", _receipt);
            console.log("error.message: ", error.message);
            setBackdrop(false);
        }
```

Error: 
index.js:1 Error: Transaction has been reverted by the EVM:
{
  "transactionHash": "0xe7801a7f2d874ad780d19d777cb0bd589b948ddd32b29d88959290413eec8319",
  "transactionIndex": 0,
  "blockNumber": 16,
  "blockHash": "0x9a707729129852b8133b01958ee07381d2893d8a4cd05d548598ece9b1e4952c",
  "from": "0x048415afed1eac39dbdfc5f39622a8283aa0e702",
  "to": "0xf4c2af8c75d803dd967d6083384b1eab6e33d3e5",
  "cumulativeGasUsed": 29085,
  "gasUsed": 29085,
  "contractAddress": null,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "effectiveGasPrice": 2641489336,
  "type": "0x2",
  "events": {}
}
    at Object.TransactionError (web3.min.js:2:1)
    at Object.TransactionRevertedWithoutReasonError (web3.min.js:2:1)
    at web3.min.js:2:1
    at h (web3.min.js:2:1)
    at Generator.<anonymous> (web3.min.js:2:1)
    at Generator.next (web3.min.js:2:1)
    at t (web3.min.js:2:1)
    at s (web3.min.js:2:1)
    at web3.min.js:2:1
    at new Promise (<anonymous>)
    at web3.min.js:2:1
    at web3.min.js:2:1

**Comment by verma-shu6ham** [comment] 2023-03-21 03:58
Hi @Muhammad-Altabba,

I have created a repo, the link is given below. 

https://github.com/shubham-verma-neo/ErrorReason

the contract is deployed on the Matic Mumbai test net - 0x30630b0dC38d6340f8663FCD0882E3545bC40A50

let me know if you need any other details.

**Comment by Muhammad-Altabba** [comment] 2023-03-22 00:07
Hello @shubham-verma-neo,
Thanks for sharing. This was really tricky to detect. And it turned out to be nothing to handle :smile: 
The short answer is: you just need to read the reason with `error.reason` (or err.reason depending on the chosen name for the error object). 

And here is what caused the confusion: The reason is there. But using console.log at the browser does not show the properties of the logged object. It shows only the toString of that object. And the toString of the error is just its `message`. However, the Error message was a stringified JSON (but for historical reasons this string was only for the receipt object and did not contain the `signature` or the error `reason`). And this caused us to see an object but without the reason. This issue was not present at the console.log at the Terminal because at the terminal, it prints all the object properties.

So, please confirm that you can access the `error.reason`. So we can close this issue.
And you can also see all the properties of that error object with `JSON.stringify(error, null, 2)`

Thanks,

**Comment by verma-shu6ham** [comment] 2023-03-24 04:43
Hi @Muhammad-Altabba, 

First of all, I will thank you to being with me on this issue. 

I have tried, but as you said need to access the `error.reason` (or `err.reason` depending on the chosen name for the error object).

But still, I am not able to get the reason.

**Changes in ReactJS**
```
const setRandomAddress = async () => {
    if (!accounts) {
      alert("Please Connect Wallet.");
      return;
    }
    if (_randomAddre === "") {
      alert("Please enter valid address.");
      return;
    }
    try {
      await sampleContract.methods.setRandomAddress(_randomAddre)
        .send({
          from: accounts[0],
          gas: 100000,
          handleRevert: true
        })
        .on('error', err => {
          console.error("err on ",err)
          console.log("err.reason on", err.reason);
        });
    }
    catch (err) {
      console.log("err ", err);
      console.log("err.reason ", err.reason);
      console.log("JSON.stringify ", JSON.stringify(err, null, 2));
    }
    set_RandomAddre("");
  }
  ```
**Output** 

```
err  Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0xea13fdfb655c0191adb38ac43b5b50e95e3fb85b424f09b9269836ff89f53628",
  "blockNumber": 33494899,
  "contractAddress": null,
  "cumulativeGasUsed": 339196,
  "effectiveGasPrice": 2500000015,
  "from": "0x69d9295a2980b612f78c9e69d1dd0fb5d1427408",
  "gasUsed": 24385,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000028000000000000000000000008000000000000000000000000000000000800000000000000000000100000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000400000000000000000000000000000200000000000000000080000000000000000000000000000000000000000004000000000000000000041000000000100000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000100000",
  "status": false,
  "to": "0x30630b0dc38d6340f8663fcd0882e3545bc40a50",
  "transactionHash": "0x7a8270367326b46ec6cfae3b9e4b613992383b8a86b48f9f45ff2b1f8cbcead2",
  "transactionIndex": 1,
  "type": "0x2",
  "events": {
    "0": {
      "address": "0x0000000000000000000000000000000000001010",
      "blockHash": "0xea13fdfb655c0191adb38ac43b5b50e95e3fb85b424f09b9269836ff89f53628",
      "blockNumber": 33494899,
      "logIndex": 3,
      "removed": false,
      "transactionHash": "0x7a8270367326b46ec6cfae3b9e4b613992383b8a86b48f9f45ff2b1f8cbcead2",
      "transactionIndex": 1,
      "id": "log_0071979d",
      "returnValues": {},
      "signature": null,
      "raw": {
        "data": "0x00000000000000000000000000000000000000000000000000003771f0283900000000000000000000000000000000000000000000000000058c6f8ba59dd81100000000000000000000000000000000000000000000046e86a5291b0645aec4000000000000000000000000000000000000000000000000058c3819b5759f1100000000000000000000000000000000000000000000046e86a5608cf66de7c4",
        "topics": [
          "0x4dfe1bbbcf077ddc3e01291eea2d5c70c2b422b415d95645b9adcfd678cb1d63",
          "0x0000000000000000000000000000000000000000000000000000000000001010",
          "0x00000000000000000000000069d9295a2980b612f78c9e69d1dd0fb5d1427408",
          "0x0000000000000000000000003a22c8bc68e98b0faf40f349dd2b2890fae01484"
        ]
      }
    }
  }
}
    at Object.TransactionError (web3.min.js:28468:1)
    at Object.TransactionRevertedWithoutReasonError (web3.min.js:28478:1)
    at web3.min.js:28941:1
    at h (web3.min.js:33280:1)
    at Generator.<anonymous> (web3.min.js:33364:1)
    at Generator.next (web3.min.js:33305:1)
    at t (web3.min.js:33032:1)
    at s (web3.min.js:33046:1)
    at web3.min.js:33051:1
    at new Promise (<anonymous>)
    at web3.min.js:33043:1
    at web3.min.js:28956:1
```

```
err.reason  undefined
```

```
JSON.stringify  {
  "receipt": {
    "blockHash": "0xea13fdfb655c0191adb38ac43b5b50e95e3fb85b424f09b9269836ff89f53628",
    "blockNumber": 33494899,
    "contractAddress": null,
    "cumulativeGasUsed": 339196,
    "effectiveGasPrice": 2500000015,
    "from": "0x69d9295a2980b612f78c9e69d1dd0fb5d1427408",
    "gasUsed": 24385,
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000028000000000000000000000008000000000000000000000000000000000800000000000000000000100000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000400000000000000000000000000000200000000000000000080000000000000000000000000000000000000000004000000000000000000041000000000100000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000100000",
    "status": false,
    "to": "0x30630b0dc38d6340f8663fcd0882e3545bc40a50",
    "transactionHash": "0x7a8270367326b46ec6cfae3b9e4b613992383b8a86b48f9f45ff2b1f8cbcead2",
    "transactionIndex": 1,
    "type": "0x2",
    "events": {
      "0": {
        "address": "0x0000000000000000000000000000000000001010",
        "blockHash": "0xea13fdfb655c0191adb38ac43b5b50e95e3fb85b424f09b9269836ff89f53628",
        "blockNumber": 33494899,
        "logIndex": 3,
        "removed": false,
        "transactionHash": "0x7a8270367326b46ec6cfae3b9e4b613992383b8a86b48f9f45ff2b1f8cbcead2",
        "transactionIndex": 1,
        "id": "log_0071979d",
        "returnValues": {},
        "signature": null,
        "raw": {
          "data": "0x00000000000000000000000000000000000000000000000000003771f0283900000000000000000000000000000000000000000000000000058c6f8ba59dd81100000000000000000000000000000000000000000000046e86a5291b0645aec4000000000000000000000000000000000000000000000000058c3819b5759f1100000000000000000000000000000000000000000000046e86a5608cf66de7c4",
          "topics": [
            "0x4dfe1bbbcf077ddc3e01291eea2d5c70c2b422b415d95645b9adcfd678cb1d63",
            "0x0000000000000000000000000000000000000000000000000000000000001010",
            "0x00000000000000000000000069d9295a2980b612f78c9e69d1dd0fb5d1427408",
            "0x0000000000000000000000003a22c8bc68e98b0faf40f349dd2b2890fae01484"
          ]
        }
      }
    }
  }
}
```
```
err on Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0xea13fdfb655c0191adb38ac43b5b50e95e3fb85b424f09b9269836ff89f53628",
  "blockNumber": 33494899,
  "contractAddress": null,
  "cumulativeGasUsed": 339196,
  "effectiveGasPrice": 2500000015,
  "from": "0x69d9295a2980b612f78c9e69d1dd0fb5d1427408",
  "gasUsed": 24385,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000028000000000000000000000008000000000000000000000000000000000800000000000000000000100000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000400000000000000000000000000000200000000000000000080000000000000000000000000000000000000000004000000000000000000041000000000100000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000100000",
  "status": false,
  "to": "0x30630b0dc38d6340f8663fcd0882e3545bc40a50",
  "transactionHash": "0x7a8270367326b46ec6cfae3b9e4b613992383b8a86b48f9f45ff2b1f8cbcead2",
  "transactionIndex": 1,
  "type": "0x2",
  "events": {
    "0": {
      "address": "0x0000000000000000000000000000000000001010",
      "blockHash": "0xea13fdfb655c0191adb38ac43b5b50e95e3fb85b424f09b9269836ff89f53628",
      "blockNumber": 33494899,
      "logIndex": 3,
      "removed": false,
      "transactionHash": "0x7a8270367326b46ec6cfae3b9e4b613992383b8a86b48f9f45ff2b1f8cbcead2",
      "transactionIndex": 1,
      "id": "log_0071979d",
      "returnValues": {},
      "signature": null,
      "raw": {
        "data": "0x00000000000000000000000000000000000000000000000000003771f0283900000000000000000000000000000000000000000000000000058c6f8ba59dd81100000000000000000000000000000000000000000000046e86a5291b0645aec4000000000000000000000000000000000000000000000000058c3819b5759f1100000000000000000000000000000000000000000000046e86a5608cf66de7c4",
        "topics": [
          "0x4dfe1bbbcf077ddc3e01291eea2d5c70c2b422b415d95645b9adcfd678cb1d63",
          "0x0000000000000000000000000000000000000000000000000000000000001010",
          "0x00000000000000000000000069d9295a2980b612f78c9e69d1dd0fb5d1427408",
          "0x0000000000000000000000003a22c8bc68e98b0faf40f349dd2b2890fae01484"
        ]
      }
    }
  }
}
    at Object.TransactionError (web3.min.js:28468:1)
    at Object.TransactionRevertedWithoutReasonError (web3.min.js:28478:1)
    at web3.min.js:28941:1
    at h (web3.min.js:33280:1)
    at Generator.<anonymous> (web3.min.js:33364:1)
    at Generator.next (web3.min.js:33305:1)
    at t (web3.min.js:33032:1)
    at s (web3.min.js:33046:1)
    at web3.min.js:33051:1
    at new Promise (<anonymous>)
    at web3.min.js:33043:1
    at web3.min.js:28956:1
```
```
err.reason on undefined
```

**Comment by Muhammad-Altabba** [comment] 2023-03-24 06:58
Thanks @shubham-verma-neo for sharing,
This is interesting. Could you please share the output when you stringify the error object with `JSON.stringify(error, null, 2)`? 
Thanks,

**Comment by verma-shu6ham** [comment] 2023-03-24 07:08
Hi @Muhammad-Altabba ,

output of err, err.reason, JSON.stringify(error, null, 2) already shared above.

here the output of **JSON.stringify(error, null, 2)**

```
JSON.stringify  {
  "receipt": {
    "blockHash": "0xea13fdfb655c0191adb38ac43b5b50e95e3fb85b424f09b9269836ff89f53628",
    "blockNumber": 33494899,
    "contractAddress": null,
    "cumulativeGasUsed": 339196,
    "effectiveGasPrice": 2500000015,
    "from": "0x69d9295a2980b612f78c9e69d1dd0fb5d1427408",
    "gasUsed": 24385,
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000028000000000000000000000008000000000000000000000000000000000800000000000000000000100000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000400000000000000000000000000000200000000000000000080000000000000000000000000000000000000000004000000000000000000041000000000100000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000100000",
    "status": false,
    "to": "0x30630b0dc38d6340f8663fcd0882e3545bc40a50",
    "transactionHash": "0x7a8270367326b46ec6cfae3b9e4b613992383b8a86b48f9f45ff2b1f8cbcead2",
    "transactionIndex": 1,
    "type": "0x2",
    "events": {
      "0": {
        "address": "0x0000000000000000000000000000000000001010",
        "blockHash": "0xea13fdfb655c0191adb38ac43b5b50e95e3fb85b424f09b9269836ff89f53628",
        "blockNumber": 33494899,
        "logIndex": 3,
        "removed": false,
        "transactionHash": "0x7a8270367326b46ec6cfae3b9e4b613992383b8a86b48f9f45ff2b1f8cbcead2",
        "transactionIndex": 1,
        "id": "log_0071979d",
        "returnValues": {},
        "signature": null,
        "raw": {
          "data": "0x00000000000000000000000000000000000000000000000000003771f0283900000000000000000000000000000000000000000000000000058c6f8ba59dd81100000000000000000000000000000000000000000000046e86a5291b0645aec4000000000000000000000000000000000000000000000000058c3819b5759f1100000000000000000000000000000000000000000000046e86a5608cf66de7c4",
          "topics": [
            "0x4dfe1bbbcf077ddc3e01291eea2d5c70c2b422b415d95645b9adcfd678cb1d63",
            "0x0000000000000000000000000000000000000000000000000000000000001010",
            "0x00000000000000000000000069d9295a2980b612f78c9e69d1dd0fb5d1427408",
            "0x0000000000000000000000003a22c8bc68e98b0faf40f349dd2b2890fae01484"
          ]
        }
      }
    }
  }
}
```

**Comment by Muhammad-Altabba** [comment] 2023-03-31 06:13
Hello @shubham-verma-neo 
Sorry I did not see that you already provided the `JSON.stringify(error, null, 2)`. I was on a vacation at that time and I was opening it from my mobile so I did not notice it. But I wanted all the data to be able to work on it once available.

However, the issue is that you are passing handleRevert at the wrong place. (in addition to the earlier discussed point with console.log on the browser). Actually, according to the [documentation](https://web3js.readthedocs.io/en/v1.2.5/web3-eth.html#handlerevert), you need to set it at web3.eth and not as configuration to the send function. Maybe the documentation is not that clear but as mentioned it is `web3.eth.handleRevert`. And so you set it with `web3.eth.handleRevert = true` and once you set it it will work with send and other mentioned methods.

I hope this resolves your issue and I wish you a happy coding :smile:

**Comment by verma-shu6ham** [comment] 2023-04-07 06:32
Hi @Muhammad-Altabba ,

sorry to disturb you on your vacation.

I have tried the way you suggest in the above comment. I have set ```web.eth.handleRevert = true``` but something strange happens for reference I recorded the video please have a look. I have also pushed the latest code and changes that I made to the code. 

git rep:- https://github.com/shubham-verma-neo/ErrorReason

video link:- https://drive.google.com/file/d/1xMngAeg7rvboeHMmxKaWK9HmsRYKHkrq/view?usp=sharing

**Comment by Muhammad-Altabba** [comment] 2023-04-10 03:18
You are always welcome @shubham-verma-neo ,
And many thanks for sharing.

The good news is that the current issue could be closed as setting handleRevert is doing its job.
But still, in the end, it is not working for you. Because, the current version of the Infura provider, seems to be updated to put the error inside `data.data`. And here is how the internal object looks like with Infura:
![image](https://user-images.githubusercontent.com/24407834/230818491-545546b5-e62f-4b32-9c88-55f3711eac65.png)
 

And so we need to update web3.js to handle this. And here is the line that needs to be changed:
https://github.com/web3/web3.js/blob/2948927a18a2424621743294a80ea3ee5bf0e1e9/packages/web3-core-method/src/index.js#L629
And it could be changed to something like:
```ts
                    reasonData = (err.data.data || err.data).substring(10);
```
However, I created [an independent issue](https://github.com/web3/web3.js/issues/5999) for this for easier tracking. And I will discuss it with the team. And I expect it to be fixed in the next batch release of web3.js version 1.x.

Many thanks again for your great help and effort in detecting this issue.

**Closed as completed by Muhammad-Altabba** 2023-04-10 03:18 UTC
Labels: 1.x
