### ISSUE TITLE
Returned error: Unknown Account

### ISSUE THREAD

**Issue by vuphuc2301** [ethereum/web3.js#4665] opened 2022-01-02 17:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm receiving the error "Returned error: Unknown Account" when trying to send approve request from my website on phone to metamask app using walletconnect

### Expected Behavior

Metamask Popup and ask for confirmation

### Steps to Reproduce

```ts

import Web3 from "web3";

const web3 = new Web3('https://bsc-dataseed1.binance.org:443');

const ABI = [
    {
        constant: false,
        inputs: [{ name: "_spender", type: "address" }, { name: "_value", type: "uint256" }],
        name: "approve",
        outputs: [{ "name": "", "type": "bool" }],
        payable: false, stateMutability: "nonpayable", type: "function"
    }
];

async function getApprovePermission() {
    const myContract = new web3.eth.Contract(ABI, '0xB8c77482e45F1F44dE1745F52C74426C631bDD52');
    const result = await myContract.methods.approve('contract address....', 100).send({
        from: '0x.....123'
    });

    return result
}

```

### Web3.js Version

1.6.1

### Environment

- Operating System: IOS
- Browser: Safari
- Node.js Version: 16.5.0
- NPM Version: 7.19.1

**Comment by kingsley-einstein** [comment] 2022-01-04 22:09
Facing same issue

**Comment by nazarhussain** [comment] 2022-01-06 16:28
@vuhoangp Thanks for reaching to us. The error message with the prefix `Returned error` clearly means this is not an error generated  by our library. Rather the error was returned from the provider node you are connected to as an error response. 

I would suggest you to verify and debug once again within your code, there seems to an invalid account address used. You can also try to connect to some other provider to verify. 

If you can't figure out, then try to create a code which we can execute to reproduce the error. Because in general testing we may use different account addresses and your error may be related to those particular accounts.

**Comment by jdiegosierra** [comment] 2022-01-10 01:43
You have to use Metamask provider instead of node URL `const web3 = new Web3(window.ethereum);`

**Comment by zetorange1** [comment] 2022-01-19 03:56
You need to run this before making `myContract` variable.
`web3.eth.setProvider(Web3.givenProvider);`

**Comment by nazarhussain** [comment] 2022-01-21 10:37
@vuhoangp Hope the above comments would solved the problem. 

As earlier explained in my comment, the error message mentions that the error is returned from the provider not the library. 

I am closing the issue now, if you find any relevant information suggesting this issue relates to library, please re-open the issue.

**Closed as completed** 2022-01-21 10:37 UTC
Labels: Bug, 1.x

**Comment by GeniusGeeek** [comment] 2022-02-13 09:27
> You have to use Metamask provider instead of node URL `const web3 = new Web3(window.ethereum);`


How do you use metamask provider on mobile browser when metamask extension isn't available on mobile? it will be undefined or null

**Comment by elmaedesistemas** [comment] 2022-03-20 06:14
someone fix it?

**Comment by mengfanze512** [comment] 2022-04-19 11:15
someone fix it?

**Comment by JayKCDev** [comment] 2022-10-31 09:18
@vuphuc2301 I see you're nowhere signing the transaction (at least not visible in the shared code snippet) for every transaction you make you need to first generate a txHash. Without the transaction hash the indexing node will reject your transaction since every txHash mutatates the state if blockchain as a whole.

> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Current Behavior
> I'm receiving the error "Returned error: Unknown Account" when trying to send approve request from my website on phone to metamask app using walletconnect
> 
> ### Expected Behavior
> Metamask Popup and ask for confirmation
> 
> ### Steps to Reproduce
> ```ts
> import Web3 from "web3";
> 
> const web3 = new Web3('https://bsc-dataseed1.binance.org:443');
> 
> const ABI = [
>     {
>         constant: false,
>         inputs: [{ name: "_spender", type: "address" }, { name: "_value", type: "uint256" }],
>         name: "approve",
>         outputs: [{ "name": "", "type": "bool" }],
>         payable: false, stateMutability: "nonpayable", type: "function"
>     }
> ];
> 
> async function getApprovePermission() {
>     const myContract = new web3.eth.Contract(ABI, '0xB8c77482e45F1F44dE1745F52C74426C631bDD52');
>     const result = await myContract.methods.approve('contract address....', 100).send({
>         from: '0x.....123'
>     });
> 
>     return result
> }
> ```
> 
> ### Web3.js Version
> 1.6.1
> 
> ### Environment
> * Operating System: IOS
> * Browser: Safari
> * Node.js Version: 16.5.0
> * NPM Version: 7.19.1
> 
> ### Anything Else?
> _No response_
