### ISSUE TITLE
getTransactionCount() returns incorrect nonce when transactions are pending

### ISSUE THREAD

**Issue by abrinckm** [ethereum/web3.js#1741] opened 2018-06-28 18:43 UTC
The situation I have is this:
* The correct nonce of (208) is reported by https://rinkeby.etherscan.io/.
* An incorrect nonce of (206) is returned from web3.eth.getTransactionCount()
* I have 2 pending transactions on rinkeby.

so I assume the difference of 2 comes from my 2 pending transactions?

I've only tested this on rinkeby. 

To reproduce the error you'll need to submit a transaction that sits too long with a `pending` status.

I'm fortunate/unfortunate enough to be able to reproduce this consistently when trying to deploy a contract on rinkeby. (at the time of this writing, my contract deployments are taking up to two days to confirm regardless of gwei).

If you want to try and reproduce, here is my rough code and hopefully your transactions pend awhile ;)

```
// I've already compiled using solc and have the abi and bytecode 

let contract = new web3.eth.Contract(abi);

let txn = contract.deploy({data: '0x'+bytecode}); 

let txn_object = {
  gas: 270000,
  gasPrice: '55', 
  from: from, 
  data: txn.encodeABI()
};

web3.eth.getTransactionCount(from)
  .then(nonce => {
    txn_object.nonce = nonce;

    let raw_txn = new require('ethereum-tx')(txn_object);
    raw_txn.sign(private_key);
    let serialized = raw_txn.serialize();
    let signed_txn = '0x'+serialized.toString('hex');

    web3.eth.sendSignedTransaction(signed_txn).on('receipt', (result) => console.log(result));
  })
```

running this the second time results in `transaction already known` error because getTransactionCount() is returning previous nonce.

I know that I could reproduce using txn.send({from:from}) instead of going through the trouble of manually signing the txn, but I wanted to report exactly what I'm doing.

**Comment by dostu** [comment] 2018-07-12 15:25
I believe you can call `web3.eth.getTransactionCount(address, 'pending')` to include pending transactions.

**Comment by abrinckm** [comment] 2018-09-07 14:59
@dostu Unfortunately no. That is another issue that remains open. You can read [here](https://github.com/ethereum/go-ethereum/issues/2880)

**Comment by Bat-Orshikh** [comment] 2018-11-13 08:19
@abrinckm Same probleem here. I want to know how many number transaction is pending that created by me. Do you have a any solution for that?

**Comment by abrinckm** [comment] 2018-11-19 17:12
@Bat-Orshikh If you enable the Txpool API by running geth with flags `--rpcapi txpool`

Then you can open the geth console (e.g., `geth attach http://localhost:8545`) and enter `txpool.content`

you should see details on a number of pending or queued transactions. I haven't figured out how to revert transactions at the moment. Although there is a "not a great" solution here: https://ethereum.stackexchange.com/questions/1774/geth-how-to-clear-queued-transactions

**Comment by Bat-Orshikh** [comment] 2018-11-20 09:18
@abrinckm thanks for the reply.
I'm using infura. And I can't get the pending transaction number.
So I just handled my nonce problem.

**Comment by Ledslash** [comment] 2018-12-05 15:22
When can we expect to be fixed? it's actually costing an important amount of effort just to handle the nonce issue.

**Comment by adambordas** [comment] 2019-01-22 16:11
Is this still an issue? As @abrinckm mentioned, [this issue](https://github.com/ethereum/go-ethereum/issues/2880) is related, but it's solved now. So if the node you use updated to the latest version of go-ethereum, than this issue is solved as well. Please correct me if I'm wrong.

**Comment by nivida** [comment] 2019-01-25 11:01
@stukker01 Thanks for figuring this out! I'm closing this issue now and if someone still has this issue then please feel free to drop a comment here and tag me.

**Closed by nivida** 2019-01-25 11:01 UTC
Labels: bug

**Comment by lucashenning** [comment] 2019-06-26 15:57
Any update on this? This is still an issue on Quorum `v2.2.4` using web3 `1.0.0-beta.55`. 

We're retrieving the nonce like this: `eth.getTransactionCount(this.account.address, 'pending');`. However, if we send a lot of transactions at the same time, some of them fail:
```
Transaction has been reverted by the EVM:
{
  "blockHash": "0x004092e938498bbdc9ce609a854ab588a39cc69da54201b572f61873157684e2",
  "blockNumber": 1769,
  "contractAddress": null,
  "cumulativeGasUsed": 29919,
  "from": "0xeddf42a34b24d37bc6f4b8aac1d11eb8a72f99ae",
  "gasUsed": 29919,
  "logs": [],
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0x353b7ffc2eaa9ca5d5a55b377956d201ef100645",
  "transactionHash": "0x05d2611ce819bbeb3de934a0f9537c32dc78eb6559532725a39e6938930c77b8",
  "transactionIndex": 0
}
```

This does not happen if we manually increment the nonce for each transaction.

**Comment by tsujp** [comment] 2019-12-15 06:07
This is still an issue. I've been able to reproduce the issue as @lucashenning described, but also it can happen when done slowly too. Such as between the time it takes to broadcast the transaction (I assume) and when a new transaction is being constructed. A workaround could be to have N addresses and only use an address if the last TX it constructed has been recognised by the network, or add iteration logic for the nonce yourself – I think web3 should be smart enough to track that a transaction is valid and has been attempted to be broadcast and should internally update it's nonce on the client-side.

This is mostly speculation here, but this issue is definitely NOT gone and is extremely frustrating since the result is your transaction just doesn't get broadcast or is rejected for having the same nonce.

**Comment by sssubik** [comment] 2020-05-19 05:17
@tsujp @nivida Hey Is the issue over? What is the solution for having correct nonce while sending a transaction.?

**Comment by tsujp** [comment] 2020-05-19 11:41
> @tsujp @nivida Hey Is the issue over? What is the solution for having correct nonce while sending a transaction.?

I don't use Web3 anymore I use Ethers.js now and I also defer that stuff to Metamask as Ethers.js has some edge patch to fix this too which I haven't used yet. Concerning Web3, I believe it has some edge version, likely `2.0.0-alpha.1` or whatever the tag is called which has this fixed, sorry I cannot give you anymore at this time.

**Comment by ayushgupta0610** [comment] 2020-12-09 12:08
> @abrinckm thanks for the reply.
> I'm using infura. And I can't get the pending transaction number.
> So I just handled my nonce problem.

Could you throw some light on this, @Bat-Orshikh! How exactly did you solve the nonce issue?

**Comment by barkntuncer** [comment] 2021-10-18 21:07
Still the same issue

**Comment by ekkis** [comment] 2022-03-29 17:02
it's 4 years later and we still have this issue
