### ISSUE TITLE
web3.accounts.create() generating wrong public key

### ISSUE THREAD

**Issue by agilani** [ethereum/web3.js#1267] opened 2017-12-31 22:45 UTC
Which Web3.js version?: 1.0.0-beta.27
Which operating system?: Windows / Chrome
How installed?: NPM
Using it with Angular-CLI project

# actual behavior
An account generated by web3.accounts.create() is creating an account with public/private key. Which is desired behavior, But when i try to access the account using the private key on myetherwallet.com, it displayes a different public key than the one given by web3.

# expected behavior
The public key should be same.

# steps to reproduce
initialize web3 and create a new account. I created 10 accounts and 8 out of them had the issue.

**Comment by DanielMReed** [comment] 2018-02-08 13:13
A minimum working example so I can be reproduced would help, is MEW giving you the public key or the address?

**Comment by phoax** [comment] 2018-02-14 00:49
Same problem, I try to get a public key from a private key, and
`web3.eth.accounts.privateKeyToAccount('c7864d1ad07dd6ee3e1ec554e36bfe50cb95fe660bd873fd96dfe32f8908a6d0');`
generates 
`address: "0x69E36154eba1D933aa1820195a54a5068622902f"`
It should be `0x48d48309670e7E64CD277778DE02689F5268081d`

**Comment by phoax** [comment] 2018-02-14 00:52
I have a similar problem, I try to get a public key from a private key, and
`web3.eth.accounts.privateKeyToAccount('c7864d1ad07dd6ee3e1ec554e36bfe50cb95fe660bd873fd96dfe32f8908a6d0');`
generates 
`address: "0x69E36154eba1D933aa1820195a54a5068622902f"`
It should be `0x48d48309670e7E64CD277778DE02689F5268081d`

**Comment by kevinwucodes** [comment] 2018-02-17 18:09
@phoax the private key should always be prefixed with `0x` because it is expecting a hexadecimal string

**Comment by ARitz-Cracker** [comment] 2018-06-10 20:34
Lots of confusion could be solved by allowing a buffer to be passed as well, not just a string that'll have its first 2 bytes stripped cuz it's expecting a "0x" prefix.

**Comment by samjam48** [comment] 2018-07-02 10:19
I had the same error with an incorrect account address being generated from passing in a privateKey variable using:
`web3.eth.accounts.privateKeyToAccount(privateKey)`

Simply fixed by using:
`web3.eth.accounts.privateKeyToAccount("0x"` + privateKey)`

Thanks @kevinwucodes


Of course I upgrade my web3 and went in day's worth of debugging different errors to arrive back at this problem and before actually finding this solution....

**Comment by tcrowe** [comment] 2018-12-15 23:52
@agilani @phoax Will this suffice to inform others of the right argument? https://github.com/ethereum/web3.js/pull/2129

**Closed** 2019-10-13 08:15 UTC
Labels: 1.x, documentation
