### ISSUE TITLE
React native url == null (WebsocketProvider)

### ISSUE THREAD

**Issue by helllynx** [ethereum/web3.js#2864] opened 2019-06-02 19:18 UTC
### Description 

Hi) While writing an application on  RN, there were problems with catching exceptions during internet connection loss. If I have already call `new Web3.providers.WebsocketProvider(urlConfig);` then when the connection is lost, the application crashes without causing try/catch.

#### Expected behavior

Calling `new Web3.providers.WebsocketProvider(urlConfig);` when connection lost must throw some exception.

#### Actual behavior

Just crash without logs in logger, but with screen logs.

#### Error Logs 

![rn_web3](https://user-images.githubusercontent.com/14349081/58766169-1c63f180-8584-11e9-86ea-c26de54929a9.jpg)

### Versions 
    web3: 1.0.0-beta.55
    react-native: 0.59.4

Thank you!

**Comment by nivida** [comment] 2019-06-03 03:10
Could you create a GitHub repository with an example project where this error happens? Otherwise, it will be hard to reproduce this issue 1:1.

**Comment by helllynx** [comment] 2019-06-03 08:25
@nivida here [repo](https://github.com/helllynx/eth_wallet). I took the main project and delete unnecessary parts, I apologize for the unnecessary dependences =( 

**For reproduce:**

Run app, then push button, in logs you seee some events. The easiest way to reproduce is to connect the phone by USB, running the build and then turn off  Wi-Fi or cellular network. You need wait some timeout, about 10 sec.

**Comment by sirpy** [comment] 2020-01-07 21:43
bug in react native
see PR for fix
https://github.com/facebook/react-native/pull/27702

**Comment by nivida** [comment] 2020-01-09 13:26
@sirpy Thanks for proposing this PR in the ``react-native`` repository. I will close this issue now but feel free to ping me here again if the issue is still existing after the PR got merged and released.

**Closed as completed by nivida** 2020-01-09 13:26 UTC
Labels: Needs Clarification, 2.x
