### ISSUE TITLE
Typescript compilation (tsc) fails when web3 is a dependency

### ISSUE THREAD

**Issue by pasiphae00** [ethereum/web3.js#3154] opened 2019-10-24 00:30 UTC
### Description 

Suddenly today after updating npm dependencies, some of our TypeScript packages that depend on `web3` started failing to build due to a Type import/export error.

Seems to have shown up in the last 24 hours, coinciding with `1.2.2`.

#### Expected behavior

The packages should build.

#### Actual behavior

`tsc` fails due to the following error (below).

#### Steps to reproduce the behavior
Code in question is proprietary, so I cannot share the repo unfortunately.

All i can say is have a typescript file that depends on `web3@1.2.2` and try to build it with `tsc`.

The offending types are not even imported directly, and there is no trace from `tsc` so I cannot provide any more context than what is pasted below.

#### Error Logs 
```
./../node_modules/web3-eth/types/index.d.ts(38,10): error TS2305: Module '"web3-eth-abi"' has no exported member 'AbiCoder'.
```

### Versions 
* web3.js: `1.2.2`
* nodejs: `lts` (12.17)
* browser: n/a
* ethereum node: n/a

**Comment by cgewecke** [comment] 2019-10-24 01:12
@hrharder Thanks for reporting. Are you able to work-around this temporarily by setting tsconfig.json like this?
```javascript
{
    "compilerOptions": {
        "skipLibCheck": true
    }
}
```
---------------
> have a typescript file that depends on web3 and try to build it with tsc.

This should be added to the E2E here, e.g just a small outer-level smoke-test (maybe via the npm registry proxy). Each package has types tests and AbiCoder is covered at web3-eth-abi.

**Comment by pasiphae00** [comment] 2019-10-24 01:15
This works! Thank you. Feel free to close the issue if needed.

**Comment by cgewecke** [comment] 2019-10-24 01:16
@hrharder Oh, if it's ok will leave this open until tsc works as expected :)

**Comment by pasiphae00** [comment] 2019-10-24 01:17
@cgewecke seems logical :) Thanks!

**Comment by joshstevens19** [comment] 2019-10-28 17:30
i see this being a issue for a few people will get a fix out tomorrow time when i get a second which should resolve this for people. Will link the PR once done.

**Comment by joshstevens19** [comment] 2019-10-28 17:33
@hrharder can you paste me your code which is erroring on tsc and your tsconfig so i can make it break. Did a plain import of web3 and some eth stuff and it built fine. Be great if you got me your example so i can test against it.

**Comment by pasiphae00** [comment] 2019-10-28 17:40
@joshstevens19 thanks for tackling this!

[I'll attach a gist with one](https://gist.github.com/hrharder/4adb16cdca9dbf3b6c771d75046a0ca8) of the files (I assume) was causing the problem, including TypeScript config and the package file. Unfortunately, the codebase in question is quite large and proprietary, and the trace from `tsc` (in the initial issue) doesn't link to a line in our code, it shows up as a libCheck (disabled by setting `skipLibCheck` as @cgewecke suggested).

Let me know if I can provide any more info. It's possible this is lower level than I expected, as in not an issue with Web3, but rather an intermediary dependency (such as one of the 0x libraries) that has a version conflict.

**Comment by pasiphae00** [comment] 2019-10-28 17:42
@joshstevens19  -- for more context. The `index.ts` file linked is the router initializer for a specific endpoint within a larger express-based web service. I can't link too much of the business logic due to the proprietary nature, but can link more structural code if necessary.

**Comment by joshstevens19** [comment] 2019-10-28 17:54
the issue is not anything in web3 its your `typeRoots` in the tsconfig.  If you for example remove the `typesRoots` it builds fine.

`If typeRoots is specified, only packages under typeRoots will be included.` -  stated in ts docs https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types 

hence why its complaining as you're excluded web3 types from your ts project. If you remove it from the config it works fine.

![image](https://user-images.githubusercontent.com/18472422/67703828-fbc18b80-f9ab-11e9-90fd-c84fa53361e0.png)

If you want to keep this you can change your tsconfig to:

```
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "outDir": "dist",
    "rootDir": "src",
    "sourceMap": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "typeRoots": [
      "../../node_modules/@types",
      "../../node_modules/@0x/typescript-typings/types",
      "node_modules/@types",
      "node_modules/@0x/typescript-typings/types"
    ],
    "types": ["web3"]
  },
  "include": ["src/"],
  "exclude": ["node_modules"]
}
```

everything will build fine. 

as this is a config setup not a web3 issue will close hope this helps. :+1:

we can carry on the talk on this closed issue if you want to discuss any more config happy to help.

**Closed as completed by joshstevens19** 2019-10-28 17:54 UTC
Labels: Types, 1.x

**Comment by joshstevens19** [comment] 2019-10-28 18:06
edited what i said a minute ago FYI @hrharder

**Comment by pasiphae00** [comment] 2019-10-28 18:07
Great -- thanks for pointing that out @joshstevens19, my apologies for not realizing that.

I (wrongly) assumed it was a version issue, since we hadn't made any config changes, but after bumping a version our builds started failing.

Thanks again, i'll test this out. It does seem like `skipLibCheck` does the trick, but the way you suggest would be better since we can use the correct types and (hopefully) get rid of a few `as any` blocks.

**Comment by joshstevens19** [comment] 2019-10-28 18:08
@hrharder no worries yes i would avoid `skipLibCheck` if i was you as it decreases the typings of your application so the way above would be how i suggest you go forward. Cheers

**Comment by pasiphae00** [comment] 2019-10-28 18:15
Awesome. Will do -- appreciate it.
