### ISSUE TITLE
issue with websocket connection to infura

### ISSUE THREAD

**Issue by cmaliwal** [ethereum/web3.js#1646] opened 2018-05-21 18:29 UTC
I use websocket (ws) coneection to Infura node 

`web3 = new Web3(new Web3.providers.WebsocketProvider("wss://ropsten.infura.io/ws"));`

sometimes it's works fine or sometimes it give error on console : 

`Error: CONNECTION ERROR: Couldn't connect to node on WS.`

`Uncaught (in promise) Error: CONNECTION ERROR: Couldn't connect to node on WS.`

I am not getting why its happening.

**Comment by nivida** [comment] 2018-08-10 06:22
Can you determine when exactly this is happening? It's a bit hard to reproduce it this way.

**Comment by minhtruong92** [comment] 2018-09-10 14:45
I got the same issue, my code works with provider: "wss://ropsten.infura.io/ws" (testnet), but it doesn't work with "wss://mainnet.infura.io/ws". 
I use the code in introduction page https://infura.io/docs/wss/introduction

**Comment by ryokomy** [comment] 2018-09-27 07:54
I also had the same issue with "wss://rinkeby.infura.io/ws".

**Comment by sanaterrae** [comment] 2018-10-13 21:47
added some other details for same issue found here at https://github.com/INFURA/infura/issues/140

**Comment by pasiphae00** [comment] 2018-10-18 20:19
I'm having the same issue (using Kovan WS endpoint). It's extremely sporatic... About 25% of the time it works fine, and the other 75% it throws the `CONNECTION ERROR`.

I'll run my program once and it will fail, and then again with no changes and it will fail. 

Hard to see if this is an issue with Infura, or somewhere lower in the stack like the WS driver.

**Comment by jamesmorgan** [comment] 2019-01-25 10:40
I also get this almost exclusive failing with the latest version of web3 `1.0.37` - originally I thought it was an issue with Infura but then found this issue, any ideas on the solution - this is the ticket I raised with Infura https://community.infura.io/t/ropsten-connection-error-couldnt-connect-to-node-on-ws/272/5

**Comment by jamesmorgan** [comment] 2019-01-25 10:43
I have also found that adding this config fixed it - taken direct from https://github.com/ethereum/web3.js/issues/1217
```
{
  clientConfig: {
    maxReceivedFrameSize: 100000000,
    maxReceivedMessageSize: 100000000,
  }
}
```

**Comment by nivida** [comment] 2019-01-25 10:47
@jamesmorgan I've refactored the web3 providers and especially the WebsocketProvider (PR #2000). I will release this PR within the next days and probably this issue got fixed with it. I can't see anything that Web3.js is doing which could have an impact on establishing a connection.

**Comment by holgerd77** [comment] 2020-02-14 15:44
No further issue mentions for over a year, will close for now. Feel free to reopen.

**Closed by holgerd77** 2020-02-14 15:44 UTC
Labels: 1.x, enhancement

**Comment by Wyctus** [comment] 2020-12-14 21:35
This error started to happen to me regularly for a couple of weeks now. I can't tell the reason, seems to be totally random. Maybe it's a problem with Infura, since the error pops up on two different machines at the same time (they are running the same code).

```
Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.ConnectionError (/home/wyctus/p1/node_modules/web3-core-helpers/lib/errors.js:66:23)
    at Object.InvalidConnection (/home/wyctus/p1/node_modules/web3-core-helpers/lib/errors.js:36:21)
    at /home/wyctus/p1/node_modules/web3-providers-ws/lib/index.js:161:37
    at Map.forEach (<anonymous>)
    at WebsocketProvider._onClose (/home/wyctus/p1/node_modules/web3-providers-ws/lib/index.js:160:28)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/wyctus/p1/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onClose (/home/wyctus/p1/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/home/wyctus/p1/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (node:events:329:20)
    at WebSocketConnection.handleSocketClose (/home/wyctus/p1/node_modules/websocket/lib/WebSocketConnection.js:389:14)
    at TLSSocket.emit (node:events:341:22)
    at node:net:655:12
    at TCP.done (node:_tls_wrap:564:7) {
  code: 1011,
  reason: 'Internal response error'
}
```

My code is simply listening to some events on a some contracts. Sometimes it works for a day without any problem. But after it happens I can't reconnect for 30-60 minutes.
