### ISSUE TITLE
How to resend or cancel pending transaction?

### ISSUE THREAD

**Issue by zeleniy** [ethereum/web3.js#4442] opened 2021-10-08 14:34 UTC
### 

- [X] This is not a Bug Report, Feature Request, or related to Documentation

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

Depending on #4440 and #4441 (i mean nothing works as it should) how i can resend or cancel pending transaction using web3js API?

**Comment by nazarhussain** [comment] 2021-10-14 12:34
@zeleniy I had to close #4440 as it was not a bug related to `getTransaction`. 

For your question here I believe you [web3.eth.sendTransaction](https://web3js.readthedocs.io/en/v1.5.0/web3-eth.html#sendtransaction) would work. You have to send the transaction and wait for the confirmation, and if transaction is not confirmed or replaced due to any issue an error will be fired. Then you can respond to the error anyway you want. 

If that would be possible for you to create a reproducible script that mimic this flow, would be nice to investigate together on it.

**Comment by nazarhussain** [comment] 2021-10-28 13:06
@zeleniy Did you get a chance to look into this issue further. If you can create a reproducible script to simulate the workflow we can further investigate into it.

**Comment by nazarhussain** [comment] 2021-11-11 15:37
Hi @zeleniy, It's been long we didn't get an update from you. I am closing this issue. If  you can make an example snippet which can reproduce the flow, feel free to re-open the issue.

**Closed as completed by nazarhussain** 2021-11-11 15:37 UTC
Labels: 1.x, Question
