### ISSUE TITLE
Can't transfer tokens

### ISSUE THREAD

**Issue by vanzay** [ethereum/web3.js#2764] opened 2019-05-01 10:59 UTC
### Description
I'm trying to transfer tokens like this
```
const Web3 = require('web3');
const abi = require('human-standard-token-abi');

async function testSend() {
  let url = 'http://127.0.0.1:8545';
  let contractAddress = '0x6031ab93c5e436dfc6f4db819bf50f67e7b1289d';
  let from = '0x76b4514ceb23475be392e1305877a834401bdde8';
  let secret = 'secret';
  let to = '0xe63fb07be1bbc1d84c7e41554faf5457a1c4327e';
  let amount = 5 * 10 ** 18;
  let gas = 100000;

  let web3 = new Web3(new Web3.providers.HttpProvider(url));
  let contract = new web3.eth.Contract(abi, contractAddress);
  let gasPrice = await web3.eth.getGasPrice();
  await web3.eth.personal.unlockAccount(from, secret, null);
  let tx = await contract.methods.transfer(to, `${amount}`).send({from, gas, gasPrice});
  console.log(tx);
}
```
and I'm receiving an error "**Invalid params: invalid type: null, expected a block number or 'latest', 'earliest' or 'pending'.**"

### RPC calls traces
1. **eth_gasPrice**
```
{ jsonrpc: '2.0', id: 0, method: 'eth_gasPrice', params: [] }
```
```
{ jsonrpc: '2.0', result: '0x3b9aca00', id: 0 }
```
2. **personal_unlockAccount**
```
{ jsonrpc: '2.0',
  id: 1,
  method: 'personal_unlockAccount',
  params:
   [ '0x76b4514ceb23475be392e1305877a834401bdde8',
     '734873kjn873',
     null ] }
```
```
{ jsonrpc: '2.0', result: true, id: 1 }
```

3. **eth_sendTransaction**
```
{ jsonrpc: '2.0',
  id: 2,
  method: 'eth_sendTransaction',
  params:
   [ { from: '0x76b4514ceb23475be392e1305877a834401bdde8',
       gas: '0x186a0',
       gasPrice: '0x3b9aca00',
       data:
        '0xa9059cbb000000000000000000000000e63fb07be1bbc1d84c7e41554faf5457a1c4327e0000000000000000000000000000000000000000000000004563918244f40000',
       to: '0x6031ab93c5e436dfc6f4db819bf50f67e7b1289d' } ] }
```
```
{ jsonrpc: '2.0',
  result:
   '0xd1e0cf24bb077418b1836470b2d225c37568b373490b1b2087987c2ec8c06545',
  id: 2 }
```
4. **eth_getTransactionReceipt**
```
{ jsonrpc: '2.0',
  id: 3,                                                                                                                                                                                                      15:40
  method: 'eth_getTransactionReceipt',
  params:
   [ '0xd1e0cf24bb077418b1836470b2d225c37568b373490b1b2087987c2ec8c06545' ] }
```
```
{ jsonrpc: '2.0',
  result:
   { blockHash: null,
     blockNumber: null,
     contractAddress: null,
     cumulativeGasUsed: '0x96b9',
     from: null,
     gasUsed: '0x96b9',
     logs: [ [Object] ],
     logsBloom:
      '0x0000000000100000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000800000000000000000000000000000000010000000000000000
0000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000002000000000000000000100000000000000000000000000000000000000000010000000000000000000000000000002000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000002',
     root: null,
     status: '0x1',
     to: null,
     transactionHash:
      '0xd1e0cf24bb077418b1836470b2d225c37568b373490b1b2087987c2ec8c06545',
     transactionIndex: '0x0' },
  id: 3 }
```
5. **eth_getBlockByNumber**
```
{ jsonrpc: '2.0',
  id: 4,
  method: 'eth_getBlockByNumber',
  params: [ null, false ] }
```
```
{ jsonrpc: '2.0',
  error:
   { code: -32602,
     message:
      'Invalid params: invalid type: null, expected a block number or \'latest\', \'earliest\' or \'pending\'.' },
  id: 4 }
```

### Versions 
* web3.js: 1.0.0-beta.53
* nodejs: v10.12.0
* parity: 2.4.5 (ropsten network)

**Comment by nivida** [comment] 2019-05-01 11:12
Thanks for opening this issue! As it looks like is partiy not returning a block number in the transaction receipt: 
``` javascript 
{ jsonrpc: '2.0',
  result:
   { blockHash: null,
     blockNumber: null,
     contractAddress: null,
     cumulativeGasUsed: '0x96b9',
     from: null,
     gasUsed: '0x96b9',
     logs: [ [Object] ],
     logsBloom:
      '0x0000000000100000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000800000000000000000000000000000000010000000000000000
0000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000002000000000000000000100000000000000000000000000000000000000000010000000000000000000000000000002000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000002',
     root: null,
     status: '0x1',
     to: null,
     transactionHash:
      '0xd1e0cf24bb077418b1836470b2d225c37568b373490b1b2087987c2ec8c06545',
     transactionIndex: '0x0' },
  id: 3 }
```

Could you open an issue in the parity repository?

**Comment by vanzay** [comment] 2019-05-01 11:38
Opened https://github.com/paritytech/parity-ethereum/issues/10623
Thanks

**Comment by vanzay** [comment] 2019-05-01 11:54
BTW with 1.0.0-beta.36 the source piece of code works well.

**Comment by nivida** [comment] 2019-05-01 12:23
Yes, because there isn't a check if a new block got mined if you use the HttpProvider. The fix in the latest version would be to use the WebsocketProvider.

Edit: [TransactionObserver](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-core-method/src/observers/TransactionObserver.js)

**Comment by vanzay** [comment] 2019-05-01 12:34
Will the issue be fixed for the HttpProvider?

**Comment by vanzay** [comment] 2019-05-02 09:54
I've changed the source code with the WebsocketProvider. Now it hangs on the line:
```
let tx = await contract.methods.transfer(to, `${amount}`).send({from, gas, gasPrice});
```

**Comment by nivida** [comment] 2019-05-02 11:07
@vanzay The HttpProvider issue got already fixed and will be released today. 
Did you configure the transaction confirmation workflow as documented in the [documentation](https://web3js.readthedocs.io/en/1.0/web3.html#transactionblocktimeout)? 

Btw.: Could you ask further question in our [gitter](https://gitter.im/ethereum/web3.js) channel, on [StackOverflow](https://ethereum.stackexchange.com/) or the community-driven [discord](https://discord.gg/EKCthR) server?

**Comment by vanzay** [comment] 2019-05-03 06:35
In 1.0.0-beta.54 the HttpProvider still doesn't work.

**Comment by nivida** [comment] 2019-05-03 10:16
Could you add a GitHub repository or all required code snippets to reproduce it?

**Comment by vanzay** [comment] 2019-05-03 10:49
Added https://github.com/vanzay/web3-test

**Comment by nivida** [comment] 2019-05-03 11:50
Did you also test it with a configured transaction confirmation workflow as described in the documentation?

**Comment by vanzay** [comment] 2019-05-03 12:19
Also tried this way:
```
  let web3 = new Web3(new Web3.providers.HttpProvider(url), null, {
    transactionBlockTimeout: 50,
    transactionConfirmationBlocks: 24,
    transactionPollingTimeout: 480
  });
```
the same result.

**Comment by nivida** [comment] 2019-05-03 12:23
You have to wait for 24 blocks and then the transaction will resolve.

**Closed as completed** 2019-05-03 12:23 UTC

**Comment by vanzay** [comment] 2019-05-03 12:32
But why do I receive an exception? How to avoid it?

**Comment by vanzay** [comment] 2019-05-06 07:51
@nivida Why has the issue been closed? It's not resolved yet (see the comment above).

**Comment by kael-shipman** [comment] 2019-06-07 14:54
I agree, I'm still getting this issue. The issue shouldn't be closed until there's a satisfactory resolution for it. Please re-open.

**Comment by imbenwolf** [comment] 2019-06-24 17:23
I am currently not happy:
- to use httpprovider as expected, beta.51+ needs to be used (https://github.com/ethereum/web3.js/issues/1986#event-2279111028)
- when using beta.51+, ganache is broken (https://github.com/ethereum/web3.js/issues/2610)

and now, when i finally figured all that out:
- apparently, to transfer tokens, beta.36 needs to be used?? otherwise there is no clean way to support parity or am i wrong?

what is going on @nivida?

**Comment by nivida** [comment] 2019-06-25 08:32
Could you reference a GitHub repository? @imbenwolf

**Comment by imbenwolf** [comment] 2019-06-27 10:40
hi @nivida please see referenced issues in my comment. here a short summary:
- httpprovider returns "Uncaught TypeError: Cannot read property 'node' of undefined." when under beta.51 as per your comment
- ganache-cli does not support eth_chainid rpc endpoint thus not working with web3 (bad!). It is unfortunate that the truffle team does not fix such issues quickly but why not calculate for a fallback? this way nobody can use ganache-cli to develop with web3!
- after some experimenting, i realized that what you were suggesting "You have to wait for 24 blocks and then the transaction will resolve." can be achieved with setting "web3.transactionConfirmationBlocks = 24" in the future i would suggest constructively not closing an issue without also providing a working resolution as it will make it very hard for developers to keep up with all these issues while working for a company. I do appreciate the work & help you are giving though
