### ISSUE TITLE
Error: Couldn't decode uint256 from ABI: 0x

### ISSUE THREAD

**Issue by quantumproducer** [ethereum/web3.js#1629] opened 2018-05-14 01:42 UTC
I created this Contract: 

https://etherscan.io/address/0xfc7e86dbd205d02f97316995d8ace5d0afb9fe62#readContract

You can see in the Read Contract section that ownersNum is a uint with a current value of 1.

I copied the address

0xFc7e86dBD205D02F97316995d8AcE5D0AFB9fe62 and validated with https://tokenmarket.net/
ethereum-address-validator

```
cat keyaddress.js
module.exports = '0xFc7e86dBD205D02F97316995d8AcE5D0AFB9fe62'
```

In my node server, I created abi.js and copied the abi from etherscan

```
cat abi.js
module.exports = [{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"owners","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"ownersNum","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[],"name":"payout","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"developer","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[],"name":"buyKey","outputs":[{"name":"success","type":"bool"}],"payable":true,"stateMutability":"payable","type":"function"},{"anonymous":false,"inputs":[{"indexed":true,"name":"buyer","type":"address"}],"name":"QuantumPilotKeyPurchased","type":"event"}];
```

Now I try to read the ownersNum value in memory:

```
const fs = require('fs');
const express = require('express');
const Web3 = require('web3');
const BigNumber = require('bignumber.js');
const sigUtil = require('eth-sig-util');
const abi = require('./abi');
const keyaddress = require('./keyaddress');

var web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
let c = new web3.eth.Contract(abi, keyaddress);
console.log(c);

let on = c.methods.ownersNum().call();
        console.log(on);
        return;


//below is never reached, the above crashes
//  on.then(function(a,b) {
          //console.log(a);
          //console.log(b);
  //});
```

And this happens

```
     ... (contract details)
       name: 'buyKey',
       outputs: [Array],
       payable: true,
       stateMutability: 'payable',
       type: 'function',
       signature: '0xe95db6f9' },
     { anonymous: false,
       inputs: [Array],
       name: 'QuantumPilotKeyPurchased',
       type: 'event',
       signature: '0x55985f5332be13e699aaa51a5d3c003941f60e74af84533ebab5626b72cf3f51' } ] }
Promise { <pending> }
(node:5079) UnhandledPromiseRejectionWarning: Error: Couldn't decode uint256 from ABI: 0x
    at SolidityTypeUInt.formatOutputUInt [as _outputFormatter] (/root/scan/node_modules/web3-eth-abi/src/formatters.js:174:15)
    at SolidityTypeUInt.SolidityType.decode (/root/scan/node_modules/web3-eth-abi/src/type.js:252:17)
    at /root/scan/node_modules/web3-eth-abi/src/index.js:327:49
    at Array.forEach (<anonymous>)
    at ABICoder.decodeParameters (/root/scan/node_modules/web3-eth-abi/src/index.js:326:13)
    at Contract._decodeMethodReturn (/root/scan/node_modules/web3-eth-contract/src/index.js:459:22)
    at Method.outputFormatter (/root/scan/node_modules/web3-eth-contract/src/index.js:812:46)
    at Method.formatOutput (/root/scan/node_modules/web3-core-method/src/index.js:163:54)
    at sendTxCallback (/root/scan/node_modules/web3-core-method/src/index.js:475:33)
    at /root/scan/node_modules/web3-core-requestmanager/src/index.js:147:9
    at XMLHttpRequest.request.onreadystatechange (/root/scan/node_modules/web3-providers-http/src/index.js:77:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/root/scan/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/root/scan/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/root/scan/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/root/scan/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:5079) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5079) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This used to work fine while I was testing on Kovan. Now I switch to MainNet, upgrade web3, getting this error. I was on beta27, upgraded today to 34, same error, slightly different printout but same result.

**Comment by asselstine** [comment] 2018-05-15 00:31
I have the same issue.  I'm using MetaMask if that helps.

**Comment by quantumproducer** [comment] 2018-05-15 00:48
@asselstine you got an error reading a transaction?
Do you get the same error when reading from a smart contract?

**Comment by quantumproducer** [comment] 2018-05-15 10:31
@asselstine , according to https://ethereum.stackexchange.com/questions/48431/error-couldnt-decode-uint256-from-abi-0x/48518#48518 "Your code works in Infura" ..

 I tried out in Metamask too, per https://www.reddit.com/r/ethdev/comments/8jgyes/why_is_web3_returning_0x_for_my_contract_calls/ (needs 0.2 API calls for Web3)

**Comment by asselstine** [comment] 2018-05-15 17:43
I reset my local Ganache instance and it seemed to resolve the issue.  At least for now ;)

**Comment by asselstine** [comment] 2018-05-17 18:17
@quantumproducer I've isolated the problem down to one thing:

An eth_call message is being sent to the node with a zero `to` address.

I.e.:

eth_call:
to: "0x0000000000000000000000000000000000000000"

It really doesn't like that.   The error may be in my code...I'm investigating.  Regardless it would be handy for web3 to complain if 'to' is null.

**Comment by asselstine** [comment] 2018-05-17 18:32
I can confirm: one of my Truffle artifacts was not deployed to the network I was on.  Sending eth_call to  the zero addresses results in the '0x' encoding issue.

**Comment by asselstine** [comment] 2018-06-17 02:01
### A VM exception in a constant function call will cause Web3 to throw

> Couldn't decode *** from ABI: 0x

**Comment by netpoe** [comment] 2018-06-17 04:12
I'm getting this error with mainnet infura, but not in ropsten infura.

Using web3@1.0.0.beta.33: 

```
    let nonce = await this.getNonce(this.simpleCrowdsale)

    let txOptions = {
      from: this.wallet.getAddress(),
      gas: Web3.utils.toHex(this.gas),
      gasLimit: Web3.utils.toHex(this.gas),
      gasPrice: Web3.utils.toHex(this.defaultGasPrice),
      data: txObject.encodeABI(),
      nonce: Web3.utils.toHex(nonce)
    }

    try {
      let signedTx = await this.web3.eth.accounts.signTransaction(txOptions, this.wallet.getInstance().privateKey)
      let receipt = await this.web3.eth.sendSignedTransaction(signedTx.rawTransaction) // error happens here
```

**Comment by marcosmartinez7** [comment] 2018-06-22 19:53
Same problem here using Geth 1.8 and web3@1.0.0.beta.33 when trying to invoca a call

**Comment by mastashake08** [comment] 2018-06-27 02:18
I am having same issue what is status of ticket?

**Comment by quantumproducer** [comment] 2018-06-27 02:33
Try syncing... I ended up using parity because geth doesn't work on harddisks

**Comment by mastashake08** [comment] 2018-06-27 12:33
I'm connecting to infura so parity and geth are irrelevant in my case.

**Comment by hems** [comment] 2018-07-09 21:43
I'm calling `balanceOf` of an ERC20 token through a `geth` node connected to Kovan

This is the js code, using  web3 version: `1.0.0-beta.34`
````js
  const contract = new web3.eth.Contract(contractAbi, address)
  contract.methods.balanceOf(my_address).call()
````

Results in posting this json:
````json
{"jsonrpc":"2.0","id":7,"method":"eth_call","params":[{"data":"0x70a0823100000000000000000000000097ebb3391b30f495ce8cb97857db9b72d3e9dbcb","from":"0x97ebb3391b30f495ce8cb97857db9b72d3e9dbcb","to":"0x6ff6c0ff1d68b964901f986d4c9fa3ac68346570"},"latest"]}
````

And i can see the geth node replies me this:

````json
{"jsonrpc":"2.0","id":7,"result":"0x"}
````

In short: the RPC answer is wrong and missing the actual `balanceOf` the account, which i know is something like 0.005 of the token, which i can see on etherscan.

Something must be wrong on the js code?

**Comment by Rex-L** [comment] 2018-07-13 06:49
The different Ether network （Main Ethereum Network、 Ropsten Test Network、private Network、 private Network） have  different contractAddress. so  change contractAddress

**Comment by hems** [comment] 2018-07-13 16:34
indeed turns out this was happening because i was mistakenly connected to a different testnet than the one i thought i was!

perhaps a more friendly error could be yielded, such as 'not found' or 'not existent' something a little bit less cryptic

**Comment by justindthomas** [comment] 2018-08-06 07:06
For posterity (in case anyone else happens upon this with a similar challenge) I was also struggling with this problem just now and it turned out to be self-sabotage; I tested the Destructible pattern on my Rinkeby test ERC20 token before I deployed an update to mainnet by calling the "destroy()" method and then forgot I did that. So my Rinkeby token contract address was correct - as was my ABI. But the token had been invalidated.

**Comment by nivida** [comment] 2019-03-30 01:16
This got fixed with the PR https://github.com/ethereum/web3.js/pull/2608 and will be released asap.

**Closed by nivida** 2019-03-30 01:16 UTC
Labels: bug

**Comment by Sreesankar-G-Warrier** [comment] 2020-08-13 20:50
Hi, am also having the same issue and I got this error from my browser

 web3.min.js:1 Uncaught (in promise) Error: Couldn't decode  from ABI: 0x
    at o.formatOutputInt [as _outputFormatter] (web3.min.js:1)
    at o.decode (web3.min.js:1)
    at web3.min.js:1
    at Array.forEach (<anonymous>)
    at b.decodeParameters (web3.min.js:1)
    at M.d._decodeMethodReturn (web3.min.js:1)
    at f.outputFormatter (web3.min.js:1)
    at f.formatOutput (web3.min.js:1)
    at o (web3.min.js:1)
    at web3.min.js:1 

Am using these versions
Truffle v5.1.37 (core: 5.1.37)
Solidity v0.5.16 (solc-js)
Node v12.18.3
Web3.js v1.2.1

By using this web3 version I got another error from the browser.

 index.js:338 Uncaught (in promise) Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
    at h.decodeParameters (index.js:338)
    at B.d._decodeMethodReturn (index.js:572)
    at l.outputFormatter (index.js:935)
    at l.formatOutput (index.js:169)
    at o (index.js:653)
    at a (util.js:689)
    at b.run (browser.js:153)
    at p (browser.js:123) 

so I changed my web3 version to this cdn.

https://cdn.jsdelivr.net/gh/ethereum/web3.js@1.0.0-beta.34/dist/web3.min.js

Please help me to solve this issue and am very new to this tech. So, I hope, I will get a detailed explanation about this issue. Thanks in Advance.
