### ISSUE TITLE
getTransaction returns null

### ISSUE THREAD

**Issue by zeleniy** [ethereum/web3.js#4440] opened 2021-10-08 14:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have pending transaction [here](https://etherscan.io/tx/0xb95f0ba92378fd2205f8c33e3df49d898f1c1c745a514d2e4bbf1a1fdc8a20c6).
```
# node --no-warnings src/index.js 
null
```

### Expected Behavior

Should return transaction.

### Steps to Reproduce

```
web3.eth.getTransaction('0xb95f0ba92378fd2205f8c33e3df49d898f1c1c745a514d2e4bbf1a1fdc8a20c6').then(console.log);
```

### Web3.js Version

1.3.6

### Environment

```
# npm list --depth=0
ethereum.udiar.net@1.0.0 /root/ethereum-app
+-- commander@7.2.0
+-- ethereumjs-tx@2.1.2
+-- keythereum@1.2.0
+-- moment@2.29.1
+-- properties-reader@0.3.1
+-- sprintf-js@1.1.2
`-- web3@1.3.6
```

**Comment by nazarhussain** [comment] 2021-10-14 12:22
@zeleniy The `web3.eth.getTransaction` is meant to access the confirmed transactions. The transaction you are referring to is replaced and would not be available to the node you are connected to. The `etherscan` is showing it because of its own indexing of all transactions. 

I would not consider this a bug related to `getTransaction` so why closing this issue. Will look into your other issues and respond to them.

**Closed as completed by nazarhussain** 2021-10-14 12:22 UTC
Labels: Bug
