### ISSUE TITLE
Issue in getblocknumber

### ISSUE THREAD

**Issue by vvknda** [ethereum/web3.js#5661] opened 2022-11-29 13:55 UTC
Package : Node 16.18.1
Web3 v1.8.1

We have issue in the web3.eth.getBlockNumber();

Showing the invalid json response . I have attached the Screenshot with this for the reference . 

![image_2022_11_29T13_40_25_496Z](https://user-images.githubusercontent.com/81407249/204547230-4b7b8b5c-d7f6-4640-9806-d8bc50646431.png)

Please solve the issue ASAP .

**Comment by nikoulai** [comment] 2022-11-29 15:26
Hey, thanks for reaching out!

Could you please provide more info about the issue? which Ethereum node do you use?
If you can, please provide a reproducible example.

**Comment by vvknda** [comment] 2022-11-30 06:44
Ethereum Node version is v1.10.23 and installed & ETH2 Version ( lighthouse ) used . 


web3.eth.getBlockNumber();

Command only we get the issue above mentioned . But in the geth attach we see the eth.blockNumber is shown the updated block number . 

![Screenshot from 2022-11-30 12-12-47](https://user-images.githubusercontent.com/81407249/204726264-cf676f66-9256-40c9-a9d3-eeca1ac0d411.png)

**Comment by nikoulai** [comment] 2022-11-30 10:18
Have you initialized properly `Web3js`?  if you have a node running on localhost, the next example should work.

```ts
(async () => {
  let web3 = new Web3("http://localhost:8545"); //

  console.log("BlockNumber:", await web3.eth.getBlockNumber());
})();
```

**Comment by Muhammad-Altabba** [comment] 2022-11-30 17:29
Thanks @vvknda for opening an issue.
However, it seems that there is a misconfiguration of your connected node and how you are accessing it. This is unfortunately combined with an issue in web3.js that causes it to not report your issue clearly (this is probably the same or related to the issue: https://github.com/web3/web3.js/issues/5367). But web3.js does not have an issue with `getBlockNumber`. And you may find it informative to read the discussions here from other community members: https://ethereum.stackexchange.com/questions/76767/error-invalid-json-rpc-response-from-web3
 
And to confirm that the issue is with the `geth` configuration, and how it is being accessed, try running `geth` with `--rpcaddr 0.0.0.0` and `--rpccorsdomain "*"`. And let us know if you continue to face the issue or not.
However, it is extremely dangerous to have the mentioned configuration. But I recommend you do this in a test machine to confirm the issue's root cause. But for a production configuration, you would need different setups and configurations according to your exact case.

All the best,

**Comment by mconnelly8** [comment] 2023-06-21 16:26
Hey @vvknda, as @Muhammad-Altabba mentioned, this is a misconfiguration issue on your connected node, so we are closing it.

**Closed as completed by mconnelly8** 2023-06-21 16:26 UTC
Labels: Bug, Discussion, 1.x
