### ISSUE TITLE
connection not open on send()

### ISSUE THREAD

**Issue by lijodigiledge** [ethereum/web3.js#1654] opened 2018-05-23 09:08 UTC
# npm start

error on screen

connection not open on send()
connection not open on send()
connection not open on send()
Error: connection not open
    at WebsocketProvider.send (/home/lijo/philippines/chakka/node_modules/web3-providers-ws/src/index.js:247:18)
    at Timeout._onTimeout (/home/lijo/philippines/chakka/node_modules/web3-providers-ws/src/index.js:232:19)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

**Comment by ekryski** [comment] 2018-06-19 05:57
Duplicate of https://github.com/ethereum/web3.js/issues/1025

**Comment by kashifaa** [comment] 2018-07-17 05:00
acing same issue in web3@beta.34 , 
anyone find solution to this ???????

**Comment by danielj86** [comment] 2018-08-01 07:25
@kashifaa 

Could not find any good solution yet. for now im restarting my app with pm2 every 15 mins.

**Comment by nivida** [comment] 2018-08-10 06:43
I'm closing it because an issue to this already exists.

**Closed by nivida** 2018-08-10 06:43 UTC

**Comment by zomglings** [comment] 2018-11-02 21:20
@nivida : Where is the issue? Please link it here.

**Comment by genisgetman** [comment] 2018-11-22 09:45
Even issue #1025 that been redirect from here are closed unresolved =(

**Comment by tochie** [comment] 2018-11-28 18:05
@nivida please where is the link to the other issue since you closed this one ?

**Comment by rmujica** [comment] 2018-12-03 20:42
@tochie @nkashy1  #1965
