### ISSUE TITLE
Web3 doesn't return custom required message

### ISSUE THREAD

**Issue by dzabeu** [ethereum/web3.js#3327] opened 2020-01-22 11:20 UTC
Hi

When we have a revert in a transaction, web3 throws an error, and the error message contains this revert reason.

This error happen because i have a require inside my contract, so it is correct. So, i have a question: I can't get the custom message? 

For example, if i have this require below: 

` function functionExample( uint256 _number) public returns (bool) {
        require(_number>10,"Number need to be bigger than 10");
 }`

When i send a number, for example, 8 (<10, so require revert the transaction), and i`m receiving this return: 

`{ Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0x4370ed0ddd1f121377ea336223050e760a70c7713a275639bc890e8857c3ba99",
  "blockNumber": 5833233,
  "contractAddress": null,
  "cumulativeGasUsed": 391416,
  "from": "0x3e31b2a2784fdf3b03b4401c53de19063f4a512e",
  "gasUsed": 24055,
  "logs": [],
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0xb0345348c912d7856fb28cd6f7804c7dde339654",
  "transactionHash": "0x9bbde7f847e442fe67f5c4bac60996435167da993d320176f0efd302130778ed",
  "transactionIndex": 2
}`

Is it possible to receive the custom message? I mean, this message: "Number need to be bigger than 10".

This is so crucial for all contracts, and until now, i cant get this value...

Node: v10.15.3 
Web3.js:  
├─┬ truffle-contract@4.0.31
│ ├─┬ truffle-interface-adapter@0.2.5
│ │ └── web3@1.2.1 
│ └── web3@1.2.1 
├─┬ truffle-hdwallet-provider@1.0.17
│ └── web3@1.2.1 
└── web3@1.2.5-rc.0
OS: MacOS

**Comment by nivida** [comment] 2020-01-22 11:26
@dzabeu Thanks for opening this issue! We have added the possibility to get the revert message of a transaction with version 1.2.5-rc.0. This version will get released as a production version on Thursday if there is no show-stopper until then. You are able to activate the transaction revert handling with defining the ``web3.eth.handleRevert`` option to ``true``. The related documentation can currently be seen [here](https://github.com/ethereum/web3.js/blob/v1.2.5-rc.0/docs/web3-eth.rst#L407) and will be published on Thursday as well.

**Closed as completed by nivida** 2020-01-22 11:26 UTC
Labels: 1.x

**Comment by dzabeu** [comment] 2020-01-22 11:38
Hi @nivida !! 

I just downloaded the new version web3@1.2.5-rc.0, 10 minutes ago. This version doesn't have the improvement?   

I put on my topic the web3 version that i have in my project  
└── web3@1.2.5-rc.0

Tks

**Comment by nivida** [comment] 2020-01-22 11:46
@dzabeu Thanks for commenting here again! I've tested it and this is actually the case. The ``1.2.5-rc.0`` tag here on GitHub, the related release [branch](https://github.com/ethereum/web3.js/tree/release/1.2.5), and the working branch [1.x](https://github.com/ethereum/web3.js/blob/1.x/packages/web3-eth/src/index.js) do have those improvements included but not the published packages on ``npm``. We apologize for the confusion and will fix it (publish a rc.1 version) asap.

**Comment by dzabeu** [comment] 2020-01-22 11:50
Nice, tks you @nivida . This should be the problem, because i have used npm command to update the web3 version. 

Do you alert us about this update by this topic? How can i check the moment that i could use this new functionality?

**Comment by nivida** [comment] 2020-01-22 11:53
@dzabeu Thanks for your patience! I've tested it locally in an empty testing project and was no longer able to reproduce the issue. As it looks like does the ``package-lock`` of your project overwrite the ``web3-eth: 1.2.5-rc.0`` dependency to download the ``1.2.4`` version of it.

**Comment by dzabeu** [comment] 2020-01-22 12:05
I have deleted my package/package-lock.json and reinstall everything. But didnt work yet... 

I told me that i need to use this command. Do you have some example to help? 
web3.eth.handleRevert = true;

Tks!

**Comment by nivida** [comment] 2020-01-22 12:15
Which version of the ``web3-eth`` package does get installed? The possibility is here that truffles ``package-lock`` is enforcing another version.

**Comment by dzabeu** [comment] 2020-01-22 12:39
@nivida , only 1.2.5-rc.0: 

npm list web3
└── web3@1.2.5-rc.0 

Do you have an example to implement the command?

**Comment by dzabeu** [comment] 2020-01-22 13:16
Note: The contracts were deployed on Rinkeby network.  
Using ganache, for example, it is working normally (even before the update top 1.2.5...)

**Comment by dzabeu** [comment] 2020-01-22 13:23
Now, to deploy o ganache, i needed to install truffle-wallet-provider, and now i have two version:

├─┬ truffle-hdwallet-provider@1.0.17
│ └── web3@1.2.1 
└── web3@1.2.5-rc.0 

But anyway, it was not working when i was using only web3 1.2.5

**Comment by k06a** [comment] 2020-02-14 00:37
I also need an example, for me it seems this option does nothing

**Comment by cgewecke** [comment] 2020-02-14 01:58
@k06a 

There are examples in the unit tests [here][1]. 

Those tests succeed against both ganache-cli and a geth --dev client (see [travis here][2]).

Can you identify a difference between what's done there and your case? 

[1]: https://github.com/ethereum/web3.js/blob/1.x/test/e2e.method.send.js#L192-L324
[2]: https://travis-ci.org/ethereum/web3.js/jobs/646763831#L740

**Comment by SvenMeyer** [comment] 2020-02-23 10:50
I use web3@1.2.6 and still can not see a revert message.

```
try {
          web3.eth.handleRevert = true;
          this.result  = await this.contract.methods.addItem(
            this.ipfs_hash,
            product_amount_String,
            this.form.product_name,
            token_amount_String,
            this.form.metadata,
          ).send({ from: accounts[0], gas: 4e6, gasPrice: 1e6})
         .on('error', (err, receipt) => {
            console.log("err.message =",err.message);
            console.log("receipt =", receipt);
          });

} catch (err) {
        console.log("web3.eth.handleRevert =", web3.eth.handleRevert)
        console.error(err);
        console.log("err.message =",err.message);
}
```
web3.eth.handleRevert = true

err.message = Error: [ethjs-rpc] rpc error with payload {"id":8485727948832,"jsonrpc":"2.0","params":["0xf901cb13830f4240833d0900949eafc37a5d473c5c0c9532bcb54104dcf72ee28280b9016459a4a6bd00000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000de0b6b3a76400000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000002e516d56464464736b35454c4e44727937596e616965526835785a4b71594c376674634663384b514c4178326d3652000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000271710000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000822d45a0050a3ca0581633590c4869356707314ae2d2f78ef158289147b357b78ea95069a0183e78569153626421c161ae3499cd9f02ae154e93d9b18f50fe5a1df450a55e"],"method":"eth_sendRawTransaction"} [object Object]

err.signature = undefined
err.reason = undefined
receipt = undefined

I am using Ganache GUI v2.0.2 and if I run my code from remix, it manages to display the revert message.

Would be great to have one working example code snippet.

**Comment by jmahhh** [comment] 2020-02-26 06:59
I'm not sure this issue should be closed. Facing the same as above, attributes do not exist, on 1.2.6.

**Edit:** spoke too soon. @svenmeyer @k06a @dzabeu not sure what your setup is, but I can see `reason` if I `JSON.stringify` the resulting error, whether in a try-catch or in `.on('error', ...)`

**Comment by SvenMeyer** [comment] 2020-02-26 11:06
somehow remix as well as etherscan manage to get that information out of transactions, but I still haven't managed that with web3 ...
@jmahhh ok, thanks, I will give that a try

**Comment by dzabeu** [comment] 2020-02-27 13:41
Hi everybody!

I found it, and the article said that this is not work when you try to use with "sendSignedTransaction" function, that is right? 

I`m using  sendSignedTransaction.... maybe this is the reason that didn't work to me.

link:

https://www.soliditydeveloper.com/web3-1-2-5-revert-reason-strings/

**Comment by Elyx0** [comment] 2021-03-07 20:19
I get arrayify error:
```js
Uncaught Error: invalid arrayify value (argument="value", value="0xx08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000094c50543a452d3130310000000000000000000000000000000000000000000000", code=INVALID_ARGUMENT, version=bytes/5.0.10)
```

**Comment by MuhammadSajid404** [comment] 2021-03-13 06:12
Hi everybody

web3.eth.handleRevert = true 
after enabling handlerevert = true i am getting this kind of error from web3 in the browser console.

MetaMask - RPC Error: Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"message":"VM Exception while processing transaction: revert Only adopters can call this function","code":-32000,"data":{"0x9a5f8d4e7280d3519b09ed8f56eb9bbb3650c10d6d5d631171e185d1c5066dc1":

i want to display a specific part of this error in the UI "only adopters can call this function" from this error, is it possible? and second in what format this error is..

**Comment by DenkevichOleg** [comment] 2021-05-08 00:04
@nivida actual for 1.3.5 version:
`Uncaught Error: invalid arrayify value (argument="value", value="0xx08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001c466f6c6c6f77696e67733a20616c726561647920756e666f6c6c6f7700000000", code=INVALID_ARGUMENT, version=bytes/5.1.0)`

**Comment by SwampyDev** [comment] 2021-11-22 20:53
Is this issue still under investigation? @nivida 

Only solution I've found so far is to write some ghastly regex in an error handler such as the following:

```
handleRPCError = (error) => {
	const parsedError = JSON.stringify(error.message);

	if (parsedError.includes('execution reverted: ')) {
		const rgx = /(?<=execution reverted: )(.*)(?=\\n{)/g;
		const rgxResult = rgx.exec(parsedError);
		return Array.isArray(rgxResult) ? rgxResult[0] : rgxResult;
	}

	return 'Unknown error';
}
```

**Comment by nlukic97** [comment] 2022-03-10 00:15
I am experiencing a problem when I set handleRevert ([referenced in the web3 docs](https://web3js.readthedocs.io/en/v1.2.5/web3-eth-contract.html#handlerevert)) to **true** on my contract instance in NodeJS using Web3.js. Here's a simplified version of the setup:

1. Solidity:
```solidity
function registerVoter(address _address) external {
        require(voters[_address].registered == false,"This address is already registered.");

        // ...
}
```


2. script.js. I tried adding handleRevert to true using different methods, all of them fail and crash the nodeJS server **when solidity reverts the transaction:**
```js
// web3.eth.handleRevert = true; // Doesn't work. Tried adding it as was in unit test: https://github.com/ChainSafe/web3.js/blob/1.x/test/e2e.method.send.js#L192-L324
const contract = new web3.eth.Contract(abi,process.env.CONTRACT_ADDRESS);
contract.handleRevert = true // also doesn't work
// contract.options.handleRevert = true // also doesn't work
// contract.handleRevert = true // also doesn't work

contract.methods.sendNumberTen(9).send({from:process.env.WALLET_ADDRESS, gas:3000000})
.catch(err=>{
    console.log('SOMETHING WENT WRONG------------------------');
  })
```

The error:
```
Error: invalid arrayify value (argument="value", value="0xx08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000d556e617574686f72697a65642e00000000000000000000000000000000000000", code=INVALID_ARGUMENT, version=bytes/5.5.0)
```

**Comment by Qsajid** [comment] 2022-11-12 21:17
> Hi everybody
> 
> web3.eth.handleRevert = true after enabling handlerevert = true i am getting this kind of error from web3 in the browser console.
> 
> MetaMask - RPC Error: Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"message":"VM Exception while processing transaction: revert Only adopters can call this function","code":-32000,"data":{"0x9a5f8d4e7280d3519b09ed8f56eb9bbb3650c10d6d5d631171e185d1c5066dc1":
> 
> i want to display a specific part of this error in the UI "only adopters can call this function" from this error, is it possible? and second in what format this error is..

Thanks for the tip @MuhammadSajid404  👍

After setting  web3.eth.handleRevert = true  , now the error message contains 'reason', 'signature' and 'receipt' objects... 'reason' captures the value sent by 'require' from smart contract, as you can see from the sample below.

`{"reason":"Name already exists","signature":"Error(String)","receipt":{"transactionHash":"0x55d3323c567647a96164d2be4952202887c1cc43b399baf8a254377e0e267208","transactionIndex":0,"blockNumber":106,"blockHash":"0xd177f4afa7c9fe7faac161e9998cee1c7d5e7f9eca293a195457177ead59617a","from":"0x93aae3011c2b00bce40b348046cbfeae0c68be3e","to":"0x54eb7a2d655e93eca2be85dabe5da18b0748f327","cumulativeGasUsed":43843,"gasUsed":43843,"contractAddress":null,"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","status":false,"effectiveGasPrice":2500000883,"type":"0x2","events":{}}}`

**Comment by alireza1691** [comment] 2022-11-21 13:15
This message and these details came from blockchain , so you can't change them ,but you can change your log (what you want to get as a log).
