### ISSUE TITLE
sendSignedTransaction() error: invalid sender

### ISSUE THREAD

**Issue by Skyge** [ethereum/web3.js#2915] opened 2019-06-27 02:01 UTC
#### Expected behavior

    Calling `web3.eth.sendSignedTransaction(data)` should succeed.

#### Actual behavior

    Calling `web3.eth.sendSignedTransaction(data)` 
    returns `error: {"code":-32000,"message":"invalid sender"}`.

#### Steps to reproduce the behavior

```javascript
const Tx = require('ethereumjs-tx');
const privateKey = new Buffer('e33xxxxc0fd109', 'hex')

const rawTx = {
  nonce: '0x00',
  gasPrice: '0x09184e72a000',
  gasLimit: '0x2710',
  to: '0x0000000000000000000000000000000000000000',
  value: '0x00',
  data: '0x7f7465737432000000000000000000000000000000000000000000000000000000600057'
}

const tx = new Tx(rawTx);
tx.sign(privateKey);

const serializedTx = tx.serialize();

web3.eth.sendSignedTransaction('0x' + serializedTx.toString('hex'))
.on('receipt', console.log);
```

#### Error Logs 
```
error: {"code":-32000,"message":"invalid sender"}
```

### Versions 
* web3.js: 1.0.0-beta.55
* nodejs: v11.10.1
* browser: Chrome

**Comment by Skyge** [comment] 2019-06-27 02:03
But this is not a bug of `web3.js`, it is due to the package `ethereumjs-tx` at the version `2.0.0`, if you use the version `1.3.7`, it will not have this error.

**Comment by Skyge** [comment] 2019-06-28 02:26
Besides above, I can not get anything from Promise Event `receipt `, does that means `transactionHash` now?

**Comment by shumailxyz** [comment] 2019-06-29 22:06
I am having issues with `receipt` as well. Keeps on waiting. Works with version beta 1.0.0-beta.36.

**Comment by Skyge** [comment] 2019-07-02 08:59
@shumailxyz When I try to use a lower version: `1.0.0-beta.36`, I can get a log with `.on("receipt", …`

**Comment by Skyge** [comment] 2019-07-04 12:45
Ohhh, I find a similar issue that mentions the event `receipt`: #2601

**Comment by PaulRBerg** [comment] 2019-07-05 14:23
I can also confirm that ethereumjs-tx version 2.0.0 is broken:

> error: {"code":-32000,"message":"invalid sender"}

Reverting to 1.3.7 fixes the problem.

**Comment by Skyge** [comment] 2019-07-06 03:47
@PaulRBerg If you want to use the version: 2.0.0, you should add extra parameter `chain` like this
```ts
var tx = new Tx(rawTx, {'chain':'ropsten'});
```

**Comment by nivida** [comment] 2019-07-08 08:16
I've closed this because your problem is related to the ethereumjs-tx package.

**Closed as completed by nivida** 2019-07-08 08:16 UTC

**Comment by soumyaniljana** [comment] 2020-02-21 11:26
confirmed v1.3.7 works.

**Comment by zikyfranky** [comment] 2020-03-23 15:11
> @PaulRBerg If you want to use the version: 2.0.0, you should add extra parameter `chain` like this
> 
> ```ts
> var tx = new Tx(rawTx, {'chain':'ropsten'});
> ```

This works 100%

Thanks.

**Comment by programerr01** [comment] 2021-06-06 08:58
`var tx = new Tx(rawTx, {'chain':'ropsten'});
`
will it work for binance smart chain ?
```
const Tx = require('ethereumjs-tx').Transaction;
var Web3 = require('web3')
var web3 = new Web3(new Web3.providers.HttpProvider('https://bsc-dataseed1.binance.org:443'))
```

**Comment by zikyfranky** [comment] 2021-06-07 16:05
> `var tx = new Tx(rawTx, {'chain':'ropsten'}); `
> will it work for binance smart chain ?
> 
> ```
> const Tx = require('ethereumjs-tx').Transaction;
> var Web3 = require('web3')
> var web3 = new Web3(new Web3.providers.HttpProvider('https://bsc-dataseed1.binance.org:443'))
> ```

try also specifying the right chainId for Tx module using the `@ethereumjs/common` or  deprecated version `ethereumjs-common`

I haven't tested this, so I don't know if it works.

```js
import Common from 'ethereumjs-common'

const BSC_MAIN = Common.forCustomChain(
    'mainnet', {
        name: 'bnb',
        networkId: 56, 
        chainId: 56
    }, 
    'petersburg'
)

var tx = new Tx(rawTx, {common: BSC_MAIN});
```

**Comment by programerr01** [comment] 2021-06-07 17:36
> > `var tx = new Tx(rawTx, {'chain':'ropsten'}); `
> > will it work for binance smart chain ?
> > ```
> > const Tx = require('ethereumjs-tx').Transaction;
> > var Web3 = require('web3')
> > var web3 = new Web3(new Web3.providers.HttpProvider('https://bsc-dataseed1.binance.org:443'))
> > ```
> 
> try also specifying the right chainId for Tx module using the `@ethereumjs/common` or deprecated version `ethereumjs-common`
> 
> I haven't tested this, so I don't know if it works.
> 
> ```js
> import Common from 'ethereumjs-common'
> 
> const BSC_MAIN = Common.forCustomChain(
>     'mainnet', {
>         name: 'bnb',
>         networkId: 56, 
>         chainId: 56
>     }, 
>     'petersburg'
> )
> 
> var tx = new Tx(rawTx, {common: BSC_MAIN});
> ```

thanks, i'll test it though i switched to python

**Comment by TuanLe2411** [comment] 2021-10-01 16:03
> > > `var tx = new Tx(rawTx, {'chain':'ropsten'}); `
> > > will it work for binance smart chain ?
> > > ```
> > > const Tx = require('ethereumjs-tx').Transaction;
> > > var Web3 = require('web3')
> > > var web3 = new Web3(new Web3.providers.HttpProvider('https://bsc-dataseed1.binance.org:443'))
> > > ```
> > 
> > 
> > try also specifying the right chainId for Tx module using the `@ethereumjs/common` or deprecated version `ethereumjs-common`
> > I haven't tested this, so I don't know if it works.
> > ```js
> > import Common from 'ethereumjs-common'
> > 
> > const BSC_MAIN = Common.forCustomChain(
> >     'mainnet', {
> >         name: 'bnb',
> >         networkId: 56, 
> >         chainId: 56
> >     }, 
> >     'petersburg'
> > )
> > 
> > var tx = new Tx(rawTx, {common: BSC_MAIN});
> > ```
> 
> thanks, i'll test it though i switched to python

does it work?

**Comment by decentpay-finance** [comment] 2021-11-27 03:20
> > > `var tx = new Tx(rawTx, {'chain':'ropsten'}); `
> > > will it work for binance smart chain ?
> > > ```
> > > const Tx = require('ethereumjs-tx').Transaction;
> > > var Web3 = require('web3')
> > > var web3 = new Web3(new Web3.providers.HttpProvider('https://bsc-dataseed1.binance.org:443'))
> > > ```
> > 
> > 
> > try also specifying the right chainId for Tx module using the `@ethereumjs/common` or deprecated version `ethereumjs-common`
> > I haven't tested this, so I don't know if it works.
> > ```js
> > import Common from 'ethereumjs-common'
> > 
> > const BSC_MAIN = Common.forCustomChain(
> >     'mainnet', {
> >         name: 'bnb',
> >         networkId: 56, 
> >         chainId: 56
> >     }, 
> >     'petersburg'
> > )
> > 
> > var tx = new Tx(rawTx, {common: BSC_MAIN});
> > ```
> 
> thanks, i'll test it though i switched to python

did it work?

**Comment by prantiknoor** [comment] 2022-06-05 20:02
```
var Transaction = require("@ethereumjs/tx").Transaction;
var Common = require("@ethereumjs/common").default;

const BSC_MAIN = Common.custom({ name: "bnb", networkId: 56, chainId: 56 });
var tx = new Transaction(txData, { common: BSC_MAIN });
```
It has worked for me.

**Comment by namelessperson0** [comment] 2022-07-10 09:56
Change the below 
``` 
      const Tx = require('ethereumjs-tx').Transaction;

      var rawTransaction = {
        "from": myAddress,
        "gasPrice": web3js.utils.toHex(20 * 1e9),
        "gasLimit": web3js.utils.toHex(210000),
        "to": contractAddress,
        "value": "0x0",
        "data": contract.methods.safeTransferFrom(myAddress, toAddress, tokenId).encodeABI(),
      }

        var privateKey = Buffer.from('abcde', 'hex')

        var transaction = new Tx(rawTransaction,{ chain: 'ropsten' , hardfork: 'petersburg' });

        transaction.sign(privateKey);

        web3js.eth.sendSignedTransaction('0x' + transaction.serialize().toString('hex'))
            .on('transactionHash', console.log);
```
to the below
```
      const Tx = require('ethereumjs-tx').Transaction;

      var rawTransaction = {
        "from": myAddress,
        "gasPrice": web3js.utils.toHex(20 * 1e9),
        "gasLimit": web3js.utils.toHex(210000),
        "to": contractAddress,
        "value": "0x0",
        "data": contract.methods.safeTransferFrom(myAddress, toAddress, tokenId).encodeABI(),
      }

        var privateKey ='abcde'

        web3js.eth.accounts.signTransaction(rawTransaction, privateKey)
        .then(function(value){
            web3js.eth.sendSignedTransaction(value.rawTransaction)
            .then(function(response){
              console.log("response:" + JSON.stringify(response, null, ' '));
            })
          })
```
`web3js.eth.accounts.signTransaction` will take the burden of including the correct chainId and nonce .
Reference: https://github.com/ChainSafe/web3.js/issues/3305
