### ISSUE TITLE
setConfig doesnt working as expected

### ISSUE THREAD

**Issue by Zahar44** [ethereum/web3.js#6557] opened 2023-11-01 11:26 UTC
I checked code of web3-eth-contract/lib/commonjs/contract.js and from what I see it looks like this.config.contractDataInputFill used only to set it to this._dataInputFill and when called setConfig with contractDataInputFill it doesnt override this._dataInputFill.

#### Expected behavior
this code should override transaction input/data behavior

```
const token = new this.web3.eth.Contract(ERC20Abi);
token.setConfig({ contractDataInputFill: 'both' });
```
#### Actual behavior
Transaction sent with behavior of initial contractDataInputFill value

#### Steps to reproduce the behavior
this should throw exception if used in local hardhat node

```
const token = new this.web3.eth.Contract(ERC20Abi);
token.setConfig({ contractDataInputFill: 'both' });
token.methods.decimals().call();

```
#### Logs

this will log 'input'

```
const token = new this.web3.eth.Contract(ERC20Abi);
token.setConfig({ contractDataInputFill: 'both' });
console.log(token['_dataInputFill']);
```

#### Environment

"web3": "^4.2.1"

**Comment by Zahar44** [comment] 2023-11-01 11:28
For now I'm using this workaround and it works

`(token as any)['_dataInputFill'] = 'both';`

**Comment by luu-alex** [comment] 2023-11-01 15:27
thanks for submitting this issue, theres a fix to removing `_dataInputFill` all together and just use config
https://github.com/web3/web3.js/pull/6555
this should be merged in soon

**Comment by Muhammad-Altabba** [comment] 2023-11-02 09:24
Many thanks @Zahar44 for opening the issue and suggesting a workaround. This is helpful till the issue is fixed at https://github.com/web3/web3.js/pull/6555.
However, I am closing this issue in favor of keeping the discussion on https://github.com/web3/web3.js/pull/6555.

**Closed as completed by Muhammad-Altabba** 2023-11-02 09:24 UTC
Labels: Bug, 4.x
