### ISSUE TITLE
new update break something?

### ISSUE THREAD

**Issue by eyooooo** [ethereum/web3.js#3900] opened 2021-02-04 07:23 UTC
after running npm install my project no longer starts

```
d# yarn build
yarn run v1.22.5
$ CI= GENERATE_SOURCEMAP=false react-scripts build
Creating an optimized production build...
Failed to compile.

Could not find a declaration file for module 'web3-utils'. '/sdfsdfsfsdfsdf/node_modules/web3-utils/src/index.js' implicitly has an 'any' type.
  Try `npm install @types/web3-utils` if it exists or add a new declaration (.d.ts) file containing `declare module 'web3-utils';`  TS7016

    2 | import { provider } from 'web3-core'
    3 | import { Contract } from 'web3-eth-contract'
  > 4 | import { AbiItem } from 'web3-utils'
      |                         ^
    5 | import ERC20ABI from '../constants/abi/ERC20.json'
    6 |
    7 | export const getContract = (provider: provider, address: string) => {


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by GregTheGreek** [comment] 2021-02-04 17:13
The deceleration files are manually generated as of right now, can't imagine what woudl have happened.

Any chance you can provide a sample snippet for us to test with?

**Comment by eyooooo** [comment] 2021-02-04 21:14
1. `git clone https://github.com/sushiswap/sushiswap-legacy-frontend.git`
2. `cd sushiswap-legacy-frontend`
3. `npm i`
4. `yarn start`

Previously to yesterday, this would "just work". As of yesterday, I get this:

```
Failed to compile.

/tmp/sushiswap-legacy-frontend/src/utils/erc20.ts
TypeScript error in /tmp/sushiswap-legacy-frontend/src/utils/erc20.ts(4,25):
Could not find a declaration file for module 'web3-utils'. '/tmp/sushiswap-legacy-frontend/node_modules/web3-utils/src/index.js' implicitly has an 'any' type.
  Try `npm install @types/web3-utils` if it exists or add a new declaration (.d.ts) file containing `declare module 'web3-utils';`  TS7016

    2 | import { provider } from 'web3-core'
    3 | import { Contract } from 'web3-eth-contract'
  > 4 | import { AbiItem } from 'web3-utils'
      |                         ^
    5 | import ERC20ABI from '../constants/abi/ERC20.json'
    6 | 
    7 | export const getContract = (provider: provider, address: string) => {
```

My current solution is to copy/paste an old, working node_modules dir. 

Thanks!!!!

**Comment by GregTheGreek** [comment] 2021-02-05 23:58
@spacesailor24 can you take a look?

**Comment by eyooooo** [comment] 2021-02-06 20:29
@GregTheGreek were you able to reproduce this? Thanks

**Comment by Spacesai1or** [comment] 2021-02-08 15:53
Sorry for the delay, will be taking a look at this today - thank you for bringing it to our attention!

**Comment by Spacesai1or** [comment] 2021-02-08 17:22
Am able to reproduce, investigating now

**Comment by Spacesai1or** [comment] 2021-02-08 17:54
So I can't give you the exact reason why this error occurs, but in my testing it seems to be an issue with installing the project dependencies with `npm`, but using `yarn` to run the project. If you use `yarn` to install deps, then run `yarn start`, you don't receive the error

Without doing a deep dive, [this](https://www.reddit.com/r/javascript/comments/976dxy/i_have_both_yarn_and_npm_installed_and_theyre/e46dbpt?utm_source=share&utm_medium=web2x&context=3) was the best info I could find regarding the issue

Closing because this seems unrelated to Web3.js

**Closed as completed by Spacesai1or** 2021-02-08 17:54 UTC

**Comment by eyooooo** [comment] 2021-02-08 21:37
@spacesailor24 i can confirm your workaround works. I regret not thinking of this myself!! I am still a nub to all of the diff node systems. 

thanks so much for looking into this! appreciate you and @GregTheGreek very much.
