### ISSUE TITLE
Issue with result of sha3

### ISSUE THREAD

**Issue by kochurovro** [ethereum/web3.js#4698] opened 2022-01-12 17:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi!

The result of web3.utils.sha3 differs from the result of the same function which I got about 4-5 months ago.

data in is bafybeif5znxajp2we6fmjqu3al6tfik45nuiwtux4djaapn4ziyjjosklm.
the result now is 0x0d1bbc0bf1afc8e8fb4e769a9202a94421ab72b11921d57f77dbe389f4c7b542
the result before is 0xd1bbc0bf1afc8e8fb4e769a9202a94421ab72b11921d57f77dbe389f4c7b542

### Expected Behavior

the same results

### Steps to Reproduce

web3.utils.sha3("bafybeif5znxajp2we6fmjqu3al6tfik45nuiwtux4djaapn4ziyjjosklm")

### Web3.js Version

1.5.0

### Environment

- Operating System: macOS Monterey 12.0 
- Browser: FF 95.0.2
- Node.js Version: 15.18.2
- NPM Version: 8.3.0

**Comment by luu-alex** [comment] 2022-01-20 22:40
Yes the sha3 function was changed in the later versions of web3. It looks like web3.utils.sha3 is returning correctly now. The result before "0xd1bbc0bf1afc8e8fb4e769a9202a94421ab72b11921d57f77dbe389f4c7b542" is length 65 when it should be length 66.

**Comment by kochurovro** [comment] 2022-01-21 13:22
Hi @luu-alex 

Ok, let's close this issue. But first, could you write a version where the bug was fixed?

**Comment by luu-alex** [comment] 2022-01-21 15:04
The version where the bug was fixed was `1.6.0`. If you would like to reproduce old hashes feel free to use any versions before 1.6.0. I'll close this for now and if anything comes up feel free to reopen.

Thank you for bringing this to our attention!

**Closed as completed by luu-alex** 2022-01-21 15:04 UTC
Labels: Bug, 1.x
