### ISSUE TITLE
Error when using with React app

### ISSUE THREAD

**Issue by amaurymartiny** [ethereum/web3.js#981] opened 2017-08-14 08:21 UTC
I have errors when I use web3 inside a React app.

I'm using the MetaMask provider. Using v1.0-beta18, here's my code in the react app:
```js
import Web3 from 'web3';

const web3 = new Web3(window.web3.currentProvider)
console.log(web3.eth); // outputs not empty object
web3.eth.getAccounts().then(console.log); // outputs the error below
```
Gives error:
```
Wrong response id "1" (expected: "5097747587989961") in {"jsonrpc":"2.0","id":5097747587989961,"method":"eth_accounts","params":[]}
```

---

I though it was because of the 1.0 beta version, so I tried using stable v0.20.1. Same thing.

For example, in my Chrome console (responses start with ">"):
```js
web3.version
> Object {api: "0.20.1", getNode: function, getNetwork: function…}
web3.eth
> {_requestManager: s, getBalance: function, getStorageAt: function, getCode: function, getBlock: function…}
web3.eth.accounts
>inpage.js:8195 Uncaught Error: Invalid JSON RPC response: undefined
    at Object.InvalidResponse (inpage.js:8195)
    at s.send (inpage.js:8195)
    at r.accounts
> inpage.js:171 Uncaught TypeError: cb is not a function
    at inpage.js:171
    at inpage.js:8172
web3.eth.getAccounts((err, res) => console.log(res));
> inpage.js:222 Uncaught Error: MetamaskInpageProvider - sendAsync not overwritten
    at MetamaskInpageProvider.sendAsync (inpage.js:222)
    at s.sendAsync (inpage.js:8195)
    at r.e [as getAccounts] (inpage.js:8195)
    at <anonymous>:1:10
```

The above commands in the console of any other page work.

React: 15.6.1
Chrome:  60.0.3112.90 (Official Build) (64-bit)
OS: macOS Sierra 10.12.6 (16G29)

**Comment by 0xcaff** [comment] 2017-08-16 00:24
Duplicate of https://github.com/ethereum/web3.js/issues/940

**Comment by frozeman** [comment] 2017-08-16 03:26
Thanks @0xcaff this issue is useful but I'm closing it in favor of #940 
@kumavis any idea?

**Closed by frozeman** 2017-08-16 03:26 UTC

**Comment by sethfork** [comment] 2017-12-01 07:08
@amaurymartiny How did you get around this?

**Comment by amaurymartiny** [comment] 2017-12-21 19:00
@sethfork Sorry cannot tell exactly. Started fresh again, and it worked..
