### ISSUE TITLE
web3.eth.getBlock("genesis") throws exception

### ISSUE THREAD

**Issue by barakman** [ethereum/web3.js#3354] opened 2020-02-01 15:24 UTC
From [the official documentation on function `getBlock`](https://web3js.readthedocs.io/en/v1.2.0/web3-eth.html#id41):
> String|Number - The block number or block hash. Or the string "genesis", "latest" or "pending" as in the default block parameter.

#### Expected behavior

Calling `await web3.eth.getBlock("genesis")` should return the first block.

#### Actual behavior
Calling `await web3.eth.getBlock("genesis")` throws `Error: Given input "genesis" is not a number`.

#### Steps to reproduce the behavior

```
const Web3 = require("web3");

async function run() {
    const web3 = new Web3("https://infura.io");
    const block = await web3.eth.getBlock("genesis");
    console.log(block.number, block.timestamp);
}

run();
```

#### Versions
[NPM 6.9.0, Node 10.16.0, Web3.js 1.2.1]

**Comment by nivida** [comment] 2020-02-02 13:14
@barakman Thanks for opening this issue. I will check that closer tomorrow. 👌

**Comment by nivida** [comment] 2020-02-03 12:50
Hey! I've tested it with the latest version of web3.js (1.2.6) and I was able to execute the following code successfully: 

``` javascript
var provider = new Web3.providers.WebsocketProvider('ws://localhost:7545');
var web3 = new Web3(provider);
console.log(Web3.version);
web3.eth.getBlock('genesis').then(console.log);
```

Result:
``` javascript
{
difficulty: "0"
extraData: "0x"
gasLimit: 6721975
gasUsed: 0
hash: "0xf616468789670f828080b956a12c6a1bad710338cb9e848fe93488a54f92a9fb"
logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
miner: "0x0000000000000000000000000000000000000000"
mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000"
nonce: "0x0000000000000000"
number: 0
parentHash: "0x0000000000000000000000000000000000000000000000000000000000000000"
receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"
sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347"
size: 1000
stateRoot: "0x061dde02aabfc0b389b7fcaba5fd818ae0dec727772b1e1fbb2b9a8ca318132f"
timestamp: 1580395570
totalDifficulty: "0"
transactions: []
transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"
uncles: []
}
```

I'm closing this issue now because it isn't reproducible. Feel free to drop a comment here if the issue still exists on your side also with the latest version of web3.js.

**Closed as completed by nivida** 2020-02-03 12:50 UTC
Labels: Needs Clarification, 1.x

**Comment by barakman** [comment] 2020-02-03 13:41
@nivida:
No problem, but this feature is stated in the official documentation of web3.js v1.2.0, and it is (by the least) not supported in web3.js v1.2.1, so you might wanna edit the documentation and clear it up there.
Thanks
