### ISSUE TITLE
callbackify is not a function when trying to sign a message

### ISSUE THREAD

**Issue by emperorjm** [ethereum/web3.js#3739] opened 2020-10-08 21:56 UTC
I am using "web3": "1.2.11" but have tried 1.3.0 as well with the same issue. The code is as follows:

```
this.web3js.eth.personal.sign(message, publicAddress, '').then(response => {
          console.log(response);
          this.login(publicAddress, response);
        }).catch(function (error) {
          //reject(false);
        });
```

The following error is thrown and I can't find anything online to help with finding out what's wrong:

TypeError: callbackify is not a function
    at RequestManager.send (index.js?abfa:183)
    at sendRequest (index.js?0e85:763)
    at Personal.send (index.js?0e85:797)
    at eval (App.vue?26cd:119)

**Comment by frankiebee** [comment] 2020-10-09 20:25
thanks for reporting this issue. This is a duplicate of #3727

**Closed as completed by frankiebee** 2020-10-09 20:25 UTC
