### ISSUE TITLE
window is not defined in Cloudflare workers

### ISSUE THREAD

**Issue by andreademasi** [ethereum/web3.js#5729] opened 2023-01-04 19:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
ReferenceError: window is not defined
    at node_modules/.pnpm/web3@1.8.1/node_modules/web3/dist/web3.min.js (/home/andrea/faucet/node_modules/.pnpm/web3@1.8.1/node_modules/web3/dist/webpack:/webpack/universalModuleDefinition:10:4)
```
Looks like there's a window reference in webpack used by web3.js

### Expected Behavior

Load Web3 correctly

### Steps to Reproduce

```typescript
import Web3 from 'web3'

const provider = new Web3.providers.HttpProvider("https://polygon-mainnet.infura.io/v3/...")
const web3 = new Web3(provider)
```

### Web3.js Version

1.8.1

### Environment

- Wrangler 2

**Comment by Spacesai1or** [comment] 2023-03-29 05:14
Hi @andreademasi, is this still an issue you're facing? I tested your reproduction steps with `v1.8.1` without Wrangler 2 and wasn't able to reproduce the error. If you're still receiving this error, could you share a Github repo with your complete setup so we can test this better?

**Comment by mconnelly8** [comment] 2023-06-21 17:39
@andreademasi, since we didn't get a response, we are closing this issue. 

Web3.js 4.x has been released, so it's highly encouraged to use the latest web3.js:
https://docs.web3js.org/
https://docs.web3js.org/guides/web3_upgrade_guide/x/
https://www.npmjs.com/package/web3/v/4.0.1
https://github.com/web3/web3.js/releases/tag/v4.0.1

**Closed as completed by mconnelly8** 2023-06-21 17:39 UTC
Labels: Bug, Needs Clarification, 1.x
