### ISSUE TITLE
Transaction  has been reverted by the EVM in token transfer 

### ISSUE THREAD

**Issue by bh0717-dev** [ethereum/web3.js#7287] opened 2024-09-25 23:41 UTC
`try {
    let rpcUrl;
    if (network === "ETH") rpcUrl = process.env.MAINNET_INFURA_URL;
    else if (network === "BSC") rpcUrl = process.env.BSC_MAINNET_INFURA_URL;
    console.log("rpcUrl:", rpcUrl);
    const web3 = new Web3(rpcUrl);
    const account = web3.eth.accounts.privateKeyToAccount("0x" + privateKey);
    const fromAddress = account.address;
    const tokenContract = new web3.eth.Contract(tokenAbi, tokenAddress);

    const nonce = await web3.eth.getTransactionCount(fromAddress, "latest");

    const wallet = web3.eth.accounts.wallet.add("0x" + privateKey);

    const gasLimit = await web3.eth.estimateGas({
      from: fromAddress,
      to: tokenAddress,
      data: tokenContract.methods.transfer(toAddress, amount).encodeABI(),
    });

    console.log("nonce, gasLimist:", nonce, gasLimit);
    const tx = {
      from: fromAddress,
      to: tokenAddress,
      data: tokenContract.methods.transfer(toAddress, amount).encodeABI(),
      gasPrice: await web3.eth.getGasPrice(),
      gasLimit: gasLimit,
      nonce: nonce,
      chainId: network === "ETH" ? 1 : 56,
    };
    const signedTx = await web3.eth.accounts.signTransaction(tx, privateKey);
    console.log("signedTx:", signedTx);
    const receipt = await web3.eth.sendSignedTransaction(
      signedTx.rawTransaction
    );

    console.log(
      "Token transfer successful with hash:",
      receipt.transactionHash
    );
    return receipt;`
amount: 356981723430n
This is my code and log of amount. I am getting Transaction has been reverted by the EVM in sendSignedTransaction.
Plz help for solving my problem as soon as possible

**Comment by danforbes** [comment] 2024-09-26 12:38
Can you share the details of the contract you're trying to interact with?

**Comment by wonderBH717** [comment] 2024-09-26 12:48
https://etherscan.io/address/0xd29da236dd4aac627346e1bba06a619e8c22d7c5
This is my token contract.

**Comment by danforbes** [comment] 2024-09-26 12:51
So you're interacting with the contract on Ethereum Mainnet? Are you certain that the `from` account has sufficient funds to transfer? What is the address of the `from` account?

**Comment by luu-alex** [comment] 2024-10-01 14:00
Whats the error?

**Comment by mconnelly8** [comment] 2024-10-14 17:03
Hey @bh717, any additional information you can provide and answering the questions above?  We'd like to look into this issue and resolve it for you.

**Comment by krzysu** [comment] 2024-11-15 08:06
Hey @bh717, since we haven’t heard back from you in the past month, it seems the issue is no longer affecting you. I’m closing this for now, but feel free to reopen it if you’d like to continue the discussion and you have more insights to share with us.

**Closed as completed by krzysu** 2024-11-15 08:06 UTC
Labels: 4.x
