### ISSUE TITLE
BNB chain - Sending a signature to MinimalForwarder openzeppelin contract fail the ECDSA verification with error 'ECDSA: Invalid signature 'v'' 

### ISSUE THREAD

**Issue by HmFlashy** [ethereum/web3.js#5607] opened 2022-11-10 10:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello
So we want to relay transactions using this contract https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/metatx/MinimalForwarder.sol
The method 'execute' takes the signature as a parameter (bytes)
So using web3js we are signing a transaction like this

```
const tx = {
      from: fromAccount.address,
      to: coin,
      value: 0,
      nonce,
      gas,
      data,
}
let signedTx = await fromAccount.signTransaction(tx)
```

But then we need the whole signature in a buffer to send it to the smart contract. I recreate the signature by concatenating r, s, v from the signed transaction

```
const signature = Buffer.concat([
      Buffer.from(signedTx.r.replace('0x', ''), 'hex'),
      Buffer.from(signedTx.s.replace('0x', ''), 'hex'),
      Buffer.from(signedTx.v.replace('0x', ''), 'hex'),
])
```

Then I create the relay transaction and sign it with a different wallet

```
const relayed = relayContract.methods.execute(
        {
          from: fromAccount.address,
          to: coin,
          value: 0,
          gas,
          nonce,
          data,
        },
        signature,
      )

      const relayTx = {
        from: projectAccount.address,
        to: this.bscService.relayContractAddress,
        gas: 5000000,
        data: relayed.encodeABI(),
      }

      signedTx = await projectAccount.signTransaction(relayTx) 
```

Then I send the transaction like so 

`await this.bscService.sendSignedTransaction(signedTx)`

And I get this error message
`Fail with error 'ECDSA: invalid signature "v" value'`

From what I see, the 'v' should be 27 or 28 but ours is 229.
See: https://github.com/ethereum/go-ethereum/blob/ba3919cac609134dc81b64250fc09c56dd65b46d/signer/core/signed_data.go#L279

I saw that the new way of calculating the "v" is CHAIN_ID * 2 + 35
Since BNB chain testnet id is 97, 97 * 2 + 35 = 229. So the 'v' should be ok.

But when I check the source code of ecrecover of the BNB chain. If it is not 27 or 28, the "v" is not valid.

I don't really know how to manage this problem. I need to verify the signature of the relayed transaction in the smart contract. But I don't know how to as the 'v' check.

Thanks
### 

### Expected Behavior

The expected behavior is that the signature I send to the smart contract should be ok. And both the relay and the wrapped transaction should be executed.

### Steps to Reproduce

Deploy a MinimalForwarder contract to BNB chain testnet (Relayer)
Deploy any other contract with a method in it (AnyContract)

Create a transaction for the contract AnyContract and sign it.
You'll get the r, s, v fields of the signature.
Then create the transaction for the Relayer contract. With the correct request fields and the signature created from the r, s and v field.
Sign this new transaction and send it to the chain.

You should get an error saying 
`Fail with error 'ECDSA: invalid signature "v" value'`

### Web3.js Version

1.7.0

### Environment

- Operating System: Manjaro
- Browser: 
- Node.js Version: Node 16.17.0
- NPM Version:

**Comment by nikoulai** [comment] 2022-11-11 09:54
Hey, thanks for reaching out!

Could you please also provide your test data?
Maybe changing the `common` property to pass a different `chainId` that could lead to a correct calculation?
https://web3js.readthedocs.io/en/v1.8.1/web3-eth-contract.html#defaultcommon

**Comment by HmFlashy** [comment] 2022-11-11 15:01
Thanks for your answer. 
```
const contract = this.bscService.createContract(this.coinAbi, coin)
    const decimals = Number(await contract.methods.decimals().call())
    const transfer = contract.methods.transfer(
      toAddress,
      this.bscService.toUnit(amount.toString(10), decimals),
    )
    const fromAccount = this.bscService.accountFromSecretKey(
      fromWallet.privateKey,
      fromWallet.salt,
    )
    const gas = await transfer.estimateGas({ from: fromAccount.address })
    const data = transfer.encodeABI()
    const nonce = await this.bscService.getNonce(fromAccount.address)
```
The data is just the encoded ABI for a simple transfer method.

We create the client via an HTTP provider like so
```
this.client = new Web3(
      new Web3.providers.HttpProvider(apiConfigService.bscConfig.endpoint),
)
```
I'll try changing the chainId, but it looks ok, I mean 229 is the correct id for the BNB chain testnet. 97 * 2 + 35 = 229

**Comment by HmFlashy** [comment] 2022-11-11 17:33
And yes, this is not the first transaction we do toe the bnb blockchain. And it was working fine until now.

**Comment by nikoulai** [comment] 2022-11-14 11:33
From the error message, I see that the `signedTx` is the one failing. Do the other txs to BNB work fine?

**Comment by HmFlashy** [comment] 2022-11-17 08:28
Indeed the signedTx is the one that encapsulate the base transaction that will be relayed. But yes, if I just send the base transaction it is working fine

**Comment by nikoulai** [comment] 2022-12-12 15:22
Hey @HmFlashy 

I'm currently looking into the issue. However, I cannot reproduce it the issue (inner transaction is failing for me, not the outer). 
Could you please share a reproducible example?

For more direct communication, you can reach us/me on our discord server.

**Comment by nikoulai** [comment] 2023-01-04 11:47
I'm going to close the issue, if you still phase the problem feel free to reopen it or reach us in our discord.

**Closed as completed by nikoulai** 2023-01-04 11:47 UTC
Labels: Bug, 1.x

**Comment by imranmahmudshoiball** [comment] 2023-01-14 21:36
This is a great project

**Comment by Aheyachy** [comment] 2023-01-14 21:38
Thanks
