### ISSUE TITLE
[BUG] getblockNumber function cannot get adjacent blocks.

### ISSUE THREAD

**Issue by vinhyenvodoi98** [ethereum/web3.js#3384] opened 2020-02-21 09:43 UTC
I use an interval loop (1s) in javascript to call getBlockNumber. but it cannot return adjacent block number. but if I use rpc api then it can return consecutive numbers

# Steps to reproduce the behavior
To easily reproduce I use tomochain because this blockchain can create blocks in 2s 
url : https://rpc.tomochain.com
chainID: 88 
(You can use the ethereum mainnet but it will take more time to reproduce.)

![image](https://user-images.githubusercontent.com/33363513/75022408-9ea49500-54c8-11ea-8337-c5d8d2e55cac.png)

## Using javascript
```js
let currentBlock = await web3.eth.getBlockNumber();
console.log(currentBlock.number);
```

## Using rpc api 
```sh
curl -X POST  -H "Content-type: application/json" --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' https://rpc.tomochain.com
```
Result
```sh
{"jsonrpc":"2.0","id":1,"result":"0x21e22"}
```
and the next is 
```sh
{"jsonrpc":"2.0","id":1,"result":"0x21e23"}
```
#### Versions
Web3.js v1.2.6

**Comment by cgewecke** [comment] 2020-02-25 00:02
@vinhyenvodoi98 I'm not able to reproduce this problem - have had no problem getting correct sequential block numbers. 

Could you double-check your code and/or generate a more complete description of how to simulate the error (perhaps using Infura?) 

Closing for now - can't reproduce.

**Closed as completed by cgewecke** 2020-02-25 00:02 UTC

**Comment by vinhyenvodoi98** [comment] 2020-02-27 04:14
@cgewecke sorry about no live demo for you
live demo : https://dht11-5a0f1.firebaseapp.com/

**Note for live demo**
Please create new network in your metamask ( Tomochain Mainnet maybe ) and input same chain url 

github : https://github.com/vinhyenvodoi98/Web3_blockNumber_bug_report

This time i try deeply research about why i have this bug and found that it not from rpc API it from web3.provider
when i use web3 from Metamask it cannot return adjacent block number. But when i use web3 from import url by function `Web3.providers.HttpProvider` it's work

I am very interested in this error, so which folder can i check it in the web3 source. Hope I can make a pull request for this.
