### ISSUE TITLE
MaxListenersExceededWarning when sending contract (v1.0.0-beta.33)

### ISSUE THREAD

**Issue by jackno** [ethereum/web3.js#1648] opened 2018-05-22 02:58 UTC
**Situation**: When I send a deployed contract using `contract.deploy().send()`, the command line prints a warning:
```
  contracts
(node:23488) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit
    √ gets the accounts

  6 passing (1s)
```

_Edit (14 April 2020): removed unnecessary information_

**Comment by LuisOsta** [comment] 2018-07-04 18:11
I have the same issue, have you found a solution yet?

**Comment by nivida** [comment] 2018-08-10 06:25
@jackno Is this issue still there with beta-34?

**Comment by UnkySM** [comment] 2018-08-28 16:32
I've got the same issue with beta-35.

**Comment by dmutende** [comment] 2018-10-03 18:32
Same issue with wbe3@1.0.0-beta.35

**Comment by xpepermint** [comment] 2018-10-18 15:12
This problem relates to `ganache.provider()`. Here's a quick fix:
```
    const web3 = new Web3(ganache.provider({ ... }));
    web3.currentProvider.setMaxListeners(300); // or more :)
```

**Comment by adrianmcli** [comment] 2019-01-04 21:39
@xpepermint I dug into this a little bit with the Ganache team, and it seems that the problem is that every request in Web3.js seems to add on another listener on the same "data" event, instead of having a master listener.

**Comment by levino** [comment] 2019-02-08 08:38
Same problem here. @adrianmcli Could you be somewhat more specific please?

**Comment by nivida** [comment] 2019-02-08 09:35
This is a problem of the ganache provider and not one of the Web3.js library. Please open an issue there for solving it.

**Comment by levino** [comment] 2019-02-08 10:06
No it is a bug of `web3`. I encounter the problem when using metamask in the browser.

**Comment by eccentricexit** [comment] 2019-03-29 19:15
Same here.

**Comment by eggplantzzz** [comment] 2019-06-04 14:49
Is this still an issue for everyone or has a fix been made for this?

**Comment by adrianmcli** [comment] 2019-06-12 21:19
@eggplantzzz no fix still. The problem is with how Web3.js attaches listeners haphazardly. I haven't looked at this in a few months, but I recall that a new listener is attached every time a constructor of some object is created. But it should really just be a singleton that each instance refers to.

I know that's pretty vague, but that's the only recollection I have. I'll have to dig in to this again later this month. Or maybe someone else can.

**Comment by adrianmcli** [comment] 2019-06-12 22:08
Let's unpack this further, this is the stack trace I get when I enable `--trace-warnings` in node:

```
(node:49758) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:251:17)
    at Provider.addListener (events.js:267:10)
    at RequestManager.Object.<anonymous>.RequestManager.setProvider (/Users/adrianli/dev/drizzle-utils/node_modules/web3-eth/node_modules/web3-core-requestmanager/src/index.js:98:23)
    at Object.packageInit (/Users/adrianli/dev/drizzle-utils/node_modules/web3-eth/node_modules/web3-core/src/index.js:57:33)
    at Contract (/Users/adrianli/dev/drizzle-utils/node_modules/web3-eth/node_modules/web3-eth-contract/src/index.js:63:10)
    at new Contract (/Users/adrianli/dev/drizzle-utils/node_modules/web3-eth/src/index.js:148:22)
    at Contract.Object.<anonymous>.Contract.clone (/Users/adrianli/dev/drizzle-utils/node_modules/web3-eth/node_modules/web3-eth-contract/src/index.js:560:12)
    at Object.contractDeployFormatter (/Users/adrianli/dev/drizzle-utils/node_modules/web3-eth/node_modules/web3-eth-contract/src/index.js:878:57)
    at Object.callback (/Users/adrianli/dev/drizzle-utils/node_modules/web3-eth/node_modules/web3-core-method/src/index.js:323:70)
    at sendTxCallback (/Users/adrianli/dev/drizzle-utils/node_modules/web3-eth/node_modules/web3-core-method/src/index.js:487:29)
```

Do note that this is a project that is relying on Beta35, but I believe the cause is probably the same.

Whenever a new sendTx is created during deployment, `RequestManager.setProvider` is called, and each time new listeners are added (w/ `Provider.addListener`).

This also seems to happen when just creating new contract instances:

```
(node:49763) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:251:17)
    at Provider.addListener (events.js:267:10)
    at RequestManager.Object.<anonymous>.RequestManager.setProvider (/Users/adrianli/dev/drizzle-utils/node_modules/web3-eth/node_modules/web3-core-requestmanager/src/index.js:98:23)
    at Object.packageInit (/Users/adrianli/dev/drizzle-utils/node_modules/web3-eth/node_modules/web3-core/src/index.js:57:33)
    at Contract (/Users/adrianli/dev/drizzle-utils/node_modules/web3-eth/node_modules/web3-eth-contract/src/index.js:63:10)
    at new Contract (/Users/adrianli/dev/drizzle-utils/node_modules/web3-eth/src/index.js:148:22)
    at instanceFromArtifact (/Users/adrianli/dev/drizzle-utils/packages/get-contract-instance/instanceFromArtifact.js:559:27)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

The real question is why `setProvider` is getting called each time, and even if it is called, shouldn't it clean up listeners before adding? I haven't looked into the provider code yet.

**Comment by skozin** [comment] 2019-08-18 11:07
I'm also seeing the same memory leak generated by the second stack trace when creating multiple contract instances connected to the MetaMask's provider. It turns out that web3 v1.2.1 adds a new listener each time a new contract instance is created:

![image](https://user-images.githubusercontent.com/1699593/63223619-372c2680-c1c1-11e9-899c-8c151de35874.png)

Maybe this issue is worth to be reopened and investigated further? For our Dapp, this is a critical bug since we create a lot of contract instances through the lifetime of the application, and we cannot cache them.

A related issue in truffle: https://github.com/trufflesuite/truffle/issues/1942.

**Comment by adrianmcli** [comment] 2019-09-18 18:51
@nivida Can you re-open this issue? I think everyone is in agreement that this is not solved (and the problem is not with Ganache).

**Comment by gnidan** [comment] 2019-09-18 19:12
@nivida I hope I'm not overstepping -___-

"with great power comes great responsibility"?

**Comment by nivida** [comment] 2019-09-18 19:17
@gnidan Thanks for re-opening this issue. I had the same bug in the 2.x branch and already fixed it. We will fix it as soon as possible in the 1.x branch.

**Comment by wbt** [comment] 2020-04-14 19:16
FYI: When git cloning and building the latest version of web3 from the 1.x branch with #3190 merged, I still get the MaxListenersExceededWarning.

**Comment by cgewecke** [comment] 2020-04-14 19:32
@wbt We've seen this go away in our E2E tests but they are relatively modest in scope...what needs to be done to trigger the warning?

**Comment by wbt** [comment] 2020-04-14 19:35
@cgewecke Does https://github.com/trufflesuite/truffle/issues/1942 help?
To be clear, I'm seeing this in a more complex dapp, but the top post there was the result of spending the time to try to boil the issue down to a public test case.

**Comment by cgewecke** [comment] 2020-04-14 20:42
@wbt Ok yes I can reproduce with the test written #3469. Thanks for flagging this. 

From what I can see the problem is better than before but if you're calling `setProvider` repeatedly (e.g on lots of contract objects) it will hit the `10` limit.

**Comment by cgewecke** [comment] 2020-06-09 22:08
This is now [configurable][1]. If you're using Websockets and calling `contract.setProvider`, Web3 will attach four listeners. 

[1]: https://web3js.readthedocs.io/en/v1.2.9/web3-eth.html#maxlistenerswarningthreshold

**Closed by cgewecke** 2020-06-09 22:08 UTC
Labels: 1.x, bug, in progress
