### ISSUE TITLE
More helpful error message instead of Failed to subscribe to new newBlockHeaders

### ISSUE THREAD

**Issue by miohtama** [ethereum/web3.js#3498] opened 2020-05-04 22:32 UTC
#### Expected behavior

When `await web3.eth.send()` result, a timeout error gives a helpful error message. 

It could say, for example, 

`web3.js waited the transaction for the configured X seconds. However the transaction was not confirmed before the deadline. The transaction receipt waiting process was aborted, but the transaction might be still confirmed. If you wait for longer, you can configure X or connect web3.js using a WebSocket connection` 

Also, the thrown Error object could contain a special field so that the library consumer can easily check for this condition and gracefully handle this in the user interface.

#### Actual behavior

You get an error message `Failed to subscribe to new newBlockHeaders to confirm the transaction receipt`. 

This is strictly not true, as one would be able to confirm the error message if the default timeout 750 seconds is not reached.

#### Steps to reproduce the behavior

1. Have an Ethereum node with HTTPS connection and no support for newBlockHeaders, like Infura
2. Try to send a transaction with a WalletConnect enabled wallet like Trust Wallet or MetaMask Mobile
3. The default 750 seconds limit is often reached under the current Ethereum mainnet conditions and you will see this error in the console

#### Environment

- web3.js 1.2.4
- WalletConnect 1.0, 
- Trust wallet

**Comment by miohtama** [comment] 2020-05-12 10:15
For the added bonus, I would recommend adding a number of blocks or seconds the transaction was waiting before timing out in the error message.

**Comment by cgewecke** [comment] 2020-05-21 22:32
@miohtama 

Do you think this might be a variant of the bug described in #3432? As you note, your provider is `https` and it shouldn't be subscribing to anything. 

However, it's possible WalletConnect has its own EventEmitter-like interface which Web3 is getting confused by.

If so:
+ this bug should get fixed with #3517 
+ there is a work-around described in #3432 that might work for your case

**Comment by miohtama** [comment] 2020-05-26 12:59
99% of WalletConnect enabled websites are using Infura over HTTPS today, so I think that's where the issue comes from. 

Also the underlying issue is that web3.js tries to do too much itself - currently it is a black box how the waiting of a receipt works with `await`. I would be more brutal and just not do it at all in web3.js. Only support one interface like `on` and then let the clients do a polling loop with copy-paste code. This way clients have more control over the behavior and they do not need to run into web3.js internal issues which are difficult to solve and very opinionated.

**Comment by cgewecke** [comment] 2020-05-26 14:31
@miohtama Ok thanks. 

> they do not need to run into web3.js internal issues which are difficult to solve and very opinionated

Agree, the `web3-core-methods` module is probably the single thing most in need of rationalization / simplification in this project.

**Comment by cgewecke** [comment] 2020-05-28 19:31
@miohtama Are you comfortable with closing this as a duplicate of #3432?

**Comment by cgewecke** [comment] 2020-06-03 23:12
@miohtama `1.2.9-rc.0` is published with the patch that might fix this, if you're interested in experimenting with the timeout threshold.

**Comment by cgewecke** [comment] 2020-06-09 20:59
`1.2.9` (on the premise that it's a duplicate of #3432).

**Closed as completed by cgewecke** 2020-06-09 20:59 UTC
Labels: Bug, 1.x
