### ISSUE TITLE
Typescript doesnt work?

### ISSUE THREAD

**Issue by FrankBevr** [ethereum/web3.js#5076] opened 2022-05-25 22:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![web3Typescript](https://user-images.githubusercontent.com/30662393/170380013-19bcf6bf-1006-4f66-99e9-af10288137c2.gif)

**My index.js File** 
```js
const fs = require("fs");
  const Web3 = require("web3");

  let bytecode = fs.readFileSync("MyContract_sol_MyContract.bin").toString();
  let abi = JSON.parse(fs.readFileSync("MyContract_sol_MyContract.abi").toString());

  const init = async () => {
    let web3F = new Web3("http://localhost:9545");

    Contract = new web3F.eth.Contract(abi);

    await Contract.deploy({ data: bytecode }).send({ from: "0x818828046cb83fC759a1Ec0d96BD183E6c361ace", gas: 1500000, gasPrice: web3F.utils.toWei("0.00003", "ether"), }).then((newContractInstance) => { Contract.o

    await Contract.options.address;

    await Contract.methods.getData().call()

    await Contract.methods.setData(5).send({ from: '0x3625DAd830414f6F1051B6412c5d889CCb6999e2' }).then(console.log)

    await Contract.methods.getData().call().then(console.log)

    await Contract.methods.setData(10).send({ from: '0x9e04ec47ae5E6e23909e8C5AC47Ea29E905f0eC7' }).then(console.log)

    await Contract.methods.getData().call().then(console.log)
  }

  init()
```
**My indexTS.ts File** 
```ts
const fs = require("fs");
const Web3 = require("web3");

  let bytecode = fs.readFileSync("MyContract_sol_MyContract.bin").toString();
  let abi = JSON.parse(fs.readFileSync("MyContract_sol_MyContract.abi").toString());

  const init = async () => {
    let web3F = new Web3("http://localhost:9545");

    let Contract = new web3F.eth.Contract(abi);

    await Contract.deploy({ data: bytecode }).send({ from: "0x818828046cb83fC759a1Ec0d96BD183E6c361ace", gas: 1500000, gasPrice: web3F.utils.toWei("0.00003", "ether"), }).then((newContractInstance) => { Contract.o

    await Contract.options.address;

    await Contract.methods.getData().call();

    await Contract.methods.setData(5).send({ from: "0x3625DAd830414f6F1051B6412c5d889CCb6999e2" }).then(console.log);

    await Contract.methods.getData().call().then(console.log);

    await Contract.methods.setData(10).send({ from: "0x9e04ec47ae5E6e23909e8C5AC47Ea29E905f0eC7" }).then(console.log);

    await Contract.methods.getData().call().then(console.log);
  };

  init();
```

**My BugOutuput**
```sh
/home/frank/web3/node_modules/typescript/lib/typescript.js:42530
        ts.Debug.assert(typeof typeReferenceDirectiveName === "string", "Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.");
                 ^
Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
    at Object.resolveTypeReferenceDirective (/home/frank/web3/node_modules/typescript/lib/typescript.js:42530:18)
    at /mnt/c/Users/frank/AppData/Roaming/npm/node_modules/ts-node/src/resolver-functions.ts:131:51
    at Array.map (<anonymous>)
    at Object.resolveTypeReferenceDirectives (/mnt/c/Users/frank/AppData/Roaming/npm/node_modules/ts-node/src/resolver-functions.ts:130:31)
    at actualResolveTypeReferenceDirectiveNamesWorker (/home/frank/web3/node_modules/typescript/lib/typescript.js:116611:163)
    at resolveTypeReferenceDirectiveNamesWorker (/home/frank/web3/node_modules/typescript/lib/typescript.js:116911:26)
    at processTypeReferenceDirectives (/home/frank/web3/node_modules/typescript/lib/typescript.js:118393:31)
    at findSourceFileWorker (/home/frank/web3/node_modules/typescript/lib/typescript.js:118278:21)
    at findSourceFile (/home/frank/web3/node_modules/typescript/lib/typescript.js:118133:26)
    at /home/frank/web3/node_modules/typescript/lib/typescript.js:118085:85
```

### Expected Behavior

Should work like the index.js file, but why is this not the case?

### Steps to Reproduce

Write a solidty Contract
compile it with solc to a bin and abi

intitalize npm
install web3

write a small index.js file to interact with the contract
test it with node

write the same file but in typescript
test it with ts-node

Whats wrong? 🤔 

### Web3.js Version

1.7.3

### Environment

My package.json File 

```json
{
  "dependencies": {
    "web3": "^1.7.3"
  },
  "devDependencies": {
    "@types/web3": "^1.2.2",
    "@typescript-eslint/eslint-plugin": "^5.26.0",
    "@typescript-eslint/parser": "^5.26.0",
    "eslint": "^8.16.0"
  }
}
```

My tsconfig file

```json
{
    "compilerOptions": {
      "outDir": "./lib",
      "allowJs": true,
      "target": "esnext",
      "pretty": true,
      "module": "commonjs"
    }
}
```
My Solidity File
```sol
// SPDX-License-Identifier: UNLICENSED
  pragma solidity ^0.8;

  contract MyContract {
      uint data;

      function getData() external view returns (uint){
        return data;
      }
      function setData(uint _data) external{
        data = _data;
      }
      function setDataPrivate(uint _data) private{
        data = _data + 10;
      }
  }
```
Complied with 
`solcjs --bin --abi MyContract.sol`

### Anything Else?

It has to be something really simple. 
Because the whole setup is quite simple.
Maybe a change in the tsconfig file or something similar.

**Comment by nmaskens** [comment] 2022-05-26 12:15
The issue is Typescript. You are being punished for using Typescript

**Comment by CaiWenlie** [comment] 2022-05-26 13:11
same issue since today

**Comment by mayanksethisimpplr** [comment] 2022-05-26 13:29
Something similar is happening with me also
`**_Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature_**`

**Comment by adetorodev** [comment] 2022-05-26 16:31
I am having this issue too.

**Comment by adetorodev** [comment] 2022-05-26 16:32
Guys what's the way out

**Comment by JPDesignTech** [comment] 2022-05-26 19:53
> Guys what's the way out

I managed to deal with this by setting back my `ts-node` and `typescript` versions:  

```
  "ts-node": "~10.7.0",
  "typescript": "~4.6.4"
```

**Comment by FrankBevr** [comment] 2022-05-28 16:02
@jpere547 Thanks mate <3 

Now I am almost there, I just have to figure out how the hell to run `node` correctly after compling .ts to .js. (without ts-node)

any reccomendations? : )

*A gif of what works and what doesnt*
![almostThere](https://user-images.githubusercontent.com/30662393/170833202-081c0412-fa54-4bd3-aad9-9e8a9f030154.gif)

**Comment by ClaudioAdalbertoSilva** [comment] 2022-05-31 10:54
🤓  Hey guys!
This bug was resolved in my project by installing of:
"ts-node": "^10.8.0" on package.json ✅ 
I use the "typescript": "^4.7.2" in my project.
The TypeScript compiler API need an "compatible" PKG ts-node to running.
The PKG "ts-node" is a TypeScript execution and REPL (js Read-Eval-Print-Loop is an easy-to-use command-line tool, used for processing Node. js expressions) for node.js, with source map and native ESM (ECMAScript modules) support.

**Comment by justinduncan2010** [comment] 2022-06-02 15:51
You can remove the ^ in front of the version for typescript in the package.json so it doesn't fetch the latest version for now. Re-install and it should work fine

**Comment by gleisonkz** [comment] 2022-06-09 01:08
> > Guys what's the way out
> 
> I managed to deal with this by setting back my `ts-node` and `typescript` versions:
> 
> ```
>   "ts-node": "~10.7.0",
>   "typescript": "~4.6.4"
> ```

Thanks man, It works for me.

**Comment by nazarhussain** [comment] 2022-06-22 17:59
Hey @FrankBevr I tried to reproduce the issue here is the code I used. 


```js
{
  "name": "web3-test-tsc",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "typescript": "^4.7.4",
    "web3": "^1.7.4"
  },
  "devDependencies": {
    "@types/node": "^18.0.0",
    "ts-node": "^10.8.1"
  }
}
```

Here is the script. 

```ts
const Web3 = require("web3");

const GreeterAbi = [
  {
    inputs: [{ internalType: "string", name: "_greeting", type: "string" }],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "greeting",
        type: "string",
      },
    ],
    name: "GREETING_CHANGED",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "string", name: "from", type: "string" },
      { indexed: false, internalType: "string", name: "to", type: "string" },
    ],
    name: "GREETING_CHANGING",
    type: "event",
  },
  {
    inputs: [],
    name: "greet",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "_greeting", type: "string" }],
    name: "setGreeting",
    outputs: [
      { internalType: "bool", name: "", type: "bool" },
      { internalType: "string", name: "", type: "string" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
const GreeterBytecode =
  "0x60806040523480156200001157600080fd5b5060405162000a6a38038062000a6a8339818101604052810190620000379190620002a4565b80600090805190602001906200004f92919062000057565b505062000359565b828054620000659062000324565b90600052602060002090601f016020900481019282620000895760008555620000d5565b82601f10620000a457805160ff1916838001178555620000d5565b82800160010185558215620000d5579182015b82811115620000d4578251825591602001919060010190620000b7565b5b509050620000e49190620000e8565b5090565b5b8082111562000103576000816000905550600101620000e9565b5090565b6000604051905090565b600080fd5b600080fd5b600080fd5b600080fd5b6000601f19601f8301169050919050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052604160045260246000fd5b620001708262000125565b810181811067ffffffffffffffff8211171562000192576200019162000136565b5b80604052505050565b6000620001a762000107565b9050620001b5828262000165565b919050565b600067ffffffffffffffff821115620001d857620001d762000136565b5b620001e38262000125565b9050602081019050919050565b60005b8381101562000210578082015181840152602081019050620001f3565b8381111562000220576000848401525b50505050565b60006200023d6200023784620001ba565b6200019b565b9050828152602081018484840111156200025c576200025b62000120565b5b62000269848285620001f0565b509392505050565b600082601f8301126200028957620002886200011b565b5b81516200029b84826020860162000226565b91505092915050565b600060208284031215620002bd57620002bc62000111565b5b600082015167ffffffffffffffff811115620002de57620002dd62000116565b5b620002ec8482850162000271565b91505092915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052602260045260246000fd5b600060028204905060018216806200033d57607f821691505b602082108103620003535762000352620002f5565b5b50919050565b61070180620003696000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063a41368621461003b578063cfae32171461006c575b600080fd5b6100556004803603810190610050919061043f565b61008a565b60405161006392919061052b565b60405180910390f35b6100746101b0565b604051610081919061055b565b60405180910390f35b600060607f0d363f2fba46ab11b6db8da0125b0d5484787c44e265b48810735998bab12b756000846040516100c0929190610672565b60405180910390a182600090805190602001906100de929190610242565b507f7d7846723bda52976e0286c6efffee937ee9f76817a867ec70531ad29fb1fc0e600060405161010f91906106a9565b60405180910390a160016000808054610127906105ac565b80601f0160208091040260200160405190810160405280929190818152602001828054610153906105ac565b80156101a05780601f10610175576101008083540402835291602001916101a0565b820191906000526020600020905b81548152906001019060200180831161018357829003601f168201915b5050505050905091509150915091565b6060600080546101bf906105ac565b80601f01602080910402602001604051908101604052809291908181526020018280546101eb906105ac565b80156102385780601f1061020d57610100808354040283529160200191610238565b820191906000526020600020905b81548152906001019060200180831161021b57829003601f168201915b5050505050905090565b82805461024e906105ac565b90600052602060002090601f01602090048101928261027057600085556102b7565b82601f1061028957805160ff19168380011785556102b7565b828001600101855582156102b7579182015b828111156102b657825182559160200191906001019061029b565b5b5090506102c491906102c8565b5090565b5b808211156102e15760008160009055506001016102c9565b5090565b6000604051905090565b600080fd5b600080fd5b600080fd5b600080fd5b6000601f19601f8301169050919050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052604160045260246000fd5b61034c82610303565b810181811067ffffffffffffffff8211171561036b5761036a610314565b5b80604052505050565b600061037e6102e5565b905061038a8282610343565b919050565b600067ffffffffffffffff8211156103aa576103a9610314565b5b6103b382610303565b9050602081019050919050565b82818337600083830152505050565b60006103e26103dd8461038f565b610374565b9050828152602081018484840111156103fe576103fd6102fe565b5b6104098482856103c0565b509392505050565b600082601f830112610426576104256102f9565b5b81356104368482602086016103cf565b91505092915050565b600060208284031215610455576104546102ef565b5b600082013567ffffffffffffffff811115610473576104726102f4565b5b61047f84828501610411565b91505092915050565b60008115159050919050565b61049d81610488565b82525050565b600081519050919050565b600082825260208201905092915050565b60005b838110156104dd5780820151818401526020810190506104c2565b838111156104ec576000848401525b50505050565b60006104fd826104a3565b61050781856104ae565b93506105178185602086016104bf565b61052081610303565b840191505092915050565b60006040820190506105406000830185610494565b818103602083015261055281846104f2565b90509392505050565b6000602082019050818103600083015261057581846104f2565b905092915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052602260045260246000fd5b600060028204905060018216806105c457607f821691505b6020821081036105d7576105d661057d565b5b50919050565b60008190508160005260206000209050919050565b600081546105ff816105ac565b61060981866104ae565b94506001821660008114610624576001811461063657610669565b60ff1983168652602086019350610669565b61063f856105dd565b60005b8381101561066157815481890152600182019150602081019050610642565b808801955050505b50505092915050565b6000604082019050818103600083015261068c81856105f2565b905081810360208301526106a081846104f2565b90509392505050565b600060208201905081810360008301526106c381846105f2565b90509291505056fea26469706673582212203746baed62e6fd543d947eb69460c5abf2eef8b85afff65b442695d4abaaebbc64736f6c634300080d0033";

const init = async () => {
  let web3F = new Web3("http://127.0.0.1:8545");

  let Contract = new web3F.eth.Contract(GreeterAbi);

  await Contract.deploy({ data: GreeterBytecode, arguments: ['My Message'] })
    .send({
      from: "0x6E599DA0bfF7A6598AC1224E4985430Bf16458a4",
      gas: 1500000,
      gasPrice: web3F.utils.toWei("0.00003", "ether"),
    })
    .then((newContractInstance: any) => {
      Contract = newContractInstance;
    });

  await Contract.options.address;

  await Contract.methods.greet().call().then(console.log);

  await Contract.methods
    .setGreeting('new Greeting')
    .send({ from: "0x6E599DA0bfF7A6598AC1224E4985430Bf16458a4" })
    .then(console.log);

  await Contract.methods.greet().call().then(console.log);
};

init();
```

It executed well with the `ts-node`: 

```
> npx ts-node index.ts
My Message
{
  transactionHash: '0x7f6d347f85653a6f8789604e9d44892ac8583c736fccb9036ff470ed803708f3',
  transactionIndex: 0,
  blockNumber: 3,
  blockHash: '0xac3e92a5057b3781e5f60819a5ce907bdff61554d7772595f614a19626486604',
  from: '0x6e599da0bff7a6598ac1224e4985430bf16458a4',
  to: '0x2330132c97ded051e5301ed73ecb3c67e0e6ec80',
  cumulativeGasUsed: 37000,
  gasUsed: 37000,
  contractAddress: null,
  logsBloom: '0x00000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000100800000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000',
  status: true,
  effectiveGasPrice: 3175998886,
  type: '0x2',
  events: {
    GREETING_CHANGING: {
      address: '0x2330132C97DEd051e5301eD73ECB3C67E0E6eC80',
      blockHash: '0xac3e92a5057b3781e5f60819a5ce907bdff61554d7772595f614a19626486604',
      blockNumber: 3,
      logIndex: 0,
      removed: false,
      transactionHash: '0x7f6d347f85653a6f8789604e9d44892ac8583c736fccb9036ff470ed803708f3',
      transactionIndex: 0,
      id: 'log_bd06ddb2',
      returnValues: [Result],
      event: 'GREETING_CHANGING',
      signature: '0x0d363f2fba46ab11b6db8da0125b0d5484787c44e265b48810735998bab12b75',
      raw: [Object]
    },
    GREETING_CHANGED: {
      address: '0x2330132C97DEd051e5301eD73ECB3C67E0E6eC80',
      blockHash: '0xac3e92a5057b3781e5f60819a5ce907bdff61554d7772595f614a19626486604',
      blockNumber: 3,
      logIndex: 1,
      removed: false,
      transactionHash: '0x7f6d347f85653a6f8789604e9d44892ac8583c736fccb9036ff470ed803708f3',
      transactionIndex: 0,
      id: 'log_0fff258e',
      returnValues: [Result],
      event: 'GREETING_CHANGED',
      signature: '0x7d7846723bda52976e0286c6efffee937ee9f76817a867ec70531ad29fb1fc0e',
      raw: [Object]
    }
  }
}
new Greeting
```

Also works fine with the nodejs. 

```
> npx tsc index.ts 
> node index.js
My Message
{
  transactionHash: '0x34aa60c0ba6a6a4438b8a0f49cbae1de60feea8f54ef1cdd73c23071090c727b',
  transactionIndex: 0,
  blockNumber: 5,
  blockHash: '0x9ad749ce64d73cc8e270851bb3565dba63463454bf2c29e92e183e2a7b43cba5',
  from: '0x6e599da0bff7a6598ac1224e4985430bf16458a4',
  to: '0x9679d28196a3a8167c371685fc408e80a44486bf',
  cumulativeGasUsed: 37000,
  gasUsed: 37000,
  contractAddress: null,
  logsBloom: '0x00000000000000000000001080000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000801000000000000000000000000000000000000000000000000000000000000000040000200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  status: true,
  effectiveGasPrice: 3020087011,
  type: '0x2',
  events: {
    GREETING_CHANGING: {
      address: '0x9679d28196a3A8167c371685fC408E80A44486bF',
      blockHash: '0x9ad749ce64d73cc8e270851bb3565dba63463454bf2c29e92e183e2a7b43cba5',
      blockNumber: 5,
      logIndex: 0,
      removed: false,
      transactionHash: '0x34aa60c0ba6a6a4438b8a0f49cbae1de60feea8f54ef1cdd73c23071090c727b',
      transactionIndex: 0,
      id: 'log_23dc15d9',
      returnValues: [Result],
      event: 'GREETING_CHANGING',
      signature: '0x0d363f2fba46ab11b6db8da0125b0d5484787c44e265b48810735998bab12b75',
      raw: [Object]
    },
    GREETING_CHANGED: {
      address: '0x9679d28196a3A8167c371685fC408E80A44486bF',
      blockHash: '0x9ad749ce64d73cc8e270851bb3565dba63463454bf2c29e92e183e2a7b43cba5',
      blockNumber: 5,
      logIndex: 1,
      removed: false,
      transactionHash: '0x34aa60c0ba6a6a4438b8a0f49cbae1de60feea8f54ef1cdd73c23071090c727b',
      transactionIndex: 0,
      id: 'log_c7cc17ad',
      returnValues: [Result],
      event: 'GREETING_CHANGED',
      signature: '0x7d7846723bda52976e0286c6efffee937ee9f76817a867ec70531ad29fb1fc0e',
      raw: [Object]
    }
  }
}
new Greeting
```

You can try out with the above given scripts. It seems the issue is with your typescript setup somehow. I am closing this issue for now, if you still face the issue please create a Github repo which have this issue reproducible and reopen the issue.

**Closed as completed by nazarhussain** 2022-06-22 17:59 UTC
Labels: Bug

**Comment by AF2B** [comment] 2022-07-05 17:33
> > Guys what's the way out
> 
> I managed to deal with this by setting back my `ts-node` and `typescript` versions:
> 
> ```
>   "ts-node": "~10.7.0",
>   "typescript": "~4.6.4"
> ```

Works for me! Thank you so much.

**Comment by Stazyu** [comment] 2022-07-16 02:18
> > Guys what's the way out
> 
> I managed to deal with this by setting back my `ts-node` and `typescript` versions:
> 
> ```
>   "ts-node": "~10.7.0",
>   "typescript": "~4.6.4"
> ```

Thanks.. Work for Me!

**Comment by shubasishdas** [comment] 2022-07-26 19:28
> > Guys what's the way out
> 
> I managed to deal with this by setting back my `ts-node` and `typescript` versions:
> 
> ```
>   "ts-node": "~10.7.0",
>   "typescript": "~4.6.4"
> ```

Thanks. This one works for me!
