### ISSUE TITLE
'request.withCredentials = true' breaks CORS

### ISSUE THREAD

**Issue by tomw1808** [ethereum/web3.js#1802] opened 2018-07-27 13:04 UTC
The latest change in httpprovider breaks CORS with ganache and possibly other tools (for me at least), where the CORS-domain cannot be set explicitly.

Chrome comes up with the following error message: "Failed to load http://localhost:7545/: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'null' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute."

Reproduce this issue by using the web3 0.20, e.g. "npm install web3@0.20" and then a simple index.html with the most simplistic content opening in Chrome:
```
<!doctype html>

<html>

<head>
  <script src="node_modules/web3/dist/web3.js" type="text/javascript"></script>
</head>

<body>

  <div>Here is some content.</div>


  <script>
    var web3;
    if (typeof web3 !== 'undefined') {
      web3 = new Web3(web3.currentProvider);
    } else {
      // set the provider you want from Web3.providers
      web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:7545"));
    }

  </script>
</body>

</html>
```

Anything I can do on my side?

https://github.com/ethereum/web3.js/blob/b4c1542ddb5284267f6814ba0106bfbbc83fe166/lib/web3/httpprovider.js#L66

**Comment by nomoreboredom** [comment] 2018-07-27 14:13
I am also experiencing this after migrating to version 35, following.

**Comment by H34D** [comment] 2018-08-02 12:36
i can confirm this, after downgrading to 0.20.6 it worked again.

**Comment by pierreneter** [comment] 2018-08-07 11:42
Related to #1803

**Comment by angelina999990** [comment] 2018-08-09 09:53
Encountered the same issue which says 'The value of the 'Access-Control-Allow-Credentials must be true'.  I'm using web3.js@0.20.7

**Comment by angelina999990** [comment] 2018-08-09 09:56
after downgrading to 0.20.6 it worked again. It works as well

**Comment by tradzero** [comment] 2018-08-15 06:59
i found safari will add `user-agent` to `Access-Control-Request-Headers`, and infura will reject this request. but i dont know how to remove that

**Comment by edwardfxiao** [comment] 2018-08-15 08:47
@tradzero  downgrade to v1.0.0-beta.33 solved my problem

**Comment by levity** [comment] 2018-08-30 00:19
For users of v1.0.0-beta, downgrading to v1.0.0-beta.34 will also work, because the issue was introduced after it, in [this commit](https://github.com/ethereum/web3.js/commit/f98fe1462625a6c865125fecc9cb6b414f0a5e83#diff-191801bd560e900fbb857aaa11c02aa6R45).

I had to downgrade in order to use HttpProvider with Infura. Probably the longer-term solution is to allow `withCredentials` to be turned off by an option in the constructor arguments.

**Comment by 0xclem** [comment] 2018-09-17 02:12
I can confirm that downgrading to v1.0.0-beta.34 fixes the issue. Both Safari and Firefox were impacted.

**Comment by karlphillip** [comment] 2018-10-04 00:27
What is the correct command to downgrade to that specific version?

**Comment by 0xclem** [comment] 2018-10-04 00:34
@karlphillip something like `yarn remove web3 && yarn add web3@1.0.0-beta.34` should work.

**Comment by karlphillip** [comment] 2018-10-04 00:48
Thank you, ended up going with:
npm install web3@0.20.6 --save

**Comment by therightstuff** [comment] 2018-10-04 05:49
https://github.com/ethereum/web3.js/pull/1956 resolves this by removing the credential requirement when there's no user / password supplied, 

@frozeman @nivida this seems to be an issue for quite a lot of people, is there another way to work around this or do you have any comments for the PR?

**Comment by Snehasispanigrahi** [comment] 2018-11-29 09:22
My web3 version is 0.20.6. And throws this CORS issue: Access to XMLHttpRequest at 'http://localhost:8545/' from origin 'http://127.0.0.1:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

**Comment by jamesmorgan** [comment] 2019-01-05 07:07
Any ideas on how to solve this - I find it works in most browsers but safari?

**Comment by aratakokubun** [comment] 2019-01-05 07:44
I have the same issue and can not resolve with Chrome, FireFox and Safari...

**Comment by todorone** [comment] 2019-01-28 08:54
Unfortunately this is a blocking issue, so all versions above `beta.34` are unavailable for React Native platform due to it's cookies headers resulting this error:

<img width="359" alt="screen shot 2019-01-28 at 10 49 11 am" src="https://user-images.githubusercontent.com/423701/51824357-ace6a880-22ea-11e9-85f3-dcca7f1de6cf.png">

Can somebody proficient suggest any temporary workaround until this issue is resolved? Thanks.
@nivida @tomw1808

**Comment by barrard** [comment] 2019-03-21 08:14
Im getting this error also :(
`Fetch API cannot load https://rinkeby.infura.io/v3/xxxxxxxx due to access control checks.`

**Comment by nivida** [comment] 2019-03-25 15:29
This got fixed with PR #2564 and will be released this week.

**Closed as completed by nivida** 2019-03-25 15:29 UTC
Labels: Bug

**Comment by vanchinathans-git** [comment] 2019-04-26 12:11
> I can confirm that downgrading to v1.0.0-beta.34 fixes the issue. Both Safari and Firefox were impacted.

Thank you so much. It saved my day.

**Comment by glowkeeper** [comment] 2019-10-15 12:41
I _think_ I'm seeing the same issue on a MAC build of [Clickz Latest](https://cliqz.com/en/latest), which is trying to run the following `dat`:

dat://795f83fa1356cd7d00e5cfe8f1a93f32c55127684c6fc4cb8ff89a32e000016b

That is a frontend to some contracts running on the Ethereum Rinkeby Test Network, so it relies on [MetaMask](https://metamask.io) to inject a [web3.js](https://github.com/ethereum/web3.js/) instance that points to Rinkeby. Unfortunately, no matter what I do with MetaMask, my app' thinks it's on the Ropsten network, and I get these errors:

````
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:8545/. (Reason: CORS request did not succeed).
````
I'm assuming that the reference to `http://127.0.0.1:8545/` comes from web3.js, since it is not mentioned anywhere else in my code.

Interestingly, the very same `dat` works seamlessly on vanilla Firefox with the [dat P2P protocol](https://addons.mozilla.org/en-GB/firefox/addon/dat-p2p-protocol/) extension installed.

Meanwhile, what to do concerning that error using [Clickz Latest](https://cliqz.com/en/latest)? I've seen some possibilities involving `XMLHttpRequest`, but I can't find any docs as to how to use that when setting my web3 provider. Would it help?

**Comment by nivida** [comment] 2019-10-15 12:47
@glowkeeper This got fixed with https://github.com/ethereum/web3.js/pull/3112 and will be released with 1.2.2.

**Comment by glowkeeper** [comment] 2019-10-15 13:35
Awesome! When is 1.2.2 due for release?

**Comment by 0xZick** [comment] 2019-10-18 03:19
@nivida When is 1.2.2 due for release ?)

**Comment by glowkeeper** [comment] 2019-10-19 10:00
@nivida - I appreciate you're probably busy, but I'm trying to work out project plans for some of my dApps, and that 1.2.2 upgrade has become an important ingredient of those plans. Any news on release dates?

**Comment by nivida** [comment] 2019-10-19 10:45
The release is planned for Monday. I will do the last tests and improvements over the weekend and will release it in the late afternoon on Monday (CEST)

**Comment by glowkeeper** [comment] 2019-10-19 11:01
Brilliant - thanks, @nivida

**Comment by glowkeeper** [comment] 2019-10-23 11:28
Problems?

**Comment by glowkeeper** [comment] 2019-10-23 15:58
Oooo - just seen the new version - awesome - thanks @nivida!
