### ISSUE TITLE
Enable ganache for system tests to forge the block on regular interval

### ISSUE THREAD

**Issue by nazarhussain** [ethereum/web3.js#4981] opened 2022-04-26 17:15 UTC
It [looks](https://github.com/trufflesuite/ganache/blob/90329d886cf05df409a9474edc4e15f653c2d5b4/src/packages/ganache/README.md?plain=1#L285) like we'd need to pass `-b 1` which would mine a block every 1 second

_Originally posted by @spacesailor24 in https://github.com/ChainSafe/web3.js/pull/4945#discussion_r858964766_

**Comment by mconnelly8** [comment] 2022-05-31 15:47
Tests are already done, but need to revisit tests.

**Comment by mconnelly8** [comment] 2022-07-27 17:47
Need to investigate scenarios based on node configurations

**Comment by mconnelly8** [comment] 2022-12-12 22:18
Duplicate of #5297, so will close this one.

**Closed as completed by mconnelly8** 2022-12-12 22:18 UTC
Labels: Discussion, 4.x
