### ISSUE TITLE
Error: ENS is not supported on network private

### ISSUE THREAD

**Issue by shenhaoguangDayDayUp** [ethereum/web3.js#4627] opened 2021-12-14 03:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/17617821/145930060-9f075ffc-698f-4e58-934b-4cf26fb86e0c.png)

### Expected Behavior

no error

### Steps to Reproduce

```js
export const web3Connect = () => async (dispatch, getState) => {
  //@ts-ignore
  if (typeof window.ethereum === "undefined") {
    //没安装MetaMask钱包进行弹框提示
    return;
  }
  const { web3Reducer, netWorkId } = getState();

  let addresses = await web3.eth.getAccounts();
  if (!addresses.length) {
    addresses = await (window as any).ethereum.enable();
  }
  let chainId = (await web3.eth.getChainId()) || 56; // 币安链

  console.log(web3Reducer.contractAddresses);

  try {
    await dispatch(swichNetWork(chainId));
    await dispatch({
      type: WEB3_CONNECTED,
      payload: {
        web3,
        chainId: chainId,
        account: addresses,
        loading: false,
        walletConnect: true,
        contractAddresses,
      },
    });
    dispatch(web3ConnectChange(true));
  } catch (error) {
    dispatch(web3ConnectChange(false));
  }
export const swichNetWork = (chainId) => async (dispatch, getState) => {
  //@ts-ignore
  const tx = await ethereum.request({
    method: "wallet_switchEthereumChain",
    params: [{ chainId: netWorkId }],
  });
};


```

### Web3.js Version

1.61

### Environment

- Operating System: Mac
- Browser: chome
- Node.js Version: v14.17.6
- NPM Version: 6.14.15

**Comment by nazarhussain** [comment] 2021-12-17 14:33
Hi @shenhaoguangDayDayUp Thanks for reaching out to us. I looked into the code you shared, seems like React or Redux code. Unfortunately I can't execute that code right away to debug it further. It would be so nice if you can share a reproducible script that we can run on our end without dependencies to reproduce the issue.

**Comment by fodisi** [comment] 2022-01-02 20:09
Hello folks, thanks for checking this issue.

I'm also experiencing this issue in a Node/NestJS service where I'm using web3 (v1.6.1 - also tried w/ 1.5.2 and 1.2.11 but got the same error).
The project doesn't make any calls ENS at all (no calls to ens functions), only web3 (pretty much create a web3 instance, and instantiate a few contracts, without ENS integration). However, a few moments after web3 is instantiated (using a RPC for Polygon or Celo), the service throws this error.

Error happens on `node_modules/web3-eth-ens/lib/ENS.js:482:19`.
Error message: `UnhandledPromiseRejectionWarning: Error: ENS is not supported on network private`

I'm not really sure what's happening, but looks like that by simply creating a web3 instance, the ens package is required, which in result calls `checkNetwork` function and then throws the exception asynchronously.

**Comment by nazarhussain** [comment] 2022-01-06 16:52
@fodisi @shenhaoguangDayDayUp 

This is very strange behavior. The error `ENS is not supported on network` is only been thrown from `checkNetwork` and that function is not invoked by the library itself. 

Certainly some upper layer is invoking that function. Are you sure there is no other library or code which you are injecting with web3, that may be invoking that function. 

@fodisi Can you try to create an empty npm package with only dependency of `web3` and see the problem persists.

**Comment by nazarhussain** [comment] 2022-01-21 10:38
@fodisi Were you able to reproduce this error with only `web3` dependency in the package?

**Comment by mrguamos** [comment] 2022-02-06 16:02
this happens when you use state management like Redux and I don't know the reason why lol
in vue you can use something like [markRaw](https://vuejs.org/api/reactivity-advanced.html#markraw) when using state management

_Marks an object so that it will never be converted to a proxy. Returns the object itself._

**Comment by nazarhussain** [comment] 2022-02-09 12:37
@mrguamos I am not sure, but it looks the state management is creating new objects for the web3. 

I am closing this issue, as this error does not directly relates to `web3` library. If we get more context we can reopen the issue.

**Closed as completed by nazarhussain** 2022-02-09 12:37 UTC
Labels: Bug, Needs Clarification

**Comment by rosnaib11** [comment] 2022-02-13 17:36
This happened to me when I use redux toolkit createAsyncThunk I don't know why so I just used different approach

**Comment by Hamza141999** [comment] 2022-07-26 10:17
@nazarhussain having the same issue here. I'm using useReducer and ContextAPI for global state management, and whenever I connect using web3modal, i'm given this error: Error: ENS is not supported on network private
    at ENS.checkNetwork
Can anyone please look into this? I'm not making any sort of ens.checkNetwork or networkType call in my code, its just merely a contract call after I connect my wallet

**Comment by Yinboan** [comment] 2022-10-02 10:39
> @nazarhussain having the same issue here. I'm using useReducer and ContextAPI for global state management, and whenever I connect using web3modal, i'm given this error: Error: ENS is not supported on network private at ENS.checkNetwork Can anyone please look into this? I'm not making any sort of ens.checkNetwork or networkType call in my code, its just merely a contract call after I connect my wallet

I also had this problem, but it's weird that it only triggers when I have the redux toolkit open

**Comment by mrguamos** [comment] 2022-10-02 11:08
> > @nazarhussain having the same issue here. I'm using useReducer and ContextAPI for global state management, and whenever I connect using web3modal, i'm given this error: Error: ENS is not supported on network private at ENS.checkNetwork Can anyone please look into this? I'm not making any sort of ens.checkNetwork or networkType call in my code, its just merely a contract call after I connect my wallet
> 
> I also had this problem, but it's weird that it only triggers when I have the redux toolkit open

I'm not familiar with redux but can you try using this?
https://redux-toolkit.js.org/api/other-exports#original

**Comment by Jsherborne92** [comment] 2023-03-17 15:17
No Ens calls, react context api same issue here.

**Comment by cryptolit0** [comment] 2024-08-04 00:24
i get this on svelte but only when dynamically importing the web3 library 1.xx
