### ISSUE TITLE
Nonce value is same when using two instance for two chains

### ISSUE THREAD

**Issue by ujjwalguptaofficial** [ethereum/web3.js#4500] opened 2021-10-26 06:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If i have two web3js instance with two different chains and i call `getTransactionCount` then value is being copied from first call.

```
const web3Parent = new Web3(new HDWalletProvider(privateKey, rpc.parent))
 const web3Child = new Web3(new HDWalletProvider(privateKey, rpc.child))



 const nonceChild = await web3Child.eth.getTransactionCount(from, 'pending');
  console.log('nonce', nonceChild); //11840

  const nonceParent = await web3Parent.eth.getTransactionCount(from, 'pending');
  console.log('nonce', nonceParent); // 11840

```

If i call `getTransactionCount` on parent first then value from parent will be returned in child. 

### Expected Behavior

value should be different on each chain. 

> i guess this is because of caching somewhere

### Steps to Reproduce

```
 const web3Parent = new Web3(new HDWalletProvider(privateKey, rpc.parent))
  const web3Child = new Web3(new HDWalletProvider(privateKey, rpc.child))



  let nonce = await web3Child.eth.getTransactionCount(from, 'pending');
  console.log('nonce', nonce);

  nonce = await web3Parent.eth.getTransactionCount(from, 'pending');
  console.log('nonce', nonce);
```

Here is reproducible repo - https://github.com/ujjwalguptaofficial/web3-nonce-issue

### Web3.js Version

1.6.0

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version:

**Comment by ujjwalguptaofficial** [comment] 2021-10-26 07:09
have created a reproducible repo - https://github.com/ujjwalguptaofficial/web3-nonce-issue

**Comment by Spacesai1or** [comment] 2021-12-10 17:07
@ujjwalguptaofficial Just wanted to let you know that I'm starting work on this now, apologies that it's been pending for so long

Thank you for bringing this to our attention, and thank you especially for taking the time to make a reproducible repo!

**Comment by Spacesai1or** [comment] 2021-12-10 18:00
In my testing, this bug only seems to appear when both requests are sent with `pending` block tag e.g.:

```typescript
web3.eth.getTransactionCount(from, 'pending');
web3.eth.getTransactionCount(from2, 'pending');
```

Yields duplicate count from first request

```typescript
web3.eth.getTransactionCount(from, 'pending');
web3.eth.getTransactionCount(from2, 'latest'); // This could be anything besides 'pending', also order of calls doesn't matter
```

Yields correct respective counts

**Comment by Spacesai1or** [comment] 2021-12-11 23:30
This seems to be an issue with `Web3` being instantiated with multiple times with `@truffle/hdwallet-provider`

Instantiating two instance like so:

```typescript
const web3Parent = new Web3(rpc.parent)
const web3Child = new Web3(rpc.child)
```

Yields the correct result

**Comment by Spacesai1or** [comment] 2021-12-12 00:56
@ujjwalguptaofficial I can't provide you more information on this (can't seem to find an issue in Truffle repo for it, even though there's [a comment](https://github.com/trufflesuite/truffle/blob/develop/packages/hdwallet-provider/src/index.ts#L41) about it), but it seems setting the option `shareNonce` to `false` will fix this issue:

```typescript
const web3Parent = new Web3(new HDWalletProvider(
        privateKey,
        rpc.parent,
        0, // addressIndex
        1, // numberOfAddresses
        false //shareNonce
))
const web3Child = new Web3(new HDWalletProvider(privateKey, rpc.child))
```

For readability sake, this can be written as:

```typescript
const web3Parent = new Web3(new HDWalletProvider({
        privateKeys: [privateKey],
        providerOrUrl: rpc.parent,
        shareNonce: false
}))
const web3Child = new Web3(new HDWalletProvider(privateKey, rpc.child))
```

Both of the above will result in the correct nonces being returned

I'm going to close this issue as it's not related to Web3.js

**Closed as completed by Spacesai1or** 2021-12-12 00:56 UTC
Labels: Bug, 1.x, Investigate

**Comment by ujjwalguptaofficial** [comment] 2021-12-14 03:02
thanks @spacesailor24 :)
