### ISSUE TITLE
web3.eth.getTransactionReceipt Returning Incorrect Type for `status`

### ISSUE THREAD

**Issue by seesemichaelj** [ethereum/web3.js#1657] opened 2018-05-24 16:26 UTC
Per the [JSON-RPC spec](https://github.com/ethereum/wiki/wiki/JSON-RPC#returns-31): `status: QUANTITY either 1 (success) or 0 (failure).` Looking a little further down, we can see an [example](https://github.com/ethereum/wiki/wiki/JSON-RPC#example-31): `status: '0x1'`

My interpretation of the spec says that `status` should be type `string` represented as a `hexadecimal` number with either `0x1` (success) or `0x0` (failure).

However, per the [docs](http://web3js.readthedocs.io/en/1.0/web3-eth.html#eth-gettransactionreceipt-return), [code](https://github.com/ethereum/web3.js/blob/1271b7b37f4a68b6ba2276c2e4d39593a3bbf753/packages/web3-core-helpers/src/formatters.js#L219-L221), and real results (on `1.0.0-beta34`), `web3` is returning a `boolean`.

I'm now part of the Truffle team, and https://github.com/trufflesuite/ganache-core is failing tests because of the unexpected `boolean` type.

I'm happy to submit a PR with the appropriate fixes! Thanks!

**Comment by Levino** [comment] 2018-05-28 14:36
I suggest you open a PR with a test that is failing because of what you are saying. Would be most easy to reproduce locally then.

**Comment by seesemichaelj** [comment] 2018-06-14 17:49
I'm not sure if a PR will change much other than pushing this issue from a pool of 471 issues to a pool of 34 pull requests. It's not really about reproducible in the scope of this repo as the test would just merely test for an unformatted status field.

Unfortunately, this just comes down to discussing with the maintainers about why the field is being formatted to a `boolean` rather than a hex string specified by the JSON-RPC spec. :/

**Comment by mikeseese** [comment] 2018-08-28 21:17
@nivida I see that you got assigned this. I just wanted to touch base about what the approach might be for this?

**Comment by nivida** [comment] 2019-03-20 12:03
This got fixed in version beta.48. Please update to the latest version. (beta.50)

**Closed by nivida** 2019-03-20 12:03 UTC
Labels: bug
