### ISSUE TITLE
/node_modules/web3-core-helpers/lib/errors.js:28

### ISSUE THREAD

**Issue by Park6102** [ethereum/web3.js#6124] opened 2023-05-26 19:57 UTC
■Version
"web3": "^1.10.0",

■Error Code (nodejs script quits forcefully)
/mnt/c/web3/node_modules/web3-core-helpers/lib/errors.js:28
        var err = new Error('Returned error: ' + message);
                  ^

Error: Returned error: we can't execute this request
    at Object.ErrorResponse (/mnt/c/web3/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /mnt/c/web3/node_modules/web3-core-requestmanager/lib/index.js:300:36
    at /mnt/c/web3/node_modules/web3-providers-http/lib/index.js:127:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  data: null
}

■My code
const Web3 = require('web3');
const web3 = new Web3(new Web3.providers.HttpProvider(url));

const routerContract = new web3.eth.Contract(routerABI, routerAddress);
const expiryDate = Math.floor(Date.now() / 1000) + 900;
const privateKey = process.env.WALLET_SECRET;
const activeAccount = web3.eth.accounts.privateKeyToAccount(privateKey);

encodedTx = routerContract.methods.exactInputSingle(params).encodeABI();
transactionObject = {
  gas: 4389890,
  data: encodedTx,
  from: activeAccount.address,
  to: routerAddress
};

web3.eth.accounts.signTransaction(transactionObject, privateKey, (error, signedTx) => {
  if (error)
  {
    console.log(error);
  }
  else
  {
    web3.eth.sendSignedTransaction(signedTx.rawTransaction)
    .once('transactionHash', function(hash)
    {
      console.log("txHash: ", hash)
    })
    .on('error', function(error){ console.log("error: ", error) })
    .on('confirmation', function(confNumber, result)
    {
      console.log(result);
    })
  }
});

**Comment by jdevcs** [comment] 2023-05-30 11:30
@Park6102 I wasn't able to reproduce this error with 1.10.0, and my example run fine. 

I used another contract, as you haven't provided your contract source. 
For reproducing this error could you share more data with us? node version, os, your contract source, eth node, eth NW ,

**Comment by mconnelly8** [comment] 2023-06-21 17:28
Hey @Park6102, since we didn't hear back, we are closing this issue.

Web3.js 4.x has been released, so it's highly encouraged to use the latest web3.js:
https://docs.web3js.org/
https://docs.web3js.org/guides/web3_upgrade_guide/x/
https://www.npmjs.com/package/web3/v/4.0.1
https://github.com/web3/web3.js/releases/tag/v4.0.1

**Closed as completed by mconnelly8** 2023-06-21 17:28 UTC
Labels: Needs Clarification, 1.x
