### ISSUE TITLE
Error: invalid type when calling a function on my smart contract

### ISSUE THREAD

**Issue by NotLuksus** [ethereum/web3.js#4244] opened 2021-08-15 09:03 UTC
#### Expected behavior
Call function on smart contract
#### Actual behavior
Crashes when I try to call the function
#### Steps to reproduce the behavior

Function in the smart contract looks like this.
`    function nextTokenId() external view returns (uint256) {
        return _tokenIds.current();
    }`

And I'm calling it like this:
`const nextTokenId = await contract.methods.nextTokenId().call();`

What confuses me the most is that other functions from my smart contract can be called perfectly fine.

#### Logs
Mint.tsx?3968:67 Error: invalid type (argument="type", value="u", code=INVALID_ARGUMENT, version=abi/5.0.7)
    at Logger.makeError (index.js?ffb2:173)
    at Logger.throwError (index.js?ffb2:182)
    at Logger.throwArgumentError (index.js?ffb2:185)
    at AbiCoder._getCoder (abi-coder.js?99a8:63)
    at eval (abi-coder.js?99a8:40)
    at Array.map (<anonymous>)
    at AbiCoder._getCoder (abi-coder.js?99a8:39)
    at eval (abi-coder.js?99a8:86)
    at Array.map (<anonymous>)
    at AbiCoder.decode (abi-coder.js?99a8:86)
    at ABICoder.decodeParametersWith (index.js?aab1:304)
    at ABICoder.decodeParameters (index.js?aab1:285)
    at Contract._decodeMethodReturn (index.js?6e11:470)
    at Method.outputFormatter (index.js?6e11:760)
    at Method.formatOutput (index.js?7789:147)
    at sendTxCallback (index.js?7789:523)
    at cb (util.js?3022:701)
    at Item.run (browser.js?f28c:153)
    at drainQueue (browser.js?f28c:123)

#### Environment
NPM: 7.20.6
Node: 16.6.2
Web3: 1.5.2
OS: Arch Linux
Device: Desktop PC
Browser: Chromium
Developed using: Next.js

**Comment by jahvi** [comment] 2021-08-15 10:31
The method name in your comment is `nextTokenId` but you're calling `price()`, is that a typo?

**Comment by NotLuksus** [comment] 2021-08-15 10:52
oh yes my bad, I copied the wrong line of code.
Updated the comment

**Comment by luu-alex** [comment] 2021-09-13 14:52
Hey apologies for the late response, are you still having issues?

**Comment by PreetamSolulab** [comment] 2021-09-14 10:46
> Hey apologies for the late response, are you still having issues?

Yes, I'm facing the same issue. When I call owner function (which return owner of the contract) of a smart contract, it shows the same error as mentioned in this issue (except value="a" in my error). And when I call the same way coded owner function of some other smart contract, it works fine. I can't understand why?

**Comment by luu-alex** [comment] 2021-09-14 15:26
I'll dig into this more, do you have an example code snippet of when you would get this error?

**Comment by PreetamSolulab** [comment] 2021-09-14 16:14
const Stake = new web3.eth.Contract(StakeJSON.abi, StakeJSON.address)
web3.eth.accounts.wallet.add(PrivateKey)
Stake.methods.owner().call()    // It throws error on this line

**Comment by luu-alex** [comment] 2021-09-15 15:37
Thank you for the quick response :) although I'm still having trouble reproducing this. What does the smart contract function look like or can you post the abi

**Comment by PreetamSolulab** [comment] 2021-09-15 20:37
Can't really be sure that this might be the silly reason for anyone else, but here's what was wrong with my situation.
As I told before, I was able to call the almost same owner function of other contract, except the one for which this error was thrown. It turns out that in the alright working contract, 'owner' function was inherited from inherited contract 'Ownable' and it looked like following:
function owner() public view returns (address) {
    return _owner;
}

whereas in the error throwing contract, it wasn't inherited. It was written like:
function owner() public view virtual returns (address) {
    return _owner;
}
Note that additional keyword 'virtual' while function declaration was the one creating problem, still not sure about the reason, but surely that was the problem in my case.

**Comment by luu-alex** [comment] 2021-09-16 01:15
Great that you were able to solve it. 

I'll close this issue for now until something else pops up.

**Closed as completed by luu-alex** 2021-09-16 01:15 UTC
Labels: 1.x, Investigate
