### ISSUE TITLE
Signing Transactions fail with Locally created Accounts.

### ISSUE THREAD

**Issue by sirlojik** [ethereum/web3.js#932] opened 2017-07-22 05:49 UTC
i have successfully managed to create a local account, add it to wallet, unlock it and then transfer ether to it. Now, what i wanted was to send this ether from the unlocked local account to another but i always error out. Yet sending ether between the default accounts from getAccounts() always works.. my guess is that maybe it fails on signing using the new local accounts. below is my code and error i get

```js
var web3 = new Web3('http://localhost:8545');
var accounts;
var fromAddress;
web3.eth.getAccounts().then(function(o) {
    accounts = o;
    //fromAddress previously created by createAccount with password of 'newjordah' and loaded with ether
    fromAddress = "0xD7325762c8017ff83d474AAa0ca266f178e1813c";
    loadAccount("newjordah");
    var toAddress = accounts[1];
    sendEth(fromAddress, toAddress, 0.1);
});

function sendEth(_from, _to, _amount) {
    web3.eth.sendTransaction({
        from: _from,
        to: _to,
        value: web3.utils.toWei(_amount, 'ether'),
        gas: '0x2710'
    }).then(function(receipt) {
        console.log(receipt);
    });
}

function createAccount(_password) {
    var nObj = web3.eth.accounts.create();
    web3.eth.accounts.wallet.add(nObj);
    web3.eth.accounts.wallet.save(_password);
    return nObj;
}

function loadAccount(_password) {
    try {
        var l = web3.eth.accounts.wallet.load(_password);
        console.log("Account Unlocked")
        return l;
    } catch (e) {
        console.log(e);
    }
}

```
i get this error
```

web3.min.js:1 Unhandled rejection RangeError: Maximum call stack size exceeded
    at String.slice (native)
    at t (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:620555)
    at t (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:620543)
    at t (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:620543)
    at t (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:620543)
    at t (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:620543)
    at t (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:620543)
    at t (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:620543)
    at t (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:620543)
    at t (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:620543)
    at t (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:620543)
    at t (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:620543)
    at t (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:620543)
    at t (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:620543)
    at t (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:620543)
    at t (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:620543)
    at t (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:620543)
    at t (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:620543)
    at t (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:620543)
    at t (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:620543)
    at t (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:620543)
    at t (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:620543)
From previous event:
    at i.d [as _captureStackTrace] (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:490583)
    at i._then (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:519672)
    at i.then (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:518042)
    at m.signTransaction (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:676651)
    at f (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:337277)
    at Object.callback (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:337826)
    at u (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:336909)
    at file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:417689
    at XMLHttpRequest.o.onreadystatechange (file:///C:/Users/Jordah/Desktop/react/ewallet/lerna-repo/dist/web3.min.js:1:703384)
```

**Comment by frozeman** [comment] 2017-07-22 14:17
This is beta so please be careful when sending ether. I will have a look.

**Comment by frozeman** [comment] 2017-07-22 14:27
@MaiaVictor i checked my code, and this must happen inside the signing process itself.
@sirlojik can you please build the source files yourself and use the none minified version?
clone the repo and run `gulp` and use the `dist/web3.js`

**Comment by sirlojik** [comment] 2017-07-22 17:52
Am really not sure about how to build, I have run the code below and got stuck on that error. i use windows 10 and nodejs. Maybe someone could build for me this web3.js and i can debug and reproduce future bugs.
```
C:\Users\Jordah\Desktop\react\test>git clone https://github.com/ethereum/web3.js.git
Cloning into 'web3.js'...
remote: Counting objects: 13534, done.
remote: Compressing objects: 100% (246/246), done.
remote: Total 13534 (delta 160), reused 279 (delta 104), pack-reused 13162
Receiving objects: 100% (13534/13534), 24.96 MiB | 62.00 KiB/s, done.
Resolving deltas: 100% (9516/9516), done.

C:\Users\Jordah\Desktop\react\test>gulp
[20:47:57] Local gulp not found in ~\Desktop\react\test
[20:47:57] Try running: npm install gulp
C:\Users\Jordah\Desktop\react\test\web3.js>gulp build
module.js:471
    throw err;
    ^

Error: Cannot find module 'del'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Jordah\Desktop\react\test\web3.js\gulpfile.js:8:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by lukehedger** [comment] 2017-08-30 16:18
@frozeman I think I have encountered the same issue as @sirlojik whilst attempting to sign a transaction using a privateKey generated with `web3.eth.accounts`.

Version: 1.0.0-beta.18
OS: macOS Sierra 10.12.4
Browser: Chrome 60.0.3112.101

```
const account = web3.eth.accounts.create()

myContract.methods.myMethod()
  .then(tx => tx.encodeABI())
  .then(abi => account.signTransaction({ data: abi, gas: 4700000 })) // errors here
  .then(signedTx => web3.eth.sendSignedTransaction(signedTx))
```

This is the error caused by `account.signTransaction()`: https://gist.github.com/lukehedger/1e9a786eb557bd3b42d760964736c641

**Comment by lukehedger** [comment] 2017-09-07 12:42
So, as [the stack trace](https://gist.github.com/lukehedger/1e9a786eb557bd3b42d760964736c641) suggests, the max call stack size is being exceeded by an infinite execution loop of the `pad` function in [eth-lib/bytes](https://github.com/MaiaVictor/eth-lib/blob/master/src/bytes.js#L37). This function is called by the `makeSign` function in [eth-lib/accounts](https://github.com/MaiaVictor/eth-lib/blob/master/src/account.js#L48) like so:
```
Bytes.pad(1, Bytes.fromNumber(addToV + signature.recoveryParam))
```

The issue seems to be that `addToV` can be a pretty large number (`Nat.toNumber(tx.chainId || "0x1") * 2 + 35`) when using TestRPC (`chainId` will be something like `1504787153407` unless set using the `--network-id` option). So, the hex value initially passed to `Bytes.pad` will have a length of 12 and on the second pass a length of 15. The infinite loop is then entered because the condition inside `Bytes.pad` will never be true (`hex.length === 4`):
```
const pad = (l,hex) => hex.length === l*2+2 ? hex : pad(l,"0x"+"0"+hex.slice(2));
```

If I change `l` to be `16` the function will return successfully. However, I'm not sure if this is the correct solution/what side effects this may cause as I do not have enough understanding of the web3.js library.

On a side note, this calculation of `v` will cause users of TestRPC to encounter [this bug](https://github.com/ethereumjs/testrpc/issues/297). Running TestRPC with a custom, small network ID should resolve this for now `testrpc --network-id 10`.

**Comment by cmditch** [comment] 2017-09-11 21:50
@lukehedger Good catch. I'm getting the same error with a private dev geth node using `network-id > 40,000`, but can confirm this function works on Ropsten.

**Comment by robert-zaremba** [comment] 2017-09-26 01:59
I have the same issue. This makes impossible to use `web3.js` with `geth` run in the development mode (`get --dev`).

**Comment by robert-zaremba** [comment] 2017-09-26 07:39
So the @lukehedger workaround is good. However It's pretty limited for `geth` - as far I didn't found any option to make `geth` with custom genesis block as fast as `geth --dev`. Any ideas?
https://ethereum.stackexchange.com/questions/27119/what-are-the-equivalent-options-to-geth-dev

**Comment by sirlojik** [comment] 2017-09-28 14:53
Running TestRPC with a custom, small network ID should resolve this
for now testrpc
--network-id 10.

This solved the issue for me too. Everything is working as expected

**Comment by mikeifomin** [comment] 2017-10-06 15:29
Have the same issue on a private network. 
networkId == 1110011

**Comment by mikeifomin** [comment] 2017-10-09 11:38
@frozeman I'm looking forward! 
I think this issue is slowing down not only my project!

**Comment by frozeman** [comment] 2017-10-13 14:08
Please test this branch and let me know if it fixes it: https://github.com/ethereum/web3.js/pull/1111

**Comment by mikeifomin** [comment] 2017-10-16 11:57
It did not work for me =( same stack trace

**Comment by frozeman** [comment] 2017-10-16 17:49
@mikeifomin are you sure you used the branch installation?

**Comment by mikeifomin** [comment] 2017-10-17 11:57
I'm sure. But here is the code
https://github.com/mikeifomin/web3_acc_test/blob/master/index.js


And a bit of stacktrace
```
    at pad (/Users/mike/Github/web3_acc_test/node_modules/web3/
packages/web3-eth-accounts/node_modules/eth-lib/lib/bytes.js:39
:43)
    at pad (/Users/mike/Github/web3_acc_test/node_modules/web3/
packages/web3-eth-accounts/node_modules/eth-lib/lib/bytes.js:39
:43)
```

**Comment by frozeman** [comment] 2017-10-17 16:00
@mikeifomin I updated the eth-lib version to 0.2.5 please re-test.

**Comment by mikeifomin** [comment] 2017-10-17 17:42
@frozeman yay! 
The error is gone!
Huge thanks and respect from me and everyone from my team!)

**Comment by frozeman** [comment] 2017-10-17 18:06
Awesome, can you test receiving and sending test ether

**Comment by mikeifomin** [comment] 2017-10-17 21:00
I have tested manually sendTransaction method on private network. Transaction committed successfully and getBalance method for receiver account return expected amount of ether. So in my case I confirm that the issue is gone.

Maybe you talking about integration test with testrpc package?

**Comment by frozeman** [comment] 2017-10-18 12:11
currently we have only unit tests, if you want to add some testrpc integration tests, that would be awesome! :)

**Comment by frozeman** [comment] 2017-10-18 12:42
Can you also test main net transactions?

**Comment by frozeman** [comment] 2017-10-19 13:39
should now be fixed in beta.24

**Closed by frozeman** 2017-10-19 13:39 UTC
Labels: bug
