### ISSUE TITLE
Cannot get contract events: TypeError: Cannot read property 'allEvents' of undefined

### ISSUE THREAD

**Issue by vporton** [ethereum/web3.js#3320] opened 2020-01-20 21:35 UTC
#### Expected behavior

Print nothing.

#### Actual behavior

```
$ node test.js 
/home/porton/Projects/courts/app/test.js:10
ownedContract.events.allEvents({}, function(){})
                     ^

TypeError: Cannot read property 'allEvents' of undefined
```

#### Steps to reproduce the behavior

1. Start a local Ethereum server.
2. Run my script from the attached ZIP archive.

#### Logs

```
$ node test.js 
/home/porton/Projects/courts/app/test.js:10
ownedContract.events.allEvents({}, function(){})
                     ^

TypeError: Cannot read property 'allEvents' of undefined
    at Object.<anonymous> (/home/porton/Projects/courts/app/test.js:10:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

#### Versions

```
node v10.15.2
web3@1.2.5-rc.0
Ubuntu Linux 19.10
```
[bug.zip](https://github.com/ethereum/web3.js/files/4087958/bug.zip)

**Comment by cgewecke** [comment] 2020-01-21 00:30
@vporton Looked at your bug.zip and I can't reproduce the problem. Have also double-checked that allEvents work as expected. Your code looks like:
```javascript
let web3js = require("web3")

let web3 = new web3js(new web3js.providers.HttpProvider('http://localhost:8545'));

var fs = require('fs');
 
var json = fs.readFileSync('public/RewardCourts.json', 'utf8');

let ownedContract = web3.eth.contract(json.abi, '0x0')
ownedContract.events.allEvents({}, function(){})
// ownedContract.events.CourtCreated({}, function(){})
```
In your case, the contract object creation should be rewritten like this:
```diff
- let ownedContract = web3.eth.contract(json.abi, '0x0')
+ let ownedContract = new web3.eth.Contract(json.abi, '0x0');
```

Please visit the docs for [usage][1] advice about instantiating a contract. 

[1]: https://web3js.readthedocs.io/en/v1.2.4/web3-eth-contract.html

Closing b/c not reproducible.

**Closed as completed by cgewecke** 2020-01-21 00:30 UTC
