### ISSUE TITLE
Error: Failed to check for transaction receipt

### ISSUE THREAD

**Issue by justintim-es** [ethereum/web3.js#3556] opened 2020-05-31 18:33 UTC
```
web3.eth.personal.unlockAccount('0x12AdF37d82D978fD72bfcC95Ca09C0D91Bb4F4d3', password).then(unlock => {
    if(unlock) {
        web3.eth.sendTransaction({
            value: '18835938971557730',
            from: '0x12AdF37d82D978fD72bfcC95Ca09C0D91Bb4F4d3',
            to: '0x478a286CD2Cc5D997c2AA45C6CA79A2b7c1676eD'
        }).then(console.log)
    }
})
```
Gives me the follwing error
```
(node:20048) UnhandledPromiseRejectionWarning: Error: Failed to check for transaction receipt:
{}
    at Object._fireError (C:\Users\noahv\documents\cryschyp\backend\nodejs\node_modules\web3-utils\src\index.js:57:17)
    at C:\Users\noahv\documents\cryschyp\backend\nodejs\node_modules\web3-core-method\src\index.js:272:27
(node:20048) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:20048) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the 
Node.js process with a non-zero exit code
```
I first posted an issue on openethereum, but they have sent me here
web3 version
```
web3@1.2.8
```

**Comment by cgewecke** [comment] 2020-06-01 13:19
@noahsalvadordenjo 

Believe this is a race-condition issue at OE, documented in [openethereum 10672][1]. It's also reported here at #2213. 

Do you see this with any other client? Can you provide any additional details about your OE client setup?

[1]: https://github.com/openethereum/openethereum/issues/10672

**Comment by justintim-es** [comment] 2020-06-02 07:20
Openethreum version: v3.0.0
Operating system: linux
Fully synchronized: no
Restarted: yes

Im retrying now with v3.0.1

**Comment by justintim-es** [comment] 2020-06-02 07:21
I ran this in the console
```
./openethereum --jsonrpc-interface "ip" --jsonrpc-apis "all" --js
onrpc-hosts "all" --jsonrpc-cors "all"
```

**Comment by cgewecke** [comment] 2020-06-02 13:56
@noahsalvadordenjo 

Apologies, if this is only happening on OE and [OE 10762][1] remains unresolved I think it's a problem they'll have to address. 

Closing as duplicate of #2213.

[1]: https://github.com/openethereum/openethereum/issues/10672

**Closed as completed by cgewecke** 2020-06-02 13:56 UTC
Labels: 1.x
