### ISSUE TITLE
eth.getBlock fails with "Number can only safely store up to 53 bits"

### ISSUE THREAD

**Issue by MaxXor** [ethereum/web3.js#3512] opened 2020-05-11 10:37 UTC
#### Expected behavior

Get the block.

#### Actual behavior

Error "Number can only safely store up to 53 bits"

#### Example code

```js
        this.web3.eth.getBlock(number, function(error, result) {
            if (error) {
                console.log(error);
                return;
            }
            console.log(result.timestamp);
        });
```

Ethereum Studio example: https://studio.ethereum.org/5eb924ed26b4730012351a47?openFile=app/app.js Lines (133-145)

#### Steps to reproduce the behavior

1. Load the Ethereum Studio example
2. Deploy the contract
3. See the error in console log

#### Environment

Javascript with web3.js version 1.2.7

**Comment by cgewecke** [comment] 2020-05-11 14:49
@MaxXor 

Are you using the Quorum blockchain or another EVM based fork? If so, the solution is to use a Web3.js extension library like [jpmorganchase/quorum.js][1].

(Possible duplicate of #3442) 

[1]: https://github.com/jpmorganchase/quorum.js

**Comment by MaxXor** [comment] 2020-05-11 15:00
Thanks for the reply, I don't use Quorum. I've [linked](https://studio.ethereum.org/5eb924ed26b4730012351a47?openFile=app/app.js) a small example in Ethereum Studio, it's only slightly modified version of the hello-world app there, but demonstrates the problem.

I've seen similar issues here (such as https://github.com/ethereum/web3.js/issues/1960 or https://github.com/ethereum/web3.js/issues/1905), but they were closed already. The one you linked mentions timestamps specifically but the error happens already before the `console.log(result.timestamp);` inside the `getBlock` function.

**Comment by MaxXor** [comment] 2020-05-11 15:40
[das](url)

**Comment by cgewecke** [comment] 2020-05-11 16:08
@MaxXor From what I can see superblocks/ethereum-studio is [using a custom client][1]. It might be worthwhile to open this issue over there. We run a large set of tests here against 
+ ganache development client
+ geth development client
+ ethereum mainnet

They all work. 

[1]: https://github.com/SuperblocksHQ/ethereum-studio/tree/db35a5bc819bed1428972d0d31c91ea6965cec69/packages/editor/src/services/evm/src

Closing since this looks like an issue downstream from here...please just ping if you discover otherwise.

**Closed as completed by cgewecke** 2020-05-11 16:08 UTC

**Comment by dvcrn** [comment] 2021-02-24 10:07
For future googlers, in my case this was caused by using number type for gas when parsing from hex. Changing this to String fixed the issue for me: https://github.com/dvcrn/web3.js/commit/b868c5fece70fba6d34b577ef59f3fa3159390ad
